// ============================================================
// Pipeline stage definitions — the single source of truth
// for stage metadata, default checklist items, durations,
// deliverables, automation notes, blockers, and dependencies.
// ============================================================

export type StageId =
  | 'pre_project'
  | 'discovery'
  | 'planning'
  | 'design'
  | 'development'
  | 'content'
  | 'qa'
  | 'client_review'
  | 'launch_prep'
  | 'deployment'
  | 'post_launch'

export interface ChecklistItem {
  title: string
  description?: string
  requiresClient?: boolean
}

export interface PipelineStage {
  id: StageId
  label: string
  color: string
  bgColor: string
  icon: string
  typicalDuration: string
  summary: string
  deliverables: string[]
  automatable: { task: string; tool: string }[]
  requiresClientInput: string[]
  commonBlockers: string[]
  blockedBy: StageId[]
  checklist: ChecklistItem[]
}

export const PIPELINE_STAGES: PipelineStage[] = [
  {
    id: 'pre_project',
    label: 'Pre-Project',
    color: '#6B7280',
    bgColor: 'rgba(107,114,128,0.1)',
    icon: '📋',
    typicalDuration: '3–7 days',
    summary: 'Sales, contracts, scope agreement, and deposit collection before any work begins.',
    deliverables: [
      'Signed contract / proposal',
      'Deposit invoice paid',
      'Onboarding questionnaire completed',
      'Project kickoff call scheduled',
    ],
    automatable: [
      { task: 'Send proposal PDF', tool: 'Nith Digital Quotes module' },
      { task: 'Generate contract from template', tool: 'DocuSign / HelloSign / PDF template' },
      { task: 'Deposit invoice', tool: 'Nith Digital Invoices module' },
      { task: 'Onboarding form', tool: 'Typeform / Tally.so' },
      { task: 'Kickoff call booking', tool: 'Nith Digital Bookings module / Cal.com' },
    ],
    requiresClientInput: [
      'Contract signature',
      'Deposit payment',
      'Onboarding questionnaire responses',
      'Kickoff call availability',
    ],
    commonBlockers: [
      'Client delays signing contract',
      'Deposit not paid — work cannot start',
      'Unclear or missing scope in questionnaire',
    ],
    blockedBy: [],
    checklist: [
      { title: 'Send proposal / quote to client', requiresClient: false },
      { title: 'Follow up on proposal if no response within 3 days', requiresClient: false },
      { title: 'Receive verbal or written approval to proceed', requiresClient: true },
      { title: 'Generate and send contract', requiresClient: false },
      { title: 'Contract signed by client', requiresClient: true },
      { title: 'Issue deposit invoice (typically 30–50%)', requiresClient: false },
      { title: 'Deposit payment received', requiresClient: true },
      { title: 'Send client onboarding questionnaire', requiresClient: false },
      { title: 'Questionnaire completed by client', requiresClient: true },
      { title: 'Schedule kickoff call', requiresClient: true },
      { title: 'Create project folder (Drive / Notion / internal)', requiresClient: false },
      { title: 'Add project to project management tool', requiresClient: false },
    ],
  },
  {
    id: 'discovery',
    label: 'Discovery',
    color: '#7C3AED',
    bgColor: 'rgba(124,58,237,0.1)',
    icon: '🔍',
    typicalDuration: '3–5 days',
    summary: 'Understand the client\'s business, goals, target audience, and competitors before touching a design tool.',
    deliverables: [
      'Project brief document',
      'Competitor analysis (3–5 competitors)',
      'Target audience / persona summary',
      'Brand asset audit (existing logo, colours, fonts)',
      'Technical requirements notes',
    ],
    automatable: [
      { task: 'Pull competitor sites for analysis', tool: 'SimilarWeb / BuiltWith / Screaming Frog' },
      { task: 'Domain availability check', tool: 'Namecheap / GoDaddy API' },
      { task: 'Existing site technical audit', tool: 'Google PageSpeed / Screaming Frog / Ahrefs' },
    ],
    requiresClientInput: [
      'Business goals and success metrics',
      'Existing brand assets (logo, fonts, colours)',
      'Competitor examples they like / dislike',
      'Website examples they admire (inspiration)',
      'Target audience description',
      'Any existing content to migrate',
    ],
    commonBlockers: [
      'Client cannot articulate goals clearly — needs structured brief call',
      'No existing brand guidelines — design phase will expand',
      'Legacy site access credentials not provided',
    ],
    blockedBy: ['pre_project'],
    checklist: [
      { title: 'Conduct kickoff discovery call with client', requiresClient: true },
      { title: 'Document business goals and success KPIs', requiresClient: false },
      { title: 'Define primary and secondary target audiences', requiresClient: false },
      { title: 'Gather existing brand assets (logo files, brand guide)', requiresClient: true },
      { title: 'Audit any existing website (performance, content, SEO)', requiresClient: false },
      { title: 'Research 3–5 direct competitors', requiresClient: false },
      { title: 'Research 3–5 design inspirations / references client provided', requiresClient: false },
      { title: 'Document functional requirements (forms, booking, ecommerce, etc.)', requiresClient: false },
      { title: 'Confirm tech stack preferences (CMS needs, hosting, domain)', requiresClient: true },
      { title: 'Write and share project brief document with client', requiresClient: false },
      { title: 'Client approves / signs off on brief', requiresClient: true },
    ],
  },
  {
    id: 'planning',
    label: 'Planning',
    color: '#2563EB',
    bgColor: 'rgba(37,99,235,0.1)',
    icon: '🗺️',
    typicalDuration: '2–4 days',
    summary: 'Define the site architecture, content strategy, tech stack, and project timeline before design begins.',
    deliverables: [
      'Sitemap / page list',
      'Content inventory / page-by-page content plan',
      'Tech stack decision document',
      'Hosting and infrastructure plan',
      'Revised project timeline with milestones',
    ],
    automatable: [
      { task: 'Generate sitemap XML skeleton', tool: 'VS Code / script' },
      { task: 'Set up project repo and branch structure', tool: 'GitHub / GitLab' },
      { task: 'Provision staging environment', tool: 'Vercel / Netlify / WP Engine' },
      { task: 'Set up project management board', tool: 'Linear / Notion / Trello' },
    ],
    requiresClientInput: [
      'Approval on sitemap / page structure',
      'Confirmation of pages and their priority',
      'Content responsibilities (who writes what)',
      'Any third-party integrations needed (CRM, booking, payment)',
    ],
    commonBlockers: [
      'Client keeps adding pages / scope creeping at planning stage',
      'Content ownership unclear — no one knows who writes the copy',
      'Integration requirements not discovered until late — tech stack change needed',
    ],
    blockedBy: ['discovery'],
    checklist: [
      { title: 'Create full sitemap with all pages and hierarchy', requiresClient: false },
      { title: 'Define page templates needed (home, service, blog, contact, etc.)', requiresClient: false },
      { title: 'Create content plan — list every page with content owner and deadline', requiresClient: true },
      { title: 'Decide tech stack (Next.js, WordPress, Webflow, etc.)', requiresClient: false },
      { title: 'Choose hosting provider and plan', requiresClient: false },
      { title: 'Check domain ownership and registrar access', requiresClient: true },
      { title: 'List all third-party integrations required', requiresClient: false },
      { title: 'Define CMS requirements (does client need to edit content?)', requiresClient: true },
      { title: 'Set up project GitHub/GitLab repo', requiresClient: false },
      { title: 'Provision staging environment', requiresClient: false },
      { title: 'Set up project management board with milestones', requiresClient: false },
      { title: 'Share revised timeline and milestones with client', requiresClient: false },
      { title: 'Client approves sitemap and content plan', requiresClient: true },
    ],
  },
  {
    id: 'design',
    label: 'Design',
    color: '#DB2777',
    bgColor: 'rgba(219,39,119,0.1)',
    icon: '🎨',
    typicalDuration: '5–10 days',
    summary: 'Wireframes, visual design, and client-approved mockups for all key page templates before development.',
    deliverables: [
      'Wireframes for key pages',
      'Design system / style guide (colours, typography, spacing)',
      'High-fidelity mockups for all templates',
      'Mobile responsive design comps',
      'Client-signed-off design',
    ],
    automatable: [
      { task: 'Export design tokens from Figma', tool: 'Figma / Style Dictionary' },
      { task: 'Generate colour palette from brand assets', tool: 'Figma / Coolors / Adobe Color' },
      { task: 'Compress and optimise image assets', tool: 'Squoosh / Sharp / ImageOptim' },
    ],
    requiresClientInput: [
      'Wireframe approval before moving to high-fidelity',
      'Feedback rounds on mockups (typically 2 rounds)',
      'Final sign-off on design before development',
      'Any brand preferences not captured in brief',
    ],
    commonBlockers: [
      'Client gives vague feedback ("make it pop") — needs structured feedback form',
      'Unlimited revision requests without change order — scope creep',
      'Client stakeholder alignment issues (multiple decision makers)',
      'Waiting on brand assets from client',
    ],
    blockedBy: ['planning'],
    checklist: [
      { title: 'Set up Figma project with shared access for client', requiresClient: false },
      { title: 'Define colour palette from brand guidelines', requiresClient: false },
      { title: 'Define typography system (headings, body, sizes)', requiresClient: false },
      { title: 'Create spacing and grid system', requiresClient: false },
      { title: 'Design wireframes for homepage', requiresClient: false },
      { title: 'Design wireframes for inner pages (service, about, contact)', requiresClient: false },
      { title: 'Share wireframes with client — round 1 feedback', requiresClient: true },
      { title: 'Revise wireframes based on feedback', requiresClient: false },
      { title: 'Wireframes signed off', requiresClient: true },
      { title: 'Create high-fidelity desktop mockup — homepage', requiresClient: false },
      { title: 'Create high-fidelity mockups — all page templates', requiresClient: false },
      { title: 'Create mobile mockups for all templates', requiresClient: false },
      { title: 'Design interactive states (hover, focus, active, error)', requiresClient: false },
      { title: 'Share mockups with client — round 1 feedback', requiresClient: true },
      { title: 'Apply revisions (within agreed revision limit)', requiresClient: false },
      { title: 'Share mockups with client — round 2 feedback', requiresClient: true },
      { title: 'Final design sign-off from client (written)', requiresClient: true },
      { title: 'Export all assets (icons, images, fonts, SVGs)', requiresClient: false },
      { title: 'Document design tokens for developer handoff', requiresClient: false },
    ],
  },
  {
    id: 'development',
    label: 'Development',
    color: '#059669',
    bgColor: 'rgba(5,150,105,0.1)',
    icon: '💻',
    typicalDuration: '10–21 days',
    summary: 'Build the site from approved designs — environment setup, frontend, backend, CMS, and integrations.',
    deliverables: [
      'Local development environment',
      'Staging site matching approved designs',
      'CMS setup and content types configured',
      'All integrations wired up (forms, analytics, payments)',
      'Code pushed to repository',
    ],
    automatable: [
      { task: 'Scaffold project from template', tool: 'create-next-app / WP-CLI / Astro CLI' },
      { task: 'CI/CD pipeline setup', tool: 'GitHub Actions / Vercel auto-deploy' },
      { task: 'Dependency updates and security audit', tool: 'npm audit / Dependabot' },
      { task: 'Linting and formatting', tool: 'ESLint / Prettier / Husky pre-commit' },
      { task: 'Deploy to staging on every push', tool: 'Vercel preview deployments / Netlify' },
      { task: 'Set up error monitoring', tool: 'Sentry / LogRocket' },
    ],
    requiresClientInput: [
      'Any API keys or third-party service credentials',
      'CMS content structure approval',
      'Payment gateway account details (if ecommerce)',
      'Domain registrar access for staging DNS',
    ],
    commonBlockers: [
      'Waiting on client to provide third-party API keys',
      'Design inconsistencies discovered during build — needs design clarification',
      'Content not ready — impossible to build pages without real copy',
      'Third-party integration behaving unexpectedly',
      'Hosting environment limitations',
    ],
    blockedBy: ['design'],
    checklist: [
      { title: 'Initialise project repository and push to GitHub', requiresClient: false },
      { title: 'Set up local development environment', requiresClient: false },
      { title: 'Configure CI/CD pipeline (auto-deploy to staging)', requiresClient: false },
      { title: 'Install and configure Tailwind / CSS framework', requiresClient: false },
      { title: 'Build global layout (header, footer, navigation)', requiresClient: false },
      { title: 'Build design system components (buttons, typography, cards, forms)', requiresClient: false },
      { title: 'Build homepage template', requiresClient: false },
      { title: 'Build inner page templates (service, about, blog, contact)', requiresClient: false },
      { title: 'Implement responsive layouts (mobile-first)', requiresClient: false },
      { title: 'Set up and configure CMS (if required)', requiresClient: false },
      { title: 'Model content types in CMS', requiresClient: false },
      { title: 'Build contact / enquiry form with email notification', requiresClient: false },
      { title: 'Integrate analytics (Google Analytics 4 / Plausible)', requiresClient: false },
      { title: 'Set up cookie consent (GDPR)', requiresClient: false },
      { title: 'Integrate any third-party tools (booking, chat, CRM)', requiresClient: false },
      { title: 'Implement ecommerce / payment flow (if applicable)', requiresClient: false },
      { title: 'Add all placeholder / real content to pages', requiresClient: false },
      { title: 'Set up 404 and error pages', requiresClient: false },
      { title: 'Implement animations and micro-interactions', requiresClient: false },
      { title: 'Review all pages against approved designs', requiresClient: false },
      { title: 'Internal development review / code review', requiresClient: false },
    ],
  },
  {
    id: 'content',
    label: 'Content',
    color: '#D97706',
    bgColor: 'rgba(217,119,6,0.1)',
    icon: '✍️',
    typicalDuration: '5–10 days (often parallel with dev)',
    summary: 'Final copywriting, imagery, SEO metadata, and all content populated into the live build.',
    deliverables: [
      'Final approved copy for all pages',
      'Optimised images (compressed, correct dimensions)',
      'SEO metadata (title tags, meta descriptions) for all pages',
      'Blog posts / case studies (if in scope)',
      'Alt text for all images',
    ],
    automatable: [
      { task: 'Image compression', tool: 'Sharp / Squoosh / TinyPNG API' },
      { task: 'Generate meta description drafts', tool: 'AI-assisted writing (Claude / GPT)' },
      { task: 'Keyword research', tool: 'Ahrefs / Semrush / Google Search Console' },
      { task: 'XML sitemap generation', tool: 'next-sitemap / Yoast SEO / Screaming Frog' },
    ],
    requiresClientInput: [
      'Final approved copy (if client is writing)',
      'High-resolution photography / video assets',
      'Testimonials and case study approvals',
      'Legal pages (privacy policy, terms of service)',
    ],
    commonBlockers: [
      'Client copy never arrives — the single biggest blocker in web projects',
      'Low-quality stock images — site looks generic',
      'Missing or blurry logo files',
      'Copy changes after design was finalised — layout breaks',
    ],
    blockedBy: ['planning'],
    checklist: [
      { title: 'Confirm content ownership (client writes or agency writes)', requiresClient: true },
      { title: 'Receive final homepage copy from client', requiresClient: true },
      { title: 'Receive final copy for all inner pages', requiresClient: true },
      { title: 'Proofread and edit all copy', requiresClient: false },
      { title: 'Source and licence all photography / imagery', requiresClient: false },
      { title: 'Compress and optimise all images (WebP, correct dimensions)', requiresClient: false },
      { title: 'Write SEO title tags for all pages', requiresClient: false },
      { title: 'Write meta descriptions for all pages', requiresClient: false },
      { title: 'Add alt text to all images', requiresClient: false },
      { title: 'Implement structured data / schema markup', requiresClient: false },
      { title: 'Populate all page content into CMS / codebase', requiresClient: false },
      { title: 'Review legal pages (privacy policy, cookie policy, T&Cs)', requiresClient: true },
      { title: 'Add testimonials and social proof', requiresClient: true },
      { title: 'Generate and submit XML sitemap', requiresClient: false },
      { title: 'Configure robots.txt', requiresClient: false },
      { title: 'Set up Google Search Console property', requiresClient: false },
    ],
  },
  {
    id: 'qa',
    label: 'Quality Assurance',
    color: '#DC2626',
    bgColor: 'rgba(220,38,38,0.1)',
    icon: '🧪',
    typicalDuration: '3–5 days',
    summary: 'Systematic testing across browsers, devices, performance, accessibility, and security before client review.',
    deliverables: [
      'Cross-browser test results (Chrome, Safari, Firefox, Edge)',
      'Mobile device test results',
      'Lighthouse performance scores (target 90+)',
      'Accessibility audit (WCAG 2.1 AA)',
      'Security checklist',
      'Form and functionality test results',
    ],
    automatable: [
      { task: 'Lighthouse / Core Web Vitals audit', tool: 'Lighthouse CI / PageSpeed Insights' },
      { task: 'Broken link check', tool: 'Screaming Frog / Dead Link Checker' },
      { task: 'HTML / CSS validation', tool: 'W3C Validator' },
      { task: 'Accessibility scan', tool: 'axe / WAVE / Lighthouse' },
      { task: 'Security headers check', tool: 'securityheaders.com / Mozilla Observatory' },
      { task: 'Cross-browser visual regression', tool: 'BrowserStack / Playwright / Cypress' },
      { task: 'Spell check', tool: 'Grammarly / cSpell in CI' },
    ],
    requiresClientInput: [
      'Provide test data for any forms or checkout flows',
      'Confirm all functional requirements have been met',
    ],
    commonBlockers: [
      'Performance issues requiring significant refactoring',
      'Safari CSS bugs — always test Safari early',
      'Accessibility failures that require design changes',
      'Third-party script slowing page load',
    ],
    blockedBy: ['development', 'content'],
    checklist: [
      { title: 'Test all pages in Chrome (desktop)', requiresClient: false },
      { title: 'Test all pages in Safari (desktop)', requiresClient: false },
      { title: 'Test all pages in Firefox (desktop)', requiresClient: false },
      { title: 'Test all pages in Edge (desktop)', requiresClient: false },
      { title: 'Test on iPhone (Safari mobile)', requiresClient: false },
      { title: 'Test on Android Chrome', requiresClient: false },
      { title: 'Test all responsive breakpoints (320px → 1440px+)', requiresClient: false },
      { title: 'Test all forms (valid submission, validation errors, success state)', requiresClient: false },
      { title: 'Test all CTAs and internal links', requiresClient: false },
      { title: 'Check all external links open in new tab', requiresClient: false },
      { title: 'Run Lighthouse audit — Performance score 90+', requiresClient: false },
      { title: 'Run Lighthouse audit — Accessibility score 90+', requiresClient: false },
      { title: 'Run Lighthouse audit — SEO score 90+', requiresClient: false },
      { title: 'Run Lighthouse audit — Best Practices score 90+', requiresClient: false },
      { title: 'Check Core Web Vitals (LCP, FID/INP, CLS)', requiresClient: false },
      { title: 'Scan for broken links and 404s', requiresClient: false },
      { title: 'Check all images have alt text', requiresClient: false },
      { title: 'Check keyboard navigation works throughout site', requiresClient: false },
      { title: 'Check colour contrast meets WCAG AA', requiresClient: false },
      { title: 'Verify contact form sends email correctly', requiresClient: false },
      { title: 'Verify analytics is firing correctly', requiresClient: false },
      { title: 'Check cookie consent banner works', requiresClient: false },
      { title: 'Check security headers (CSP, HSTS, X-Frame-Options)', requiresClient: false },
      { title: 'Verify SSL certificate is valid on staging', requiresClient: false },
      { title: 'Check 404 page is styled correctly', requiresClient: false },
      { title: 'Check page titles and meta descriptions on all pages', requiresClient: false },
      { title: 'Test site search (if applicable)', requiresClient: false },
      { title: 'Test ecommerce checkout flow end-to-end (if applicable)', requiresClient: false },
      { title: 'Fix all bugs found — re-test after fixes', requiresClient: false },
    ],
  },
  {
    id: 'client_review',
    label: 'Client Review',
    color: '#0891B2',
    bgColor: 'rgba(8,145,178,0.1)',
    icon: '👤',
    typicalDuration: '3–7 days',
    summary: 'Client reviews the staging site, raises feedback, and gives written approval before launch.',
    deliverables: [
      'Staging site URL shared with client',
      'Client feedback document',
      'Agreed revisions applied',
      'Written launch approval from client',
    ],
    automatable: [
      { task: 'Share staging link', tool: 'Vercel preview URL / staging subdomain' },
      { task: 'Collect feedback in structured form', tool: 'Notion / Google Form / Pastel' },
    ],
    requiresClientInput: [
      'Access staging site and review all pages',
      'Submit consolidated feedback (one round)',
      'Written sign-off / go-ahead for launch',
    ],
    commonBlockers: [
      'Client keeps finding new things to change — set clear revision limits in contract',
      'Decision by committee — multiple stakeholders with conflicting feedback',
      'Client silent for days — chase with deadline and consequences',
      'New scope requests disguised as "revisions"',
    ],
    blockedBy: ['qa'],
    checklist: [
      { title: 'Share staging URL with client with review instructions', requiresClient: false },
      { title: 'Set a review deadline (typically 5 business days)', requiresClient: false },
      { title: 'Conduct client walkthrough call of the staging site', requiresClient: true },
      { title: 'Receive consolidated feedback from client', requiresClient: true },
      { title: 'Triage feedback — separate bugs from scope changes', requiresClient: false },
      { title: 'Apply agreed revisions (within contract scope)', requiresClient: false },
      { title: 'Re-share updated staging for final check', requiresClient: true },
      { title: 'Receive written launch approval from client', requiresClient: true },
      { title: 'Issue final balance invoice', requiresClient: false },
      { title: 'Confirm final balance payment received', requiresClient: true },
    ],
  },
  {
    id: 'launch_prep',
    label: 'Launch Prep',
    color: '#EA580C',
    bgColor: 'rgba(234,88,12,0.1)',
    icon: '🚀',
    typicalDuration: '1–2 days',
    summary: 'DNS, domain, SSL, redirects, and environment configuration ready to flip the switch.',
    deliverables: [
      'Production environment configured',
      'DNS records updated',
      'SSL certificate active on production domain',
      '301 redirects configured (if migration)',
      'Environment variables set for production',
    ],
    automatable: [
      { task: 'SSL provisioning', tool: 'Let\'s Encrypt / Vercel / Cloudflare' },
      { task: 'DNS propagation check', tool: 'dnschecker.org / dig' },
      { task: 'Redirect rules from old URLs', tool: 'Next.js redirects / Cloudflare rules / .htaccess' },
      { task: 'CDN configuration', tool: 'Cloudflare / Vercel Edge Network' },
    ],
    requiresClientInput: [
      'Domain registrar login or DNS access (or delegation to you)',
      'Hosting account access if not provisioned by agency',
      'Confirm email / MX records to preserve (do not break email!)',
      'Approval on redirect plan for existing URLs',
    ],
    commonBlockers: [
      'Client cannot find domain registrar login details',
      'DNS propagation takes up to 48 hours — plan ahead',
      'MX records for email accidentally broken during DNS changes',
      'Production environment variables missing or wrong',
      'Old hosting provider has slow TTL — update TTL 24h before launch',
    ],
    blockedBy: ['client_review'],
    checklist: [
      { title: 'Confirm production hosting environment is provisioned', requiresClient: false },
      { title: 'Set all production environment variables', requiresClient: false },
      { title: 'Configure custom domain in hosting provider', requiresClient: false },
      { title: 'Obtain domain registrar access from client', requiresClient: true },
      { title: 'Lower DNS TTL to 300s (5 min) at least 24h before launch', requiresClient: false },
      { title: 'Document all current DNS records before any changes', requiresClient: false },
      { title: 'Identify and preserve MX records (email must not break)', requiresClient: false },
      { title: 'Configure A / CNAME records pointing to new host', requiresClient: false },
      { title: 'Verify SSL certificate provisioned and valid', requiresClient: false },
      { title: 'Audit all URLs from old site — build 301 redirect map', requiresClient: false },
      { title: 'Implement 301 redirects for all changed / removed URLs', requiresClient: false },
      { title: 'Test all redirects on staging with production domain preview', requiresClient: false },
      { title: 'Confirm production build passes (npm run build with zero errors)', requiresClient: false },
      { title: 'Run final Lighthouse audit on production build', requiresClient: false },
      { title: 'Back up old website (if migration)', requiresClient: false },
    ],
  },
  {
    id: 'deployment',
    label: 'Deployment',
    color: '#16A34A',
    bgColor: 'rgba(22,163,74,0.1)',
    icon: '✅',
    typicalDuration: '1 day',
    summary: 'Go live — deploy to production, verify everything works on the live domain, set up monitoring.',
    deliverables: [
      'Live website on production domain',
      'DNS fully propagated and SSL active',
      'Uptime monitoring configured',
      'Analytics verified on live domain',
      'Post-launch smoke test passed',
    ],
    automatable: [
      { task: 'Deploy to production via CI/CD', tool: 'Vercel / Netlify / GitHub Actions' },
      { task: 'Uptime monitoring', tool: 'UptimeRobot / Better Uptime / Vercel Analytics' },
      { task: 'Lighthouse post-launch audit', tool: 'Lighthouse CI / PageSpeed Insights' },
      { task: 'Submit sitemap to Google Search Console', tool: 'Google Search Console' },
    ],
    requiresClientInput: [
      'Confirm agreed launch window (avoid Monday mornings)',
      'Be on standby during go-live in case issues arise',
    ],
    commonBlockers: [
      'DNS still propagating — site not live everywhere yet',
      'Environment variable missing in production',
      'Form email not sending on production (SMTP config)',
      'CDN caching serving old content',
    ],
    blockedBy: ['launch_prep'],
    checklist: [
      { title: 'Confirm client is available and aware of launch time', requiresClient: true },
      { title: 'Trigger production deployment', requiresClient: false },
      { title: 'Verify DNS has propagated (check from multiple locations)', requiresClient: false },
      { title: 'Verify SSL is active and shows padlock in browser', requiresClient: false },
      { title: 'Smoke test all pages on live domain', requiresClient: false },
      { title: 'Test contact form on live domain (email received)', requiresClient: false },
      { title: 'Test all forms and CTA flows on live domain', requiresClient: false },
      { title: 'Verify analytics is firing on live domain', requiresClient: false },
      { title: 'Verify Google Search Console connected to live domain', requiresClient: false },
      { title: 'Submit XML sitemap to Google Search Console', requiresClient: false },
      { title: 'Check all redirects work on live domain', requiresClient: false },
      { title: 'Set up uptime monitoring (UptimeRobot or similar)', requiresClient: false },
      { title: 'Set up error alerting (Sentry or hosting alerts)', requiresClient: false },
      { title: 'Run final Lighthouse on live domain and record scores', requiresClient: false },
      { title: 'Purge CDN cache if needed', requiresClient: false },
      { title: 'Announce launch to client — send congratulatory email', requiresClient: false },
    ],
  },
  {
    id: 'post_launch',
    label: 'Post-Launch',
    color: '#D4A84B',
    bgColor: 'rgba(212,168,75,0.1)',
    icon: '🎓',
    typicalDuration: '1–3 days + ongoing',
    summary: 'Client training, documentation handoff, and setup of ongoing maintenance or retainer.',
    deliverables: [
      'Client training session (CMS usage, basic updates)',
      'Project handoff document (logins, hosting, DNS, backup)',
      'Maintenance / retainer proposal',
      'Final project invoice (if not already paid)',
      '30-day check-in scheduled',
    ],
    automatable: [
      { task: 'Generate handoff document from project data', tool: 'Notion template / PDF' },
      { task: 'Schedule 30-day check-in', tool: 'Nith Digital Bookings / Cal.com' },
      { task: 'Automated monthly backup', tool: 'Hosting provider / All-in-One WP Migration / Vercel' },
    ],
    requiresClientInput: [
      'Attend CMS training session',
      'Confirm receipt of all login credentials',
      'Review and sign maintenance agreement (if applicable)',
      'Provide testimonial / review (request politely)',
    ],
    commonBlockers: [
      'Client wants ongoing ad-hoc changes without maintenance retainer',
      'Handoff incomplete — access credentials not transferred',
      'Client edits site incorrectly after training and breaks things',
    ],
    blockedBy: ['deployment'],
    checklist: [
      { title: 'Conduct CMS training session with client (record it)', requiresClient: true },
      { title: 'Create handoff document (all logins, hosting, DNS, repo)', requiresClient: false },
      { title: 'Transfer all access credentials to client securely', requiresClient: false },
      { title: 'Send final balance invoice (if outstanding)', requiresClient: false },
      { title: 'Confirm final payment received', requiresClient: true },
      { title: 'Send maintenance / retainer proposal', requiresClient: false },
      { title: 'Schedule 30-day post-launch check-in call', requiresClient: true },
      { title: 'Set up automated backups', requiresClient: false },
      { title: 'Document any known technical debt or future improvements', requiresClient: false },
      { title: 'Archive project files in shared folder', requiresClient: false },
      { title: 'Request Google / Trustpilot review from client', requiresClient: true },
      { title: 'Add project to portfolio (with client permission)', requiresClient: true },
      { title: 'Send 30-day check-in (performance review, any issues)', requiresClient: false },
      { title: 'Mark project as completed', requiresClient: false },
    ],
  },
]

export const STAGE_ORDER: StageId[] = PIPELINE_STAGES.map((s) => s.id)

export function getStage(id: StageId): PipelineStage {
  return PIPELINE_STAGES.find((s) => s.id === id)!
}

export const STATUS_LABELS: Record<string, string> = {
  pre_project: 'Pre-Project',
  discovery: 'Discovery',
  planning: 'Planning',
  design: 'Design',
  development: 'Development',
  content: 'Content',
  qa: 'Quality Assurance',
  client_review: 'Client Review',
  launch_prep: 'Launch Prep',
  deployment: 'Deployment',
  post_launch: 'Post-Launch',
  completed: 'Completed',
  on_hold: 'On Hold',
}

export const PROJECT_TYPE_LABELS: Record<string, string> = {
  website: 'Website',
  ecommerce: 'E-commerce',
  web_app: 'Web App',
  landing_page: 'Landing Page',
  redesign: 'Redesign',
  other: 'Other',
}
