import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const prospects = [
  // ============================================================
  // CASTLE DOUGLAS — Beauty & Wellness
  // ============================================================
  {
    business_name: "Blackburns Hair & Beauty Castle Douglas",
    url: "https://www.blackburnshairsalon.co.uk",
    location: "140-142 King Street, Castle Douglas, DG7 1LU",
    sector: "Beauty & Wellness",
    contact_phone: "01556 503652",
    contact_email: "info@blackburnshairsalon.co.uk",
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online booking and local SEO",
    why_them: "Well-established hair and beauty salon on Castle Douglas's main shopping street. Has a live website but limited local SEO reach — no online booking. A modernised site with Fresha/Treatwell integration and DG7 hair salon SEO would drive more bookings.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, yell.com, blackburnshairsalon.co.uk",
  },
  {
    business_name: "A Cut Above The Rest Castle Douglas",
    url: null,
    location: "144 King Street, Castle Douglas, DG7 1LU",
    sector: "Beauty & Wellness",
    contact_phone: "01556 502552",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple brochure website with online booking",
    why_them: "High Street hairdresser in Castle Douglas with no website presence at all. A basic hair salon site with an online booking widget would capture the growing share of searchers who book salons online — particularly visitors to the town.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info directory",
  },
  {
    business_name: "New Image Hairdressers Castle Douglas",
    url: null,
    location: "86-88 King Street, Castle Douglas, DG7 1AD",
    sector: "Beauty & Wellness",
    contact_phone: "01556 504995",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brochure website with service menu, pricing and booking link",
    why_them: "Established King Street hairdresser with no web presence. In a Food Town that attracts visitors and day-trippers, a simple website would improve discoverability for anyone searching for a haircut in Castle Douglas while visiting.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info directory, castledouglas.com",
  },
  {
    business_name: "Thirtyfour Salon Gatehouse of Fleet",
    url: null,
    location: "34 High Street, Gatehouse of Fleet, Castle Douglas, DG7 2HP",
    sector: "Beauty & Wellness",
    contact_phone: "01557 814326",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brochure website with service list and online booking",
    why_them: "Hairdresser on Gatehouse of Fleet High Street with no web presence. Gatehouse is a busy tourist village and searchers looking for salons while staying locally have no way to find this business digitally.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "yelp.co.uk, bigreddirectory.com",
  },

  // ============================================================
  // CASTLE DOUGLAS — Trades & Construction
  // ============================================================
  {
    business_name: "TAS Building Supplies Castle Douglas",
    url: "https://www.tasbuildingsupplies.com",
    location: "Station Yard Industrial Estate, Castle Douglas, DG7 1LA",
    sector: "Trades & Construction",
    contact_phone: "01556 504165",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.7,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and trade e-commerce enhancement",
    why_them: "Local builder's merchant and supply company with a live website. Could benefit from improved local search visibility to capture tradespeople searching for materials across the Stewartry — a targeted content and SEO strategy would improve trade account acquisition.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info directory, tasbuildingsupplies.com",
  },
  {
    business_name: "Derek Mitchell Electrical Castle Douglas",
    url: "https://www.derekmitchellelec.co.uk",
    location: "Unit 1 Station Yard, Castle Douglas, DG7 1LA",
    sector: "Trades & Construction",
    contact_phone: "01387 268868",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with local SEO for Stewartry electrician searches",
    why_them: "Established electrical contractor based in Castle Douglas. Has a website but trades on referrals — a targeted local SEO push for 'electrician Castle Douglas' and 'electrician DG7' would generate consistent inbound leads across the Stewartry.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, bigreddirectory.com, derekmitchellelec.co.uk",
  },
  {
    business_name: "Bryan Swales Auto Repairs Castle Douglas",
    url: "https://bryanswales.co.uk",
    location: "Station Yard Industrial Estate, Oakwell Road, Castle Douglas, DG7 1LA",
    sector: "Automotive",
    contact_phone: "01556 502918",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Local SEO and online MOT/service booking",
    why_them: "Independent garage offering MOT, servicing and repairs in Castle Douglas. Has a live website. Adding an online MOT booking system and targeting 'MOT Castle Douglas' search terms would capture the significant local and passing trade searching for a reliable local garage.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "bryanswales.co.uk, yell.com, checkmot.com",
  },
  {
    business_name: "Castle Douglas MOT Centre",
    url: null,
    location: "Unit 6, Oakwell Road, Castle Douglas, DG7 2LH",
    sector: "Automotive",
    contact_phone: "01556 503090",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple garage website with online MOT booking",
    why_them: "Dedicated MOT test centre in Castle Douglas with no website. Online MOT booking is now the default expectation — a simple site with an online booking form and local SEO would capture a large share of DG7 MOT searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "yell.com, checkmot.com, garagedirectory.co.uk",
  },
  {
    business_name: "Stewartry Tyres Castle Douglas",
    url: "https://www.castledouglastyres.co.uk",
    location: "Oakwell Mills, Oakwell Road, Castle Douglas, DG7 1JY",
    sector: "Automotive",
    contact_phone: "01556 503777",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online tyre pricing and booking",
    why_them: "Local tyre specialist serving Castle Douglas. Has a website but the tyre industry has increasingly moved to online quotes and booking — a modernised site with an online tyre finder and fitting booking system would give them a meaningful edge.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, castledouglastyres.co.uk",
  },

  // ============================================================
  // CASTLE DOUGLAS — Food & Drink
  // ============================================================
  {
    business_name: "Nikos Mezze Greek Restaurant Castle Douglas",
    url: "https://www.nikosgreekrestaurant.com",
    location: "139 King Street, Castle Douglas, DG7 1DX",
    sector: "Food & Drink",
    contact_phone: "01556 504345",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online booking and local SEO",
    why_them: "Greek mezze restaurant on the main King Street — a unique dining offer in the town. Has a website but limited SEO for searches like 'Greek restaurant Dumfries and Galloway'. A refreshed site with reservation integration and local SEO would drive bookings from both locals and food tourism visitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, nikosgreekrestaurant.com, TripAdvisor",
  },
  {
    business_name: "Mad Hatter Cafe Castle Douglas",
    url: "https://www.cafescastledouglas.co.uk",
    location: "53 King Street, Castle Douglas, DG7 1AE",
    sector: "Food & Drink",
    contact_phone: "01556 502712",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and local cafe search optimisation",
    why_them: "Independent cafe on King Street — a hub for the local community. Has a web presence but limited discoverability for tourist searches. SEO targeting 'cafe Castle Douglas' and 'coffee Castle Douglas' would improve their visibility to the significant visitor footfall the Food Town attracts.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, cafescastledouglas.co.uk",
  },
  {
    business_name: "Street Lights Coffee House Castle Douglas",
    url: null,
    location: "187 King Street, Castle Douglas, DG7 1DZ",
    sector: "Food & Drink",
    contact_phone: "01556 504222",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brochure website with menu, opening hours and local SEO",
    why_them: "Coffee house on King Street with no website. Castle Douglas is marketed as a Food Town, meaning many visitors research food and drink options online before arriving — a simple web presence with a menu and Google Maps integration would capture this pre-visit search traffic.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info directory",
  },
  {
    business_name: "Scottish Pantry Castle Douglas",
    url: null,
    location: "184-186 King Street, Castle Douglas, DG7 1DA",
    sector: "Food & Drink",
    contact_phone: "01556 502232",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brochure website with menu, catering enquiry and local SEO",
    why_them: "Cafe and catering business on King Street in Castle Douglas's Food Town. No website presence — the catering arm (listed separately in the directory) suggests event work that would benefit enormously from an online presence and enquiry form.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info directory",
  },
  {
    business_name: "Jewel in the Crown Castle Douglas",
    url: "https://www.thejewelinthe-crown.co.uk",
    location: "17 King Street, Castle Douglas, DG7 1AA",
    sector: "Food & Drink",
    contact_phone: "01556 505999",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.7,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO improvement and online ordering integration",
    why_them: "Indian restaurant and takeaway at the bottom of King Street. Has a website but limited SEO reach for 'Indian restaurant Castle Douglas' searches. A localised SEO campaign with targeted content would improve discoverability against competitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, thejewelinthe-crown.co.uk",
  },
  {
    business_name: "Glen Urr Ice Cream & Sorbets",
    url: "https://www.glenurr.co.uk",
    location: "Halmyre, Haugh of Urr, Castle Douglas, DG7 3LB",
    sector: "Food & Drink",
    contact_phone: "01556 660326",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 8,
    score_access: 7,
    score_overall: 6.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with stockists map and local SEO",
    why_them: "Artisan ice cream and sorbet producer in Haugh of Urr — a food tourism gem in the Castle Douglas area. Has a website but limited visibility. A refreshed site with a stockists finder and targeted SEO for 'artisan ice cream Dumfries and Galloway' would support both direct sales and wholesale growth.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, glenurr.co.uk",
  },
  {
    business_name: "The Glenisle Inn Palnackie",
    url: "https://www.glenisleinn.co.uk",
    location: "Port Road, Palnackie, Castle Douglas, DG7 1PG",
    sector: "Food & Drink",
    contact_phone: "01556 600429",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and website refresh with accommodation and dining focus",
    why_them: "Village pub and inn in Palnackie, near the Urr estuary. Has a live website but rural pubs in this area are frequently under-served by local SEO — a targeted push for 'pub Palnackie' and 'riverside pub Dalbeattie area' would capture both locals and touring visitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, glenisleinn.co.uk",
  },
  {
    business_name: "Toffee Shop Castle Douglas",
    url: "https://www.the-toffee-shop.co.uk",
    location: "109 King Street, Castle Douglas, DG7 1LZ",
    sector: "Retail",
    contact_phone: "01556 502903",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "E-commerce enhancement and local SEO",
    why_them: "Specialist confectionery shop on King Street with a live website. The handmade toffee angle is a powerful food tourism hook — improving their site's e-commerce capability and SEO for 'Scottish fudge' and 'handmade toffee gift' searches would drive both in-store and online sales.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, the-toffee-shop.co.uk",
  },
  {
    business_name: "In House Chocolates Castle Douglas",
    url: "https://www.inhousechocolates.biz",
    location: "King Street, Castle Douglas, DG7 1LU",
    sector: "Retail",
    contact_phone: "01556 503037",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "E-commerce and food tourism SEO",
    why_them: "Artisan chocolate maker and gift shop on King Street in Scotland's Food Town. Has a website but limited e-commerce functionality. A proper online gift shop with postal options and strong food tourism SEO would extend their reach well beyond Castle Douglas day-trippers.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, inhousechocolates.biz",
  },
  {
    business_name: "Irvings Homestyle Bakery Castle Douglas",
    url: "https://www.irvingsbakery.co.uk",
    location: "Unit 1, Abercromby Industrial Estate, Castle Douglas, DG7 1LH",
    sector: "Retail",
    contact_phone: "01556 504162",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with local delivery/collection and SEO",
    why_them: "Local bakery producing homestyle bread and baked goods. Has a website. With the growing trend for local artisan bakers, an improved site with online ordering and local delivery showcasing their Food Town credentials would drive growth.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, irvingsbakery.co.uk",
  },

  // ============================================================
  // CASTLE DOUGLAS — Retail
  // ============================================================
  {
    business_name: "G.Livingston & Son Castle Douglas",
    url: "https://www.glivingston.co.uk",
    location: "69-75 King Street, Castle Douglas, DG7 1AE",
    sector: "Retail",
    contact_phone: "01556 502408",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with e-commerce and local SEO",
    why_them: "Long-established independent general store on King Street. Has a website but an independent department-style retailer in a Food Town benefits enormously from a well-optimised online presence to capture both local shoppers and visitors researching what to buy locally.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, glivingston.co.uk",
  },
  {
    business_name: "Tessera Home Interiors Castle Douglas",
    url: "https://www.tesserahomeinteriors.co.uk",
    location: "58 King Street, Castle Douglas, DG7 1AD",
    sector: "Retail",
    contact_phone: "01556 503003",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "E-commerce and interior design SEO",
    why_them: "Independent home interiors and lifestyle shop on King Street. Has a website. The home interiors market has strong e-commerce potential — improving product photography, adding online shopping and targeting 'home interiors Dumfries and Galloway' searches would meaningfully extend reach.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, tesserahomeinteriors.co.uk",
  },
  {
    business_name: "Mitchells Greengrocer Castle Douglas",
    url: "https://www.mitchellscd.co.uk",
    location: "138 King Street, Castle Douglas, DG7 1LU",
    sector: "Retail",
    contact_phone: "01556 502077",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with local SEO and seasonal produce showcase",
    why_them: "Independent greengrocer and fishmonger on King Street — a stalwart of the Castle Douglas Food Town. Has a website. The food provenance angle (local fish, seasonal veg) is a compelling story for a modernised site targeting both locals and food tourists.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, mitchellscd.co.uk",
  },
  {
    business_name: "Grierson Bros Butchers Castle Douglas",
    url: "https://www.griersonbros.co.uk",
    location: "148 King Street, Castle Douglas, DG7 1LU",
    sector: "Retail",
    contact_phone: "01556 502637",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online ordering and provenance story",
    why_them: "Award-winning traditional butcher in Castle Douglas's Food Town. Has a website. The Galloway beef and local provenance story is powerful for food tourism searches — improving the site with an online shop and better SEO would extend their reach for meat delivery beyond the town.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, griersonbros.co.uk",
  },
  {
    business_name: "McGill Duncan Gallery Castle Douglas",
    url: "https://www.mcgillduncangallery.com",
    location: "231 King Street, Castle Douglas, DG7 1DT",
    sector: "Retail",
    contact_phone: "01556 502468",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.3,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "E-commerce and arts/gallery SEO",
    why_them: "Art gallery and framing business at the top end of King Street. Has a website. The Kirkcudbright/Castle Douglas artists' community is a major draw for art buyers — a properly SEO-optimised site with online gallery and purchase capability would capture national art collectors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, mcgillduncangallery.com",
  },
  {
    business_name: "Castle Douglas Cycles",
    url: "https://www.cdbikes.co.uk",
    location: "11 Church Street, Castle Douglas, DG7 1EA",
    sector: "Retail",
    contact_phone: "01556 504542",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with bike hire booking and local SEO",
    why_them: "Independent cycle shop and hire centre serving the 7stanes mountain bike trails in the Castle Douglas area. Has a website. Bike hire and servicing for the significant cycling tourism market would benefit from prominent local SEO targeting '7stanes bike hire' and related searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, cdbikes.co.uk",
  },

  // ============================================================
  // CASTLE DOUGLAS — Accommodation
  // ============================================================
  {
    business_name: "Albion House B&B Castle Douglas",
    url: "https://www.albionhousecastledouglas.co.uk",
    location: "49 Ernspie Road, Castle Douglas, DG7 1LD",
    sector: "Accommodation",
    contact_phone: "01556 502360",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking and local SEO",
    why_them: "Guest house in Castle Douglas with a live website. The castle/food town angle is a strong hook for visitors — a refreshed site with direct booking capability (cutting OTA commission) and better SEO for 'B&B Castle Douglas' searches would improve occupancy.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, albionhousecastledouglas.co.uk",
  },
  {
    business_name: "Kings Arms Hotel Castle Douglas",
    url: "https://www.galloway-golf.co.uk",
    location: "31-33 St Andrew Street, Castle Douglas, DG7 1EL",
    sector: "Accommodation",
    contact_phone: "01556 502626",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking and golf/activity packages",
    why_them: "Town-centre hotel in Castle Douglas with a focus on golf and activity breaks. Has a website. A more prominent direct booking capability combined with targeted SEO for 'golf hotel Castle Douglas' and 'golfing breaks Dumfries and Galloway' would grow bookings.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, galloway-golf.co.uk",
  },
  {
    business_name: "Airds Farm B&B Crossmichael",
    url: "https://www.airds.com",
    location: "Airds Farm, Crossmichael, Castle Douglas, DG7 3BG",
    sector: "Accommodation",
    contact_phone: "01556 670418",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking and rural tourism SEO",
    why_them: "Farmhouse B&B near Crossmichael, Castle Douglas. Has a website. Rural B&Bs are increasingly booked through OTAs at high commission — a properly SEO-optimised direct booking site would cut these costs. Rural and farm stay tourism is growing strongly.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, airds.com",
  },
  {
    business_name: "Gelston Castle Holidays",
    url: "https://www.gelstoncastle.com",
    location: "Gelston, Castle Douglas, DG7 1SW",
    sector: "Accommodation",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking engine and luxury self-catering SEO",
    why_them: "Luxury self-catering cottages at Gelston Castle near Castle Douglas. Has a website. Castle estate self-catering is a premium product — a modernised site with professional photography, a direct booking engine and SEO targeting 'luxury self-catering Galloway' would reduce OTA dependency.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "gelstoncastle.com, castledouglas info search",
  },
  {
    business_name: "Queenshill Country Cottages",
    url: "https://www.queenshill.co.uk",
    location: "Barstobrick, Castle Douglas, DG7 2AT",
    sector: "Accommodation",
    contact_phone: "01557 820227",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.3,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking and rural Scotland SEO",
    why_them: "Rural self-catering cottages in the DG7 area. Has a website. A properly designed direct booking site with strong rural Galloway SEO would reduce reliance on Booking.com and Sykes Cottages and meaningfully improve margins on each booking.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, queenshill.co.uk",
  },

  // ============================================================
  // CASTLE DOUGLAS — Professional Services
  // ============================================================
  {
    business_name: "Gillespie Gifford & Brown Solicitors Castle Douglas",
    url: "https://www.ggblaw.co.uk",
    location: "135 King Street, Castle Douglas, DG7 1NA",
    sector: "Professional Services",
    contact_phone: "01556 503440",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with SEO for legal and property searches",
    why_them: "Established law firm on King Street offering residential conveyancing, wills, family law and rural property. Has a website but a modernised site with targeted SEO for 'solicitor Castle Douglas' and 'conveyancing DG7' would improve self-referral leads.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, ggblaw.co.uk",
  },
  {
    business_name: "Montpelier Chartered Accountants Castle Douglas",
    url: "https://www.montpeliergalloway.co.uk",
    location: "226 King Street, Castle Douglas, DG7 1DS",
    sector: "Professional Services",
    contact_phone: "01556 504064",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with local SEO for accountancy services",
    why_them: "Chartered accountants practice serving small businesses and agricultural clients across the Stewartry. Has a website. Improving their local SEO for 'accountant Castle Douglas' and 'agricultural accountant Dumfries and Galloway' would generate stronger self-referral leads.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, montpeliergalloway.co.uk",
  },

  // ============================================================
  // CASTLE DOUGLAS — Wedding & Events
  // ============================================================
  {
    business_name: "Darling Buds Florist Castle Douglas",
    url: null,
    location: "Castle Douglas, DG7",
    sector: "Wedding & Events",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.6,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Brochure website with wedding portfolio and enquiry form",
    why_them: "Wedding and events florist in Castle Douglas with no dedicated website. In a region with many wedding venues (Barholm, Cally Palace etc.), a florist with no web presence misses the pre-wedding research phase entirely — a portfolio site with gallery and enquiry form is the obvious fix.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "weddingrelated.co.uk, guidesforbrides.co.uk",
  },
  {
    business_name: "Clience Studio Castle Douglas",
    url: "https://www.cliencestudio.co.uk",
    location: "212 King Street, Castle Douglas, DG7 1DS",
    sector: "Wedding & Events",
    contact_phone: "01556 504318",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.3,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Portfolio website refresh with wedding and event photography SEO",
    why_them: "Photography and creative studio on King Street. Has a live website. With a growing wedding and events market in the Stewartry, a refreshed portfolio site with strong SEO for 'wedding photographer Castle Douglas' and 'photographer Kirkcudbright' would drive regular enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, cliencestudio.co.uk",
  },

  // ============================================================
  // CASTLE DOUGLAS — Home Services
  // ============================================================
  {
    business_name: "Hewats Services Castle Douglas",
    url: "https://www.hewats.co.uk",
    location: "63 King Street, Castle Douglas, DG7 1AG",
    sector: "Home Services",
    contact_phone: "01556 502391",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with local SEO for home services",
    why_them: "General services business on King Street in Castle Douglas. Has a website. Improving local search visibility for home service searches in the DG7 area would improve lead quality.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, hewats.co.uk",
  },
  {
    business_name: "Wallets Mart Castle Douglas",
    url: "https://www.walletsmarts.co.uk",
    location: "New Market Street, Castle Douglas, DG7 1HY",
    sector: "Professional Services",
    contact_phone: "01556 502381",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.8,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with auction and valuation SEO",
    why_them: "Livestock and property auction mart in Castle Douglas — a key agricultural services hub for the Stewartry. Has a website. Improving their digital presence for 'cattle market Castle Douglas' and 'agricultural auctioneers Galloway' searches would improve market attendance from a wider farming catchment.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "castledouglas.info, walletsmarts.co.uk",
  },

  // ============================================================
  // DALBEATTIE — Food & Drink
  // ============================================================
  {
    business_name: "Brambles Cafe Dalbeattie",
    url: null,
    location: "Craigendarroch, Dalbeattie, DG5 4QU",
    sector: "Food & Drink",
    contact_phone: "07824 878884",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple brochure website with menu, opening hours and local SEO",
    why_them: "Highly rated cafe in Dalbeattie with no website — completely dependent on word of mouth and TripAdvisor. A simple web presence with menu and opening hours would capture 7stanes cyclists and walkers searching for food stops in the Dalbeattie area.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor Dalbeattie restaurants",
  },
  {
    business_name: "The King's Arms Hotel Dalbeattie",
    url: null,
    location: "High Street, Dalbeattie, DG5 4HA",
    sector: "Food & Drink",
    contact_phone: "01556 610400",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Brochure website with pub menu, accommodation and events",
    why_them: "Town-centre hotel and pub on the High Street. Facebook presence but no website. A simple site with the menu, accommodation options and events listings would significantly improve their visibility to visitors to the Dalbeattie 7stanes area.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, Facebook",
  },
  {
    business_name: "Rose Garden Dalbeattie",
    url: null,
    location: "210 High Street, Dalbeattie, DG5 4DJ",
    sector: "Food & Drink",
    contact_phone: "01556 611555",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brochure website with menu and booking",
    why_them: "Cafe/restaurant on the High Street with no digital presence. Dalbeattie is a 7stanes hub attracting mountain bikers and outdoor visitors year-round — a website with a menu and booking would capture this seasonal search traffic.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor Dalbeattie restaurants",
  },
  {
    business_name: "Sea Horse Chinese Restaurant Dalbeattie",
    url: null,
    location: "15 Mill Street, Dalbeattie, DG5 4HE",
    sector: "Food & Drink",
    contact_phone: "01556 611173",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple website with online ordering",
    why_them: "Chinese restaurant and takeaway in Dalbeattie town centre with no website. A simple site with online ordering would capture a significant share of the local delivery market currently going to Just Eat and Deliveroo.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor Dalbeattie restaurants",
  },
  {
    business_name: "Shezan Indian Takeaway Dalbeattie",
    url: null,
    location: "42 High Street, Dalbeattie, DG5 4AA",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.1,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple website with online ordering and local SEO",
    why_them: "Indian takeaway on Dalbeattie High Street with no website. A simple ordering site would give them a direct channel and reduce reliance on Just Eat commissions.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, 22barend.co.uk",
  },
  {
    business_name: "Jamiesons Sandwich Bar Dalbeattie",
    url: null,
    location: "12A Maxwell Street, Dalbeattie, DG5 4AQ",
    sector: "Food & Drink",
    contact_phone: "01556 611640",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple brochure website with menu and online ordering",
    why_them: "Sandwich bar and deli on Maxwell Street with no web presence. A simple site with a daily menu and optional online ordering would capture the growing pre-order/click-and-collect market among Dalbeattie's workforce.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor Dalbeattie restaurants",
  },
  {
    business_name: "The Granite Kitchen Dalbeattie",
    url: null,
    location: "62a High Street, Dalbeattie, DG5 4AA",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Brochure website with menu and local SEO",
    why_them: "Newly opened cafe on the High Street in Dalbeattie. Facebook presence but no website yet — catching them early with a new site would give them a strong digital start and could build a loyal relationship.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "visitscotland.com, tripadvisor.com",
  },
  {
    business_name: "Treats and Eats Colvend",
    url: null,
    location: "Colvend, Dalbeattie, DG5",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brochure website with menu, opening hours and local SEO",
    why_them: "Country cafe in Colvend near Kippford and Rockcliffe — on a popular coastal route for visitors. No web presence despite being well-reviewed locally. A simple website would capture search traffic from walkers and cyclists on the Solway Coast route.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "22barend.co.uk, coastalkippford.com local recommendation",
  },

  // ============================================================
  // DALBEATTIE — Trades & Construction
  // ============================================================
  {
    business_name: "Active Electrical Dalbeattie",
    url: null,
    location: "6 Broomlands Avenue, Dalbeattie, DG5 4RD",
    sector: "Trades & Construction",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple trades website with local SEO",
    why_them: "Electrical contractor in Dalbeattie with no web presence — entirely reliant on word of mouth. A simple trades website targeting 'electrician Dalbeattie' and 'electrician DG5' searches would generate consistent inbound leads from homeowners and landlords.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "yell.com",
  },
  {
    business_name: "Colin Hunter Builders Dalbeattie",
    url: null,
    location: "4 Wallach Brae, Dalbeattie, DG5 4GY",
    sector: "Trades & Construction",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple trades website with project gallery and local SEO",
    why_them: "Local builder in Dalbeattie with no website. A simple site with a project gallery and Google My Business integration would capture homeowners searching for builders in the DG5 area — the most reliable way to find quality local tradespeople is still Google.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "yell.com",
  },
  {
    business_name: "Iron & Pine Dalbeattie",
    url: null,
    location: "Unit 2 Biggars Mill, Dalbeattie, DG5 4AZ",
    sector: "Trades & Construction",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Portfolio website with bespoke fabrication showcase and SEO",
    why_them: "Specialist agricultural and bespoke fabrication builder in Dalbeattie. No website. A portfolio-style site showcasing bespoke ironwork and structural projects would attract rural estate, farm and private client work from across Dumfries and Galloway.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "yell.com, birdeye.com",
  },
  {
    business_name: "Michael Stewart Plumbing Dalbeattie",
    url: null,
    location: "High Mount, Craignair View, Dalbeattie, DG5 4EQ",
    sector: "Trades & Construction",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple plumbing trades website with emergency callout and local SEO",
    why_them: "Local plumber in Dalbeattie with no website — only word-of-mouth and Referenceline reviews. A simple site with emergency callout info, services list and DG5 SEO would generate consistent leads from homeowners, landlords and estate managers across the Stewartry.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "referenceline.com",
  },

  // ============================================================
  // DALBEATTIE — Beauty & Wellness
  // ============================================================
  {
    business_name: "The Hair & Beauty Gallery Dalbeattie",
    url: null,
    location: "14 High Street, Dalbeattie, DG5 4AA",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brochure website with service menu and online booking",
    why_them: "Hair and beauty salon on Dalbeattie High Street with no web presence. A simple site with online booking would capture the growing number of clients who book salons via Google rather than phone.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "touchdumfries.com, beautynailhairsalons.com",
  },
  {
    business_name: "Trends Hair Design Dalbeattie",
    url: null,
    location: "46 High Street, Dalbeattie, DG5 4AA",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brochure website with service list and Fresha booking integration",
    why_them: "Unisex hair salon on the High Street. Listed on Fresha but no own website. Building a proper branded website with a Fresha booking link embedded would lift their professional profile and reduce dependence on the Fresha marketplace.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "fresha.com",
  },
  {
    business_name: "Relax with Rosy Dalbeattie",
    url: null,
    location: "The Green Room, Millisle, Dalbeattie",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple wellness website with service menu, booking and local SEO",
    why_them: "Beauty and holistic therapist in Dalbeattie offering massage, facials and treatments. No website — relies entirely on word of mouth and referral. A simple, well-written wellness website with booking would improve discoverability for 'massage therapist Dalbeattie' searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "dalbeattiematters.net hair and beauty section",
  },

  // ============================================================
  // DALBEATTIE — Accommodation
  // ============================================================
  {
    business_name: "Coastal Kippford Holiday Park",
    url: "https://www.coastalkippford.com",
    location: "Kippford, Dalbeattie, DG5 4LF",
    sector: "Accommodation",
    contact_phone: "01556 620636",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking engine and coastal SEO",
    why_them: "Popular holiday park by the Solway coast at Kippford. Has a website. A stronger SEO campaign targeting 'caravan park Kippford' and 'seaside holiday Scotland' combined with a slicker direct booking engine would reduce OTA dependency and improve booking margins.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "coastalkippford.com, pitchup.com, visitscotland.com",
  },
  {
    business_name: "Glenearly Caravan Park Dalbeattie",
    url: null,
    location: "Dalbeattie, DG5",
    sector: "Accommodation",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Caravan park website with online booking and touring info",
    why_them: "4-star VisitScotland rated caravan park on the outskirts of Dalbeattie. No own website — relies entirely on VisitScotland and OTAs. A direct booking site would immediately reduce commission costs on every booking and improve peak-season occupancy.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "visitscotland.com accommodation listing",
  },
  {
    business_name: "Bluebell Lodge Kippford",
    url: "https://www.kippfordlodges.com",
    location: "Kippford, Dalbeattie, DG5",
    sector: "Accommodation",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking and SEO for luxury lodge stays",
    why_them: "Luxury self-catering lodge near Kippford with a live website. Improving SEO targeting 'luxury lodge Solway Coast' and 'holiday lodge Kippford' and adding a frictionless direct booking engine would reduce reliance on booking aggregators.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "kippfordlodges.com",
  },

  // ============================================================
  // DALBEATTIE — Retail
  // ============================================================
  {
    business_name: "Idlehour Gifts Dalbeattie",
    url: null,
    location: "17 High Street, Dalbeattie, DG5 4AD",
    sector: "Retail",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "E-commerce website with gift finder and local delivery SEO",
    why_them: "Gift shop on Dalbeattie High Street stocking Yankee Candles, handmade bath products and local gifts. No website. A simple e-commerce site with postal gifting would extend their reach beyond the local market — handmade and local gifts are a strong online seller.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "visitscotland.com, tripadvisor.com",
  },
  {
    business_name: "Flowers For You Dalbeattie",
    url: "https://www.flowersforyoudalbeattie.com",
    location: "102a High Street, Dalbeattie, DG5 4HB",
    sector: "Retail",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online ordering and wedding gallery",
    why_them: "Independent florist on the High Street with a live website. Improving local SEO for 'florist Dalbeattie' and adding a wedding portfolio gallery with an enquiry form would capture both everyday floral orders and the lucrative wedding market.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "yell.com, flowersforyoudalbeattie.com",
  },

  // ============================================================
  // DALBEATTIE — Professional Services
  // ============================================================
  {
    business_name: "Austins Solicitors Dalbeattie",
    url: null,
    location: "52 High Street, Dalbeattie, DG5 4AB",
    sector: "Professional Services",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.8,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Professional services website with SEO for local legal searches",
    why_them: "Established law firm in Dalbeattie with no own website — only a listing on solicitors-barristers.co.uk. A professional site targeting 'solicitor Dalbeattie' and 'conveyancing DG5' searches would generate consistent self-referral leads without relying on directory listings.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "solicitors-barristers.co.uk",
  },

  // ============================================================
  // DALBEATTIE — Tourism & Attractions
  // ============================================================
  {
    business_name: "Drumburn Farm Alpaca Trekking Colvend",
    url: null,
    location: "Drumburn Farm, Colvend, Dalbeattie, DG5 4PY",
    sector: "Tourism & Attractions",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 9,
    score_pay: 6,
    score_fit: 9,
    score_access: 8,
    score_overall: 8.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Experience/activity website with online booking and local tourism SEO",
    why_them: "Alpaca trekking and Valais sheep experience on the Solway Coast near Kippford — a premium tourism product with zero web presence. Alpaca experiences are a viral tourism niche; a website with online bookings and professional photography would drive significant bookings from both local searches and Scotland-wide tourism platforms.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "coastalkippford.com/things-to-do, kippfordlodges.com/activities",
  },

  // ============================================================
  // DALBEATTIE — Wedding & Events
  // ============================================================
  {
    business_name: "Allan Smith Photography Dalbeattie",
    url: "http://www.allansmithphotography.com",
    location: "Dalbeattie, DG5",
    sector: "Wedding & Events",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with modern portfolio and local wedding SEO",
    why_them: "Wedding photographer based in Dalbeattie serving Dumfries and Galloway and South Ayrshire. Has a website but it's older. A refreshed, modern portfolio site with strong SEO for 'wedding photographer Dumfries and Galloway' would generate consistent enquiries from the growing D&G wedding market.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "allansmithphotography.com, guidesforbrides.co.uk",
  },

  // ============================================================
  // DALBEATTIE — Home Services
  // ============================================================
  {
    business_name: "GMC External Cleaning Services Dalbeattie",
    url: null,
    location: "9 Galla Crescent, Dalbeattie, DG5 4JY",
    sector: "Home Services",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.4,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple trades website with before/after gallery and local SEO",
    why_them: "External cleaning business in Dalbeattie — window cleaning, jet washing, gutter clearing. Listed on Yell but no website. A simple site with a quote request form and before/after photos would capture homeowners searching for these services in DG5.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "yell.com",
  },
  {
    business_name: "G.W.C.S Window Cleaning Dalbeattie",
    url: null,
    location: "Dalbeattie, DG5",
    sector: "Home Services",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.2,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Simple trades website with service areas and quote form",
    why_them: "Family window cleaning business with 30+ years experience serving Dalbeattie and across Dumfries and Galloway. Facebook presence but no website. A simple site with a quote request form and service areas map would modernise their lead generation.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "facebook.com/gwcsltd",
  },

  // ============================================================
  // KIRKCUDBRIGHT — Food & Drink
  // ============================================================
  {
    business_name: "The Garret Hotel & Restaurant Kirkcudbright",
    url: "https://www.thegarrethotel.co.uk",
    location: "116 High Street, Kirkcudbright, DG6 4JQ",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking, menu showcase and local SEO",
    why_them: "Eco-friendly art deco hotel and restaurant on the High Street of Scotland's Artists' Town. Has a website. A refresh with better local SEO targeting 'hotel Kirkcudbright' and 'restaurant Kirkcudbright' plus a direct booking engine would reduce OTA dependency for this boutique property.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "thegarrethotel.co.uk, tripadvisor.com, wanderlog.com",
  },
  {
    business_name: "Swally N Scran Kirkcudbright",
    url: null,
    location: "St Cuthberts Place, Kirkcudbright, DG6 4DH",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Brochure website with menu, opening hours and local SEO",
    why_them: "Popular local bar and food venue near the harbour. Only Facebook presence. In a town where food tourism is growing strongly, a website with a menu and venue story would capture search traffic from visitors researching where to eat in Kirkcudbright.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "tripadvisor.com, kirkcudbright.town",
  },
  {
    business_name: "Chen's Kitchen Kirkcudbright",
    url: null,
    location: "73 St Mary Street, Kirkcudbright, DG6 4DU",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple website with online ordering",
    why_them: "Chinese restaurant and takeaway on St Mary Street. No web presence. A simple ordering site would give them a direct channel for the local delivery market.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "tripadvisor.com Kirkcudbright restaurants",
  },
  {
    business_name: "Portobello Restaurant Kirkcudbright",
    url: null,
    location: "11 St Cuthbert Street, Kirkcudbright, DG6 4DJ",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brochure restaurant website with booking and local SEO",
    why_them: "Restaurant on St Cuthbert Street with no web presence. With Kirkcudbright's growing reputation as a food and arts destination, a restaurant without a website is missing significant pre-visit research traffic from tourists.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "tripadvisor.com Kirkcudbright restaurants",
  },
  {
    business_name: "Thai Kitchen Kirkcudbright Golf Club",
    url: null,
    location: "Kirkcudbright Golf Club, Kirkcudbright, DG6 4EZ",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple restaurant website with menu and booking",
    why_them: "Thai kitchen based at Kirkcudbright Golf Club — a unique dining offer in the town. No web presence of its own. An unusual combination that would attract visitors beyond just golfers if discoverable online.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "tripadvisor.com Kirkcudbright restaurants",
  },
  {
    business_name: "Paul Jones Bakery Kirkcudbright",
    url: null,
    location: "Kirkcudbright, DG6",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.3,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple bakery website with menu and online ordering",
    why_them: "Local bakery in Kirkcudbright with no web presence. Artisan bakeries are a strong food tourism draw — a simple site with fresh-baked goods photography and click-and-collect ordering would capture both local and visitor trade.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "tripadvisor.com Kirkcudbright restaurants",
  },

  // ============================================================
  // KIRKCUDBRIGHT — Accommodation
  // ============================================================
  {
    business_name: "The Garret Hotel Kirkcudbright",
    url: "https://www.thegarrethotel.co.uk",
    location: "116 High Street, Kirkcudbright, DG6 4JQ",
    sector: "Accommodation",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking engine and boutique hotel SEO",
    why_them: "Art deco boutique hotel in Kirkcudbright's Artists' Town. Has a website. As an eco-boutique in a growing arts tourism destination, a stronger site with direct booking and SEO for 'boutique hotel Kirkcudbright' would reduce OTA commission spend.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "thegarrethotel.co.uk, tripadvisor.com",
  },
  {
    business_name: "Ross Bay Retreat Kirkcudbright",
    url: "https://www.rossbayretreat.com",
    location: "Kirkcudbright area, DG6",
    sector: "Accommodation",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking and coastal self-catering SEO",
    why_them: "Luxury coastal self-catering cottages near Kirkcudbright. Has a website. Improving local SEO targeting 'luxury self-catering Galloway coast' and 'coastal cottages Kirkcudbright' would bring direct bookings and reduce reliance on Booking.com.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "rossbayretreat.com, visitscotland.com",
  },
  {
    business_name: "Barrhill Woods B&B Kirkcudbright",
    url: null,
    location: "Kirkcudbright, DG6",
    sector: "Accommodation",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brochure B&B website with direct booking and accessibility information",
    why_them: "3-room B&B near Kirkcudbright listed on VisitScotland, dog-friendly, with mobility accessibility. No own website — relies entirely on OTAs. A direct booking site would reduce commission and make accessibility information clearly searchable for guests who need it.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "visitscotland.com accommodation listing",
  },
  {
    business_name: "High Kirkland Holidays Kirkcudbright",
    url: "https://www.highkirkland.co.uk",
    location: "Kirkcudbright, DG6 4QA",
    sector: "Accommodation",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking and luxury rural SEO",
    why_them: "Luxury self-catering holiday properties near Kirkcudbright. Has a website. A stronger SEO campaign and frictionless direct booking would reduce OTA dependency for this premium rural accommodation.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "highkirkland.co.uk, visitscotland.com",
  },

  // ============================================================
  // KIRKCUDBRIGHT — Trades & Construction
  // ============================================================
  {
    business_name: "Derek Ingram Builder & Plasterer Kirkcudbright",
    url: null,
    location: "The Tammock, Main Street, Twynholm, Kirkcudbright, DG6 4NT",
    sector: "Trades & Construction",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple trades website with project gallery and local SEO",
    why_them: "Builder and plasterer based in Twynholm near Kirkcudbright — no website at all. A simple site with services, service area and a project gallery would generate consistent 'builder Kirkcudbright' and 'plasterer DG6' search leads.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "yell.com",
  },
  {
    business_name: "JK & Sons Builders Kirkcudbright",
    url: null,
    location: "15 Princess Street, Kirkcudbright, DG6 4LE",
    sector: "Trades & Construction",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Trades website with services, project gallery and local SEO",
    why_them: "Building company based in Kirkcudbright town with no web presence. A simple site targeting 'builders Kirkcudbright' would capture the steady flow of renovation, extension and new-build enquiries from homeowners across the DG6 area.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "opengovuk.com",
  },
  {
    business_name: "G.W. Davidson Builder Kirkcudbright",
    url: null,
    location: "18 Castledykes Road, Kirkcudbright, DG6 4HQ",
    sector: "Trades & Construction",
    contact_phone: "01557 331673",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple builder website with local SEO",
    why_them: "Established builder in Kirkcudbright listed in local directories but with no website. A simple site would be the most efficient use of a small marketing budget for a one-man or small team builder relying on word of mouth.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "thesocialmediadirectory.com, kirkcudbright search",
  },

  // ============================================================
  // KIRKCUDBRIGHT — Beauty & Wellness
  // ============================================================
  {
    business_name: "The Hub Hair & Beauty Kirkcudbright",
    url: null,
    location: "5 St Cuthberts Place, Kirkcudbright, DG6 4DH",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brochure website with service menu and online booking",
    why_them: "Hair and beauty salon near the harbour with no website — listed on Yell and Fresha only. A branded website with booking integration would improve professional credibility and capture tourists visiting Kirkcudbright who want local beauty services.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "yell.com, 192.com",
  },
  {
    business_name: "Sloans Hairdressing Kirkcudbright",
    url: null,
    location: "Kirkcudbright, DG6",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple hair salon website with booking and local SEO",
    why_them: "Unisex hairdressing salon in Kirkcudbright town. Yell listing only — no website. A simple site with a booking link would modernise their customer acquisition in line with how clients now find local salons.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "yell.com",
  },
  {
    business_name: "The Fitness & Therapy Suite Kirkcudbright",
    url: null,
    location: "Kirkcudbright, DG6",
    sector: "Fitness & Leisure",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Fitness and therapy website with class timetable and booking",
    why_them: "Fitness and therapy facility in Kirkcudbright with no web presence. With growing interest in wellness tourism and active holidays in D&G, a site with class schedules, therapy treatments and online booking would capture both local clients and visitors to the artists' town.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "ukphonebook.com",
  },

  // ============================================================
  // KIRKCUDBRIGHT — Tourism & Attractions
  // ============================================================
  {
    business_name: "Harbour Cottage Gallery Kirkcudbright",
    url: "https://www.harbourcottagegallery.org.uk",
    location: "Castle Bank, Kirkcudbright, DG6",
    sector: "Tourism & Attractions",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with e-commerce for art prints and SEO",
    why_them: "Member-run art gallery at the harbour in Scotland's Artists' Town. Has a website but limited SEO. A refreshed site with online art browsing and purchase capability would extend the gallery's reach to national art collectors beyond walk-in visitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "harbourcottagegallery.org.uk, kirkcudbright.town",
  },
  {
    business_name: "Kirkcudbright Sailing Club",
    url: null,
    location: "Kirkcudbright Harbour, DG6",
    sector: "Tourism & Attractions",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Club website with membership, events and visitor berthing information",
    why_them: "The marina at Kirkcudbright is one of the safest anchorages on the Solway. A sailing club website with visitor berthing information, tide tables and membership details would be a natural information hub for sailing tourism in the area.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "kirkcudbright.town, visitmyharbour.com, packthesuitcases.com",
  },

  // ============================================================
  // KIRKCUDBRIGHT — Professional Services
  // ============================================================
  {
    business_name: "Cavers & Co Solicitors Kirkcudbright",
    url: "https://www.caversandco.com",
    location: "40/42 St Mary Street, Kirkcudbright, DG6 4DN",
    sector: "Professional Services",
    contact_phone: "01557 331217",
    contact_email: "pcavers@caversandco.com",
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with local SEO for rural legal services",
    why_them: "Family-run rural law firm and estate agency in Kirkcudbright serving a large agricultural and residential client base. Has a website. Improving SEO for 'solicitor Kirkcudbright' and 'estate agent DG6' would generate consistent self-referral leads beyond word of mouth.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "caversandco.com, facebook.com/caversandco",
  },

  // ============================================================
  // KIRKCUDBRIGHT — Wedding & Events
  // ============================================================
  {
    business_name: "Lily Knowles Florist Kirkcudbright",
    url: "https://www.lilyknowles.co.uk",
    location: "20 St Cuthbert Street, Kirkcudbright, DG6 4HZ",
    sector: "Wedding & Events",
    contact_phone: "01557 526479",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with wedding gallery and local SEO",
    why_them: "Family florist on St Cuthbert Street. Has a website. Adding a dedicated wedding gallery with real ceremony photos and improving SEO for 'wedding florist Kirkcudbright' and 'florist DG6' would drive consistent enquiries from couples planning weddings across the Stewartry.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "lilyknowles.co.uk, misterwhat.co.uk",
  },
  {
    business_name: "Willow Flowers Kirkcudbright",
    url: "https://www.willowkirkcudbright.co.uk",
    location: "34 St Mary Street, Kirkcudbright, DG6 4DN",
    sector: "Wedding & Events",
    contact_phone: "01557 332456",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with wedding portfolio and floral design SEO",
    why_them: "Florist specialising in wedding and event flowers on St Mary Street. Has a website. A portfolio-led refresh showcasing real D&G weddings with strong SEO for 'wedding flowers Dumfries and Galloway' would drive enquiries from couples across the region.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "willowkirkcudbright.co.uk, zoominfo.com",
  },
  {
    business_name: "Colin Wyper Photography Kirkcudbright",
    url: null,
    location: "Kirkcudbright, DG6 4DJ",
    sector: "Wedding & Events",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Portfolio website with wedding photography SEO",
    why_them: "Photographer in Kirkcudbright with no dedicated website — only a photographycentral.co.uk listing. A proper portfolio site with gallery and SEO for 'wedding photographer Kirkcudbright' would generate consistent enquiries from couples planning weddings in the artists' town and across D&G.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "photographycentral.co.uk",
  },
]

async function run() {
  const { data: existing } = await supabase.from("prospects").select("business_name")
  const existingNames = new Set((existing ?? []).map((r: any) => r.business_name))
  const toInsert = prospects.filter(
    (p) => !existingNames.has(p.business_name) && (p.url || p.contact_phone || p.contact_email)
  )
  console.log(`Inserting ${toInsert.length} new records...`)
  for (const record of toInsert) {
    const { data, error } = await supabase.from("prospects").insert(record).select("id, business_name")
    if (error) console.error(`✗ ${record.business_name}:`, error.message)
    else console.log(`✓ ${data?.[0]?.business_name}`)
  }
  console.log("Done.")
}
run()
