import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const prospects: any[] = [
  // ── RETAIL ──────────────────────────────────────────────────────────────────

  {
    business_name: "Moshulu Dumfries",
    url: "https://www.moshulu.co.uk",
    location: "158 High Street, Dumfries, DG1 2BA",
    sector: "Retail",
    contact_phone: "01387 739841",
    contact_email: null,
    contact_name: null,
    score_need: 3,
    score_pay: 6,
    score_fit: 5,
    score_access: 5,
    score_overall: 4.3,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Local SEO landing page for Dumfries store",
    why_them: "Independent-feeling footwear chain with a physical Dumfries presence. The national site doesn't rank for local Dumfries shoe shop searches — a dedicated store page or local SEO work would drive foot traffic.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk, Yelp",
  },
  {
    business_name: "Carpets & Rugs Direct Dumfries",
    url: null,
    location: "25 Whitesands, Dumfries, DG1 2RR",
    sector: "Retail",
    contact_phone: "01387 254504",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "New website with room visualiser, product ranges and showroom booking",
    why_them: "Flooring retailer on Whitesands with no online presence. Flooring is a high-consideration purchase; buyers research extensively online before visiting. A clean website with product imagery and a showroom booking form would convert local searches directly.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Douglas Anderson Menswear",
    url: null,
    location: "5 Church Crescent, Dumfries, DG1 1DF",
    sector: "Retail",
    contact_phone: "01387 250250",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brand website with lookbook, stock highlight and local SEO",
    why_them: "Long-established independent menswear boutique in Dumfries town centre with no web presence at all. Independent clothing retail without a website is highly vulnerable to national competitor searches; a stylish lookbook site would reclaim local discoverability.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Freckles Bridal Couture",
    url: null,
    location: "13-15 Church Crescent, Dumfries, DG1 1ER",
    sector: "Retail",
    contact_phone: "01387 265202",
    contact_email: null,
    contact_name: null,
    score_need: 9,
    score_pay: 7,
    score_fit: 8,
    score_access: 7,
    score_overall: 8.15,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Bridal boutique website with gallery, designer showcase and appointment booking",
    why_them: "Bridal wear is an extremely high-intent online search category — brides plan months ahead and research heavily before visiting a boutique. Freckles has no web presence, making them almost invisible to couples searching 'bridal shops Dumfries'. A gallery-led site with an appointments system is a natural fit.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Burns Gift Shop Dumfries",
    url: null,
    location: "5 Bank Street, Dumfries, DG1 2NX",
    sector: "Retail",
    contact_phone: "01387 255579",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Gift shop website with product highlights, visitor info and e-commerce option",
    why_them: "Heritage gifts and Burns memorabilia shop in the heart of Dumfries, drawing on a steady stream of Burns-trail tourists. No website means zero capture of visitors researching ahead of a trip. A simple product showcase with tourist context would boost pre-visit and online sales.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk, Yelp",
  },
  {
    business_name: "Cowens Jewellers",
    url: null,
    location: "45 Friars Vennel, Dumfries, DG1 2RQ",
    sector: "Retail",
    contact_phone: "01387 254004",
    contact_email: null,
    contact_name: null,
    score_need: 9,
    score_pay: 7,
    score_fit: 8,
    score_access: 7,
    score_overall: 8.15,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Jewellery boutique website with product gallery, repair services and ring finder",
    why_them: "Independent jeweller on Friars Vennel with no discoverable web presence. Jewellery searches skew high-intent (engagement rings, gifts, repairs) — a well-structured site with product imagery and a repair/consultation enquiry form would capture significant local spend currently going elsewhere.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Gordon W Thomson Jeweller",
    url: null,
    location: "43 Bank Street, Dumfries, DG1 2PA",
    sector: "Retail",
    contact_phone: "01387 255147",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 7,
    score_fit: 8,
    score_access: 7,
    score_overall: 7.8,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Fine jewellery website with collection showcase and bespoke enquiry form",
    why_them: "Established fine jewellery stockist on Bank Street. No web presence means the business loses every customer who Googles 'jewellers Dumfries' before visiting the high street. Even a one-page site with photography would lift local search visibility substantially.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Blooms Florist Dumfries",
    url: null,
    location: "20 Academy Street, Dumfries, DG1 1BY",
    sector: "Retail",
    contact_phone: "01387 256192",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Florist website with occasion-based shop, same-day delivery and online ordering",
    why_them: "Independent florist in Dumfries town centre with no verified web presence. Florists rely heavily on impulse and occasion-driven searches (birthdays, funerals, weddings) — all high-value moments where a website with online ordering would convert immediately.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Cairnyard Antiques",
    url: null,
    location: "Nether Cairnyard, Dumfries, DG2 8JE",
    sector: "Retail",
    contact_phone: "01387 730218",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Antiques dealer website with catalogue, provenance notes and enquiry form",
    why_them: "Rural antiques dealer near Dumfries with no online presence. Antique collectors search nationally and internationally — a catalogue site with item descriptions and an enquiry form would extend reach far beyond walk-in trade.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Patties of Dumfries",
    url: null,
    location: "109 Queensberry Street, Dumfries, DG1 1BH",
    sector: "Retail",
    contact_phone: "01387 252891",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Outdoor gear website with product categories, brand showcase and local adventure guides",
    why_them: "Long-standing independent outdoor gear and sporting goods shop in Dumfries. Stocks walking, camping, fishing and skiing kit for a region with strong outdoor recreation demand. No website means losing customers who research online before buying outdoor kit — a product showcase with brand listings and local activity guides would drive both in-store and online conversions.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Solway Tile & DIY Centre",
    url: null,
    location: "238 Heathhall Industrial Estate, Dumfries, DG1 3PH",
    sector: "Retail",
    contact_phone: "01387 261171",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Tile showroom website with product ranges, room inspiration and trade account enquiry",
    why_them: "Local tile and DIY specialist based in the Heathhall industrial area. Competes directly with national chains (Topps Tiles, B&Q) but with no online presence to differentiate itself. A showroom website with tile inspiration galleries and a trade enquiry form would capture the significant builder and homeowner search traffic that currently lands on competitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk, Yelp",
  },

  // ── TRADES & CONSTRUCTION ─────────────────────────────────────────────────

  {
    business_name: "George Adamson Builders",
    url: "https://www.georgeadamsonbuilders.co.uk",
    location: "123 Irish Street, Dumfries, DG1 2PE",
    sector: "Trades & Construction",
    contact_phone: "01387 265651",
    contact_email: "georgeadamsonbuilders@gmail.com",
    contact_name: null,
    score_need: 4,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.55,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with project portfolio, testimonials and online quote request",
    why_them: "Federation of Master Builders member offering extensions, new builds, conversions and driveways across DG1. Has a live website but it's minimal — no project gallery, no case studies, and weak local SEO for searches like 'builders Dumfries extensions'. A stronger site with portfolio photography would significantly improve enquiry quality.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk, georgeadamsonbuilders.co.uk",
  },
  {
    business_name: "Cornerstone Builders Dumfries",
    url: null,
    location: "4 Parkhead Drive, Dumfries, DG1 3BY",
    sector: "Trades & Construction",
    contact_phone: "01387 267254",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Builder website with services list, project photos and free quote form",
    why_them: "Established local builder in DG1 with no web presence. Builders without websites lose enquiries to better-ranked competitors every day — a clean service-led site with project photos and a quote request form would immediately improve their lead flow.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Maxwelltown Roofing Services",
    url: null,
    location: "Unit 3 Irongray Road, Dumfries, DG2 0JE",
    sector: "Trades & Construction",
    contact_phone: "01387 405243",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Roofing contractor website with services, emergency contact and project gallery",
    why_them: "Local roofing firm based in Dumfries with no online presence. Roofing enquiries are often urgent and searchers click the first credible result they find — without a website, Maxwelltown is invisible to this high-intent traffic.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "DGRC Roofing Contractors",
    url: null,
    location: "Fairlands, Heathhall Terrace, Dumfries, DG1 1TU",
    sector: "Trades & Construction",
    contact_phone: "01387 279381",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Roofing website with service breakdown, free survey offer and emergency call CTA",
    why_them: "DG1-based roofing contractor with no website. Without an online presence they rely entirely on word-of-mouth while competitors rank for 'roofers Dumfries' searches. A simple but well-structured site would open a new channel of enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Robin McCorkindale Electrician",
    url: null,
    location: "5 Barnton Drive, Dumfries, DG1 4HZ",
    sector: "Trades & Construction",
    contact_phone: "01387 268458",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Sole-trader electrician website with services, areas covered and contact form",
    why_them: "Sole-trader electrician operating in DG1 with no web presence. Homeowners searching for electricians expect to see a website before calling — a single-page site with services, coverage area and a call-to-action would generate direct enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Murray Electricians",
    url: null,
    location: "The Workshop, Dumfries, DG2 9RW",
    sector: "Trades & Construction",
    contact_phone: "01387 268672",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Electrician website with domestic and commercial services, areas covered and quote form",
    why_them: "Local electrical contractor near Dumfries with no online footprint. With no website they're completely absent from search results for 'electricians Dumfries'. A straightforward site listing services and coverage would immediately address this gap.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "JB McCormick Electrical Contractor",
    url: null,
    location: "27a Galloway Street, Dumfries, DG2 7TN",
    sector: "Trades & Construction",
    contact_phone: "01387 268837",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Electrical contractor website with certification info, services list and contact CTA",
    why_them: "Established electrical contractor in DG2 Dumfries with no web presence. Electricians who display their NICEIC/NAPIT registration and services clearly on a website build trust quickly — without one, they lose to better-presented competitors in local search.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Nithsdale Plumbing & Heating",
    url: null,
    location: "2 Catherinefield Industrial Estate, Dumfries, DG1 3PQ",
    sector: "Trades & Construction",
    contact_phone: "01387 267120",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Plumbing & heating website with boiler services, emergency callout and quote request",
    why_them: "Commercial-sized plumbing and heating firm based on Dumfries industrial estate with no online presence. Their scale — multiple staff, trade premises — suggests capacity for larger jobs that require online discovery. A professional website would capture both domestic and commercial enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Atack Plumbing & Heating",
    url: null,
    location: "Unit 5, St Mary's Industrial Estate, Dumfries, DG1 1NA",
    sector: "Trades & Construction",
    contact_phone: "01387 250444",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Plumber website with boiler installations, heating services and emergency contact",
    why_them: "Plumbing and heating contractor operating from a trade premises in Dumfries with no website. Plumbers who appear in Google searches with a credible site consistently win enquiries over those who don't — a service-led site with an emergency contact CTA would deliver immediate ROI.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Johnstone & Clark Heating",
    url: null,
    location: "St Mary's Industrial Estate, Dumfries, DG1 1NE",
    sector: "Trades & Construction",
    contact_phone: "01387 267211",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Heating engineer website with boiler brands, service plans and online booking",
    why_them: "Heating specialist based at a Dumfries industrial estate — likely Gas Safe registered, servicing and installing boilers. No web presence means every homeowner searching 'boiler service Dumfries' or 'heating engineer DG1' finds competitors instead. A clean site with service plans and online booking would change that.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Hiddleston Joiners",
    url: null,
    location: "The Old School, Dumfries, DG2 9RY",
    sector: "Trades & Construction",
    contact_phone: "01387 720555",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Joinery website with bespoke woodwork gallery, services and quote request form",
    why_them: "Established joinery firm near Dumfries operating from a converted school building — scale suggests a proper business with multiple staff. No website means they're invisible online. A gallery-led joinery site showing bespoke work would build trust and generate enquiries from homeowners and contractors alike.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Thomson & Jardine Joiners",
    url: null,
    location: "Lanefoot, Dumfries, DG2 7SL",
    sector: "Trades & Construction",
    contact_phone: "01387 265032",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Joinery website with services, project photos and contact form",
    why_them: "Partnership joinery business based in DG2 Dumfries with no online presence. Joiners who show finished project photography on a website convert enquiries much more effectively — a modest portfolio site would immediately differentiate them from word-of-mouth-only competitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Dovetails Building & Joinery",
    url: null,
    location: "7E Catherinefield Industrial Estate, Dumfries, DG1 3PQ",
    sector: "Trades & Construction",
    contact_phone: "01387 731263",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Building and joinery website with project gallery, services and trade enquiry form",
    why_them: "Combined building and joinery firm on Catherinefield Industrial Estate — trade premises suggests a company with real capacity. No web presence at all. A dual-service website covering both building and joinery would rank well for multiple search terms across DG1.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "DW Construction & Joinery",
    url: null,
    location: "Unit 215 Heathhall Industrial Estate, Dumfries, DG1 3PH",
    sector: "Trades & Construction",
    contact_phone: "01387 266973",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Construction and joinery website with project portfolio and online quote form",
    why_them: "Construction and joinery specialist operating from Heathhall Industrial Estate with no online presence. The industrial premises suggest a company capable of larger projects — a well-structured website with a project gallery would attract both domestic and commercial clients currently finding competitors online.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "McKie Painters & Decorators",
    url: null,
    location: "23 St Annes Road, Dumfries, DG2 9HZ",
    sector: "Trades & Construction",
    contact_phone: "01387 266693",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Decorator website with colour inspiration gallery, services and free quote CTA",
    why_them: "Local decorating firm in DG2 with no web presence. Painting and decorating is a high-frequency local search — homeowners look online every spring and autumn. A clean site with before/after photos and a free quote form would capture this steady demand.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "McLean Painters and Decorators",
    url: null,
    location: "3 Robison Drive, Dumfries, DG2 7RR",
    sector: "Trades & Construction",
    contact_phone: "01387 256726",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Decorator website with project photos, services and online enquiry form",
    why_them: "Established painting and decorating firm in DG2 Dumfries with no online presence. Without a website they're entirely dependent on word-of-mouth, missing every local search for decorators. A simple gallery-led site would immediately improve discoverability.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Keith Logue & Sons Plasterers",
    url: null,
    location: "12 Grieve Walk, Dumfries, DG1 3SY",
    sector: "Trades & Construction",
    contact_phone: "01387 253183",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Plasterer website with service types, coverage area and contact form",
    why_them: "Multi-generational plastering firm in DG1 Dumfries with no web presence. Plasterers are frequently searched alongside builders, decorators and joiners during renovations — a website listing skim plasting, coving, rendering etc. would capture this referral traffic.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Solway Landscapes",
    url: null,
    location: "16 Millview, Dumfries, DG1 4UL",
    sector: "Trades & Construction",
    contact_phone: "01387 254923",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Landscaping website with project gallery, services and seasonal offer CTA",
    why_them: "Landscape gardening company in DG1 with no online presence. Garden and landscaping searches peak in spring and summer — a portfolio site with before/after photos of completed gardens would capture high-intent local enquiries during the peak buying window.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "Willow Cottage Landscapes & Gardens",
    url: null,
    location: "Glendale, Dumfries, DG1 4EJ",
    sector: "Trades & Construction",
    contact_phone: "07730 606793",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Landscape garden design website with portfolio, plant consultations and quote form",
    why_them: "Garden landscaping and design service in DG1 Dumfries with no web presence. The evocative name suggests a garden design focus rather than basic maintenance — a well-styled portfolio website would attract the higher-value design and build projects that justify stronger fees.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
  {
    business_name: "DJH Tiling",
    url: null,
    location: "5 Yarrow Place, Dumfries, DG2 9HF",
    sector: "Trades & Construction",
    contact_phone: "01387 250119",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Tiler website with tile fitting services, bathroom/kitchen gallery and contact form",
    why_them: "Local tiler in DG2 Dumfries with no web presence. Tilers are searched regularly alongside bathroom fitters, plumbers and kitchen fitters — a photo gallery of completed projects with a clear contact CTA would convert local bathroom and kitchen refurbishment searches into enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog.co.uk",
  },
]

async function run() {
  const { data: existing } = await supabase.from("prospects").select("business_name")
  const existingNames = new Set((existing ?? []).map((r: any) => r.business_name))

  const toInsert = prospects.filter(
    (p) => !existingNames.has(p.business_name) && (p.url || p.contact_phone || p.contact_email)
  )

  console.log(`Inserting ${toInsert.length} new records...`)

  for (const record of toInsert) {
    const { data, error } = await supabase
      .from("prospects")
      .insert(record)
      .select("id, business_name")

    if (error) console.error(`✗ ${record.business_name}:`, error.message)
    else console.log(`✓ ${data?.[0]?.business_name}`)
  }
}

run()
