import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const prospects = [
  // ─── LOCKERBIE – Trades & Construction ───────────────────────────────────────
  {
    business_name: "L Murray Builder Ltd",
    url: null,
    location: "Savannah, Main Road, Ecclefechan, Lockerbie, DG11 3BT",
    sector: "Trades & Construction",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Professional website with project portfolio and enquiry form",
    why_them: "Local builder registered at Companies House in Ecclefechan with no visible web or social presence. Entirely reliant on word of mouth — a basic portfolio site would give them credibility and capture DG11 search traffic.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Yell, Companies House",
  },
  {
    business_name: "Bell Electrical Group Ltd",
    url: null,
    location: "15 Mains Street, Lockerbie, DG11 2DG",
    sector: "Trades & Construction",
    contact_phone: "01576 202200",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 6,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Professional website with NICEIC credentials, services list and contact form",
    why_them: "Established electricians based in Lockerbie town centre with a listed phone number but no website. Commercial and domestic electrical contractors in DG11 are under-digitised — a professional site would drive direct enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Yell",
  },
  {
    business_name: "RJW Electrical Services Ltd",
    url: null,
    location: "Lochmaben, Lockerbie, DG11 1GE",
    sector: "Trades & Construction",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Website with multi-trade services listing and Which? Trusted Traders badge",
    why_them: "Family-run Lochmaben multi-trader (electrical, roofing, joinery, plumbing) listed on Which? Trusted Traders since 2012. No standalone website — a site would reinforce their verified status and capture local search traffic across all their service lines.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Which? Trusted Traders, 192.com",
  },
  {
    business_name: "John Glendinning Roofing Ltd",
    url: null,
    location: "12 Greenpark Lane, Lockerbie, DG11 2UA",
    sector: "Trades & Construction",
    contact_phone: "01576 205100",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 6,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Roofing business website with project gallery, testimonials and free quote form",
    why_them: "Established roofing contractor covering Dumfries & Galloway — listed on Yell with a phone number but no website. Roofing is a high-value trade category where local organic search (\"roofer Lockerbie\") converts well with even a basic site.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Yell",
  },
  {
    business_name: "GLS Fencing",
    url: null,
    location: "Lockerbie, DG11",
    sector: "Trades & Construction",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 5,
    score_overall: 5.8,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Website with agricultural, domestic and security fencing portfolio",
    why_them: "Lockerbie-based fencing contractor covering agricultural, domestic, forestry and security work — also has a retail arm. Yell-listed but no website. An online shop-window with project photos would help them compete with national fencing directories.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Yell",
  },
  // ─── LOCKERBIE – Tourism & Attractions ───────────────────────────────────────
  {
    business_name: "Dryfesdale Lodge Visitor Centre",
    url: "https://dryfesdalelodge.org.uk",
    location: "Dryfesdale Lodge, Lockerbie, DG11 2SF",
    sector: "Tourism & Attractions",
    contact_phone: "01576 204553",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.5,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with improved visitor information and SEO",
    why_them: "Community trust managing the Lockerbie Air Disaster memorial visitor centre and local heritage exhibitions. Has a website but it is dated and lacks modern CMS, accessibility compliance or local SEO. High emotional value to visitors makes it a meaningful project.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "VisitScotland, dryfesdalelodge.org.uk",
  },
  {
    business_name: "Eskrigg Nature Reserve",
    url: null,
    location: "Eskrigg Nature Reserve, Lockerbie, DG11",
    sector: "Tourism & Attractions",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 3,
    score_fit: 5,
    score_access: 5,
    score_overall: 5.3,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple informational website with seasonal programme, map and visitor info",
    why_them: "Wildlife reserve near Lockerbie offering conservation events and red squirrel spotting — mentioned in VisitScotland guides as a key local attraction but has no dedicated website. An informational site would drive visitors from Scotland.org and VisitScotland referral traffic.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "scotland.org.uk, VisitScotland",
  },
  {
    business_name: "Lochmaben Golf Club",
    url: "https://lochmabengolfclub.com",
    location: "Castlehillgate, Lochmaben, Lockerbie, DG11 1NT",
    sector: "Tourism & Attractions",
    contact_phone: "01387 810552",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.8,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website modernisation with online membership and visitor booking",
    why_them: "18-hole parkland course in Lochmaben with existing website that is functional but lacks online visitor tee booking, modern mobile design and local SEO. Golf tourism in D&G is growing — a refreshed site with online booking would drive green fee revenue.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, lochmabengolfclub.com",
  },
  // ─── LOCKERBIE – Accommodation ────────────────────────────────────────────────
  {
    business_name: "Hoddom Castle Caravan Park",
    url: "https://www.hoddomcastle.co.uk",
    location: "Hoddom, Ecclefechan, Lockerbie, DG11 1AS",
    sector: "Accommodation",
    contact_phone: "01576 300251",
    contact_email: "enquiries@hoddomcastle.co.uk",
    contact_name: null,
    score_need: 4,
    score_pay: 6,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.5,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO audit and Google Ads targeting touring & glamping searches",
    why_them: "5-star VisitScotland-rated caravan and glamping park in the grounds of a 16th-century castle near Ecclefechan. Has a live website but ranks poorly for competitive touring park searches. Strong seasonal offer — PPC and local SEO work would improve booking rates.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "hoddomcastle.co.uk, VisitScotland, Pitchup",
  },
  {
    business_name: "Bishopcleugh Guest House",
    url: "https://www.bishopcleugh.co.uk",
    location: "Bishopcleugh, Boreland Road, Lockerbie, DG11 2RH",
    sector: "Accommodation",
    contact_phone: "01576 203652",
    contact_email: "christine.sloan@bishopcleugh.co.uk",
    contact_name: "Christine Sloan",
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.7,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with improved booking flow and local SEO",
    why_them: "Family-run restored farmhouse B&B with cottages and lodges near Lockerbie, catering for walkers, cyclists and business travellers. Has a live website but it is dated and lacks online booking integration — adding a booking widget and refreshing local SEO would lift direct bookings.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "bishopcleugh.co.uk",
  },
  {
    business_name: "Applegarth House & Cottages",
    url: "https://applegarthhouse.co.uk",
    location: "Applegarthtown, Lockerbie, DG11",
    sector: "Accommodation",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 5.5,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website modernisation with direct booking and dog-friendly SEO targeting",
    why_them: "Dog-friendly self-catering cottages in the heart of the Dumfriesshire countryside. Has a website but relies on third-party OTAs — a site rebuild with direct booking capability and targeted SEO for dog-friendly DG11 accommodation searches would reduce commission costs.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "applegarthhouse.co.uk, dumfries-and-galloway.co.uk",
  },
  // ─── LOCKERBIE – Food & Drink ─────────────────────────────────────────────────
  {
    business_name: "Just Be Bistro Lockerbie",
    url: null,
    location: "53 High Street, Lockerbie, DG11 2JH",
    sector: "Food & Drink",
    contact_phone: "01576 205715",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.4,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Simple website with menu, opening hours and booking",
    why_them: "Highly rated Lockerbie café-bistro (Scottish, vegetarian and vegan friendly) with strong TripAdvisor reviews but no website. Instagram and Facebook active. A simple site with online table booking would capture the growing local dining-search audience.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor",
  },
  {
    business_name: "Royal Bar Lockerbie",
    url: null,
    location: "6 Station Road, Lockerbie, DG11 2HA",
    sector: "Food & Drink",
    contact_phone: "01576 202374",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "One-page website with menu, hours, events and directions",
    why_them: "Popular Lockerbie pub near the train station with dog-friendly policy, free Wi-Fi and car parking — well reviewed on TripAdvisor and Facebook but entirely without a website. A simple one-pager would improve discoverability for rail travellers and visitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, Firmania, Facebook",
  },
  {
    business_name: "The 'Fechan Diner",
    url: null,
    location: "Ecclefechan, Lockerbie, DG11 3JD",
    sector: "Food & Drink",
    contact_phone: "01576 300500",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple website with menu and directions for M74 passing trade",
    why_them: "American-style diner in Ecclefechan positioned to capture M74 motorway passing trade — no website or social media presence found. A basic site with menu and directions would significantly improve its visibility to motorists and locals alike.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor",
  },
  {
    business_name: "The Station Pub Kirkpatrick Fleming",
    url: "https://www.thestationkpf.co.uk",
    location: "The Station, Kirkpatrick Fleming, Lockerbie, DG11 3AU",
    sector: "Food & Drink",
    contact_phone: "01461 800410",
    contact_email: null,
    contact_name: "Abi",
    score_need: 4,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.3,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with food photography and events calendar",
    why_them: "Village pub and restaurant in Kirkpatrick Fleming serving food with takeaway option and Sunday specials. Has a live website that is basic — no online booking, limited food photography and dated design. A visual refresh would lift conversions for this M74-adjacent venue.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "thestationkpf.co.uk",
  },
  {
    business_name: "Marchbank Bakers Lockerbie",
    url: null,
    location: "85a High Street, Lockerbie, DG11 2",
    sector: "Food & Drink",
    contact_phone: "01576 501051",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple website with produce showcase, opening hours and order ahead",
    why_them: "Independent baker on Lockerbie High Street with no web presence — entirely reliant on footfall. A simple site with product photography, opening hours and contact details would help capture early morning and lunchtime search traffic.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor",
  },
  // ─── LOCKERBIE – Retail ───────────────────────────────────────────────────────
  {
    business_name: "The Flower Pot Gift Shop Lockerbie",
    url: "https://www.flowerpotgiftshop.co.uk",
    location: "59 High Street, Lockerbie, DG11 2JH",
    sector: "Retail",
    contact_phone: "01576 202636",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.7,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "E-commerce addition and local SEO refresh",
    why_them: "Family-run gift and flower shop established since 1984 in Lockerbie — sisters run the business. Has a live website but it lacks e-commerce and online order capability. Adding a simple online shop for gifts and flower delivery would open a new revenue channel.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "flowerpotgiftshop.co.uk",
  },
  {
    business_name: "Allthingsrosie Lockerbie",
    url: null,
    location: "9 Caledonian Place, Lockerbie, DG11 2EU",
    sector: "Retail",
    contact_phone: "07456 202623",
    contact_email: null,
    contact_name: "Kaye",
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.4,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "E-commerce website for floral arrangements and home accessories",
    why_them: "Boutique Lockerbie florist and home accessories shop — owner Kaye consistently praised for unique product range not found on the high street. Active on social media but no website. An online shop with local delivery would extend reach beyond the DG11 footfall area.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Cylex Local Search",
  },
  {
    business_name: "Fleur de Lys Lockerbie",
    url: null,
    location: "62 High Street, Lockerbie, DG11 2AA",
    sector: "Retail",
    contact_phone: "01576 204555",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.1,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Florist website with seasonal arrangements gallery and ordering",
    why_them: "Independent florist on Lockerbie High Street — phone-listed but no website or social media found. Floristry is a high-visual category where a gallery website with online ordering would directly generate wedding and gift enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Cylex Local Search",
  },
  // ─── LOCKERBIE – Home Services ────────────────────────────────────────────────
  {
    business_name: "All Clear Pest Control Ltd",
    url: null,
    location: "Lockerbie, DG11 1DE",
    sector: "Home Services",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.4,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Professional website with emergency call-out, service areas and pest identification guide",
    why_them: "Pest control business operating in the Lockerbie DG11 area with directory listings but no website. Pest control is a high-intent search category — customers search urgently and click the first credible result. A professional site with emergency contact and a blog would dominate local DG11 searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "PestControlCentral",
  },
  {
    business_name: "Mill Loch Cleaning Service",
    url: null,
    location: "Lochmaben, Lockerbie, DG11",
    sector: "Home Services",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 5,
    score_overall: 5.8,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Simple website with service list, pricing guide and online booking",
    why_them: "Domestic cleaning service based in Lochmaben — Facebook presence only. Cleaning is a recurring-revenue service where a simple website with an enquiry form and optional online booking would convert local search traffic into steady clients.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Facebook",
  },
  // ─── LOCKERBIE – Beauty & Wellness ───────────────────────────────────────────
  {
    business_name: "Curvaceous Beauty Boutique",
    url: null,
    location: "7a High Street, Lochmaben, Lockerbie, DG11 1NG",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.3,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Beauty salon website with online booking via Fresha or custom system",
    why_them: "Nail and beauty boutique on Lochmaben High Street offering gel nails, manicures, pedicures, acrylics and nail art — Fresha-listed but no standalone website. A professional site with online booking would reduce reliance on Fresha commission and build a direct client base.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Fresha",
  },
  {
    business_name: "Alice's Salon Ecclefechan",
    url: null,
    location: "Globe House, High Street, Ecclefechan, Lockerbie, DG11 3DF",
    sector: "Beauty & Wellness",
    contact_phone: "01576 300726",
    contact_email: null,
    contact_name: "Alice",
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.1,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Hairdresser website with service menu and online booking",
    why_them: "Hairdressers on Ecclefechan High Street — phone-listed and directory-referenced but no website or visible social media. A basic booking site would capture searches from the M74 commuter belt and Ecclefechan village population.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "MisterWhat, Thomson Local",
  },
  {
    business_name: "Hair by Joy Lockerbie",
    url: null,
    location: "Caledonian Place, Lockerbie, DG11",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: "Joy",
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Hairdresser website with online booking",
    why_them: "Hairdressing salon based in Caledonian Place, Lockerbie — Fresha-listed but no standalone website. A simple booking site with a service menu would help capture local search traffic and reduce platform dependency.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Fresha",
  },
  {
    business_name: "Dots Beauty Spot Lockerbie",
    url: null,
    location: "The Showroom, Caledonian Place, Lockerbie, DG11 2EU",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.4,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Beauty salon website with treatment menu and online booking",
    why_them: "Beauty spot in Lockerbie's Caledonian Place — Fresha-listed with no standalone website. A professional brand site with an online booking calendar would move customers away from Fresha commissions and build direct loyalty.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Fresha",
  },
  // ─── LOCKERBIE – Automotive ───────────────────────────────────────────────────
  {
    business_name: "Tommy's Garage Ltd",
    url: null,
    location: "Unit 2, Broadmedow Industrial Estate, Ecclefechan, Lockerbie, DG11 3LG",
    sector: "Automotive",
    contact_phone: "01576 300412",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Garage website with MOT booking, service schedule and contact",
    why_them: "MOT test centre at Ecclefechan's industrial estate — directory-listed but no website. MOT and servicing are high-search-volume terms in the DG11 area. A simple site with an online MOT booking form would capture motorists coming off the M74.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "MOT.tools, 192.com",
  },
  {
    business_name: "Railway Garage Lochmaben",
    url: null,
    location: "28 Barras, Lochmaben, Lockerbie, DG11 1QD",
    sector: "Automotive",
    contact_phone: "01387 811115",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple garage website with services and contact",
    why_them: "Highly reviewed garage in Lochmaben with a reputation for going above and beyond — directory-listed but no web presence. Word-of-mouth dependent. A basic site would help them appear in searches from Lochmaben residents and the wider DG11 area.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "auto-lock.co.uk, Yell",
  },
  // ─── LOCKERBIE – Healthcare ───────────────────────────────────────────────────
  {
    business_name: "Lockerbie Dental Care Centre",
    url: null,
    location: "134 High Street, Lockerbie, DG11 2BX",
    sector: "Healthcare",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Professional dental practice website with NHS/private info and online appointment request",
    why_them: "Second dental practice on Lockerbie High Street (distinct from Lockerbie Dental at 80 High St). No website found despite being listed in NHS directory. Patients increasingly research dental practices online — a professional site with a patient registration form would drive new NHS and private registrations.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "NHS Inform, Defacto Dentists",
  },
  // ─── LOCKERBIE – Childcare & Education ───────────────────────────────────────
  {
    business_name: "Sparklers Private Nursery Lockerbie",
    url: null,
    location: "Lockerbie, DG11",
    sector: "Childcare & Education",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.1,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Nursery website with registration form, daily schedule and team introduction",
    why_them: "Private nursery in Lockerbie registered with Dumfries & Galloway Council — council directory listing only. Parents now heavily research childcare online before registering. A warm, professional website with a registration enquiry form would directly increase enrollments.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Dumfries & Galloway Council ELC Directory",
  },
  // ─── LOCKERBIE – Fitness & Leisure ───────────────────────────────────────────
  {
    business_name: "Regain Fitness Lockerbie",
    url: "https://www.regainfitness.co.uk",
    location: "Caledonian Place, Lockerbie, DG11 2EX",
    sector: "Fitness & Leisure",
    contact_phone: null,
    contact_email: "info@regainfitness.co.uk",
    contact_name: null,
    score_need: 4,
    score_pay: 6,
    score_fit: 7,
    score_access: 8,
    score_overall: 5.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website conversion optimisation and local SEO for both Lockerbie and Annan locations",
    why_them: "24/7 gym with locations in Lockerbie and Annan (opened Annan 2025) — has a live website and active social but limited SEO. Dual-location membership makes it ideal for a combined digital campaign targeting fitness searches across DG11 and DG12.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "regainfitness.co.uk",
  },
  // ─── LOCKERBIE – Wedding & Events ────────────────────────────────────────────
  {
    business_name: "Springkell Exclusive Hotel & Venue",
    url: "https://www.springkell.com",
    location: "Eaglesfield, Lockerbie, DG11 3AL",
    sector: "Wedding & Events",
    contact_phone: "01461 600553",
    contact_email: null,
    contact_name: null,
    score_need: 3,
    score_pay: 9,
    score_fit: 8,
    score_access: 8,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Wedding SEO campaign and paid social for exclusive-use venue bookings",
    why_them: "Historic Palladian Mansion (1734) in Eaglesfield, exclusive-use wedding and events venue with 21 en-suite rooms and 3 self-catering cottages. Has a live website and strong presence but competes nationally. A targeted SEO and Pinterest/Instagram campaign for Gretna Green alternative searches could significantly grow bookings.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "springkell.com, Celtic Castles, Guides for Brides",
  },
  {
    business_name: "The Mill Forge Hotel",
    url: "https://www.gretnagreenforge.co.uk",
    location: "Kirkpatrick Fleming, Lockerbie, DG11 3BQ",
    sector: "Wedding & Events",
    contact_phone: "01461 800344",
    contact_email: "info@themill.co.uk",
    contact_name: null,
    score_need: 3,
    score_pay: 9,
    score_fit: 8,
    score_access: 8,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "PPC / Google Ads campaign for Gretna Green wedding venue searches",
    why_them: "Grade B-listed wedding venue 2 miles from Gretna Green with 33 en-suite bedrooms and multiple function spaces. Well-established with multiple websites but high competition in Gretna wedding space. A targeted PPC campaign for international couples searching \"Gretna Green wedding venue\" would generate direct bookings.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "gretnagreenforge.co.uk, Bridebook",
  },
  {
    business_name: "Kilt Hire Glendinning Annan",
    url: "https://www.wglendinning.co.uk",
    location: "109 High Street, Annan, DG12",
    sector: "Wedding & Events",
    contact_phone: "01461 202763",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.8,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online kilt hire enquiry form and wedding package showcase",
    why_them: "Traditional kilt maker and hire service on Annan High Street — website is live but dated. Wedding kilt hire is a high-value category in this Gretna-adjacent area. A refreshed site with an online enquiry form would capture couples planning nearby Gretna and DG12 weddings.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "annan.org.uk/weddings",
  },

  // ─── ANNAN – Trades & Construction ───────────────────────────────────────────
  {
    business_name: "Solway Plumbers Eastriggs",
    url: null,
    location: "Almond Bank, Eastriggs, Annan, DG12 6LB",
    sector: "Trades & Construction",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.3,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Plumber website with emergency call-out, services list and quote form",
    why_them: "Plumbing service based in Eastriggs, Annan — directory-listed but no website or social media presence. Plumbing is a high-intent local search category. A professional site with a 24/7 emergency contact button would capture urgent DG12 call-outs that currently go to better-digitised competitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Gazette Live Directory",
  },
  {
    business_name: "W J Grieve Garage & Car Sales",
    url: null,
    location: "Annan Road, Eastriggs, Annan, DG12 6PB",
    sector: "Trades & Construction",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Garage and car sales website with stock listing and MOT booking",
    why_them: "MOT centre and used car dealer based in Eastriggs, Annan — directory-listed only. MOT booking and used car searches are two strong organic SEO opportunities — a simple combined site would capture both audiences in the DG12 area.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "MOTRemind.me, CheckMOT",
  },
  // ─── ANNAN – Tourism & Attractions ───────────────────────────────────────────
  {
    business_name: "Galabank Caravan and Camping Site",
    url: null,
    location: "North Street, Annan, DG12 5DQ",
    sector: "Tourism & Attractions",
    contact_phone: "01461 203539",
    contact_email: null,
    contact_name: "John Ramage",
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple website with pitches, availability and booking",
    why_them: "Council-managed caravan and camping site in Annan overlooking the River Annan — 30 pitches with electric hook-ups. No website despite being the only campsite listed for Annan on the town's official directory. A simple site would capture search traffic from touring motorhomers heading to the Solway Coast.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "annan.org.uk/accommodation",
  },
  // ─── ANNAN – Accommodation ────────────────────────────────────────────────────
  {
    business_name: "Warmanbie Hotel & Restaurant",
    url: "https://www.warmanbie.co.uk",
    location: "Annan, DG12 5LL",
    sector: "Accommodation",
    contact_phone: "01461 204015",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with improved booking integration and local SEO",
    why_them: "Country house hotel and restaurant near Annan set in private grounds on the River Annan. Has a website but it is dated and lacks an integrated booking system. Competes in a strong Gretna-Green-adjacent market where couples look for quieter alternatives — local SEO work would lift their profile.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "annan.org.uk, warmanbie.co.uk",
  },
  // ─── ANNAN – Food & Drink ─────────────────────────────────────────────────────
  {
    business_name: "Cafe Royal Annan",
    url: "https://www.thecaferoyal.co.uk",
    location: "95 High Street, Annan, DG12 6DJ",
    sector: "Food & Drink",
    contact_phone: "01461 202865",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.8,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online ordering and home delivery promotion",
    why_them: "Award-winning family-run fish and chip restaurant with home delivery in Annan — has a live website but it is dated. The home delivery offer is under-promoted digitally. A refreshed site with prominent online ordering and local SEO would capture DG12 takeaway searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "annan.org.uk, thecaferoyal.co.uk",
  },
  {
    business_name: "The Shed Annan",
    url: "https://www.theshed.info",
    location: "7 Lady Street, Annan, DG12 5DA",
    sector: "Food & Drink",
    contact_phone: "01461 201116",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.7,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with menu showcase and online booking",
    why_them: "Independent eatery on Lady Street, Annan — has a website but it appears basic. A refresh with a visual menu, table booking and links to social reviews would lift online conversion for this town-centre restaurant.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "annan.org.uk, theshed.info",
  },
  {
    business_name: "Our Place Annan",
    url: "https://ourplaceannan.co.uk",
    location: "49-55 High Street, Annan, DG12 6AD",
    sector: "Food & Drink",
    contact_phone: "01461 380390",
    contact_email: null,
    contact_name: null,
    score_need: 4,
    score_pay: 6,
    score_fit: 7,
    score_access: 8,
    score_overall: 5.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO audit and Google Ads for cocktails and tapas searches in DG12",
    why_them: "Stylish Annan restaurant and bar — tapas to steaks, cocktails to malts. Has a live website and social presence. Lower digital need but good fit for an SEO or Google Ads campaign targeting dining-out searches in Annan and the wider DG12 area.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "annan.org.uk, ourplaceannan.co.uk, Scotland Starts Here",
  },
  {
    business_name: "Del Amitri Restaurant at The Powfoot Hotel",
    url: "https://www.thepowfoothotel.com",
    location: "Links Avenue, Powfoot, Annan, DG12 5PN",
    sector: "Food & Drink",
    contact_phone: "01461 700300",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.1,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with food menu, dining reservation and golf package showcase",
    why_them: "Restaurant at the Powfoot Hotel golf resort near Annan — overlooking the Solway Firth. Has a live website but the food and dining section is under-developed versus the golf offer. A dedicated restaurant page with reservation and Sunday lunch promotion would drive dining covers.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "annan.org.uk, thepowfoothotel.com",
  },
  {
    business_name: "The Gretna Inn",
    url: null,
    location: "Gretna, DG16",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Simple website with menu, real ales list and local events",
    why_them: "The only central Gretna/Gretna Green pub with home-cooked food and a focus on local ales — Facebook active but no website. Positioned to capture Gretna wedding guests and M74 travellers. A simple site with menu and events calendar would dramatically improve discoverability.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Facebook, Scotland Starts Here",
  },
  // ─── ANNAN – Retail ───────────────────────────────────────────────────────────
  {
    business_name: "Caledonia Park Designer Outlet Gretna",
    url: "https://caledoniapark.com",
    location: "Glasgow Road, Gretna, DG16 5GG",
    sector: "Retail",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 2,
    score_pay: 9,
    score_fit: 5,
    score_access: 7,
    score_overall: 4.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Digital advertising campaign for outlet shopping tourist traffic",
    why_them: "50+ brand outlet mall near Gretna Green — well-managed website and social presence. Low web-design need but potential for Google Ads or SEO project targeting 'outlet shopping Scotland' searches from England. Monitor for paid campaign opportunity.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "caledoniapark.com, VisitScotland",
  },
  {
    business_name: "Xtra Help Annan",
    url: null,
    location: "32 Winterhope Road, Annan, DG12 5JL",
    sector: "Retail",
    contact_phone: "01461 205163",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 5,
    score_overall: 5.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple website with product categories and contact",
    why_them: "Hardware and home improvement store in Annan — phone-listed but no website. A simple product-category site with opening hours and contact details would help capture local DG12 hardware searches currently going to online retailers.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "annan.2day.uk",
  },
  // ─── ANNAN – Professional Services ───────────────────────────────────────────
  {
    business_name: "A C Eggleton & Co Ltd",
    url: null,
    location: "Annan, DG12 5AB",
    sector: "Professional Services",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 6,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.4,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Accountancy firm website with services, team bios and client portal link",
    why_them: "Annan-based accountants, financial advisers and registered auditors — listed on accountantfirms.co.uk but no standalone website. Accounting firms without websites consistently lose new client enquiries to better-digitised competitors. A professional site with a contact form and service descriptions would generate direct referrals.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "accountantfirms.co.uk",
  },
  // ─── ANNAN – Home Services ────────────────────────────────────────────────────
  {
    business_name: "Be-Dazzled Cleaning Services Annan",
    url: null,
    location: "Ty-Gwyn Lakeview, Powfoot, Annan, DG12 5PG",
    sector: "Home Services",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Cleaning company website with service areas, pricing guide and online booking",
    why_them: "Domestic cleaning service in Powfoot, Annan — Yell-listed with a 5-star rating from 10 reviews but no website. Strong reputation with no digital presence to match. A clean, simple website with a booking form would convert local cleaning searches into steady client relationships.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Yell",
  },
  // ─── ANNAN – Beauty & Wellness ────────────────────────────────────────────────
  {
    business_name: "Revive Beauty & Aesthetics Annan",
    url: null,
    location: "28-30 High Street, Annan, DG12 6AJ",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 6,
    score_fit: 8,
    score_access: 7,
    score_overall: 6.7,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Aesthetics and beauty clinic website with treatment menu, before/after gallery and online booking",
    why_them: "Beauty, aesthetics and complementary therapy clinic on Annan High Street — Fresha-listed with social media but no standalone website. Aesthetics is a premium service category where a professional website with a treatment gallery and booking system significantly lifts perceived credibility and converts consultations.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Fresha",
  },
  {
    business_name: "Colin James Hair Salon Annan",
    url: null,
    location: "120 High Street, Annan, DG12 6DP",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: "Colin James",
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Salon website with services, stylist profiles and online booking",
    why_them: "Hair salon on Annan High Street — Fresha-listed but no standalone website. A professional salon website with stylist profiles, a service menu with prices and an online booking calendar would reduce Fresha commission dependency and build a direct client base.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Fresha",
  },
  {
    business_name: "THE Salon Annan",
    url: null,
    location: "1-3 Bruce Street, Annan, DG12 5AB",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.3,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Hair and beauty website with online booking and service menu",
    why_them: "Hair and beauty salon on Bruce Street, Annan — Fresha presence only. An independent website with brand identity, service pricing and a booking system would help differentiate from other local salons and reduce platform dependency.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Fresha",
  },
  // ─── ANNAN – Automotive ───────────────────────────────────────────────────────
  {
    business_name: "Annantown Garage",
    url: null,
    location: "Annan, DG12 6BJ",
    sector: "Automotive",
    contact_phone: "01461 202832",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Garage website with MOT booking, services and contact",
    why_them: "MOT test centre and car service garage in Annan — Yell-listed and MOT-certified for Class 4 but no website. A simple site with an online MOT booking form and service menu would capture motorists searching for MOT centres in Annan online.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Yell, MOTRemind.me",
  },
  {
    business_name: "Tech Care Annan",
    url: null,
    location: "Church Street, Annan, DG12 6EA",
    sector: "Automotive",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 5,
    score_overall: 5.7,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Garage website with services, MOT booking and contact",
    why_them: "MOT test centre on Church Street, Annan — directory-listed only. A simple website with MOT and service information would help capture local search traffic and compete with better-digitised garages in the area.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "CheckMOT, MOTRemind.me",
  },
  // ─── ANNAN – Healthcare ───────────────────────────────────────────────────────
  {
    business_name: "Firth Veterinary Centre Annan",
    url: null,
    location: "Annan, DG12",
    sector: "Healthcare",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.4,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Veterinary practice website with services, team and online appointment request",
    why_them: "Veterinary centre in Annan — listed in the Annan healthcare directory but no website found. Vet practices without websites consistently miss out on new pet-owner registrations. A professional site with a register-your-pet form and emergency contact would drive new clients.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "annan.org.uk healthcare directory",
  },
  // ─── ANNAN – Childcare & Education ───────────────────────────────────────────
  {
    business_name: "Sparklers Private Nursery Annan",
    url: null,
    location: "Annan, DG12",
    sector: "Childcare & Education",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.1,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Nursery website with registration form, daily routine and team introduction",
    why_them: "Private nursery in Annan registered with Dumfries & Galloway Council — council directory listing only. Parents research childcare online before visiting. A warm, professional website with a registration enquiry form would directly increase enrollment enquiries from DG12 families.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Dumfries & Galloway Council ELC Directory",
  },
  {
    business_name: "Sparklers Private Nursery Gretna",
    url: null,
    location: "Gretna, DG16",
    sector: "Childcare & Education",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.1,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Nursery website with registration form, daily routine and parent information",
    why_them: "Private nursery in Gretna registered with Dumfries & Galloway Council — council directory listing only. Gretna is a busy visitor and resident area with a growing population. A nursery website with photos, staff bios and registration form would capture parent enquiries that currently go unanswered online.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Dumfries & Galloway Council ELC Directory",
  },
  // ─── ANNAN – Fitness & Leisure ────────────────────────────────────────────────
  {
    business_name: "The Deep Burn Gym Annan",
    url: null,
    location: "Unit 1, The Broom Industrial Estate, Annan, DG12 5PF",
    sector: "Fitness & Leisure",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.3,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Gym website with membership options, class timetable and online sign-up",
    why_them: "Independent gym on Annan's industrial estate — social media presence found but no standalone website. Independent gyms without websites struggle to compete with Regain Fitness and national chains on local search. A professional site with membership pricing and a sign-up form would capture search traffic and reduce reliance on social platforms.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Firmania",
  },
  {
    business_name: "Regain Fitness Annan",
    url: "https://www.regainfitness.co.uk",
    location: "96-98 High Street, Annan, DG12 6EJ",
    sector: "Fitness & Leisure",
    contact_phone: null,
    contact_email: "info@regainfitness.co.uk",
    contact_name: null,
    score_need: 4,
    score_pay: 6,
    score_fit: 7,
    score_access: 8,
    score_overall: 5.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and paid social for new Annan location launch and dual-membership promotion",
    why_them: "Second location of Regain Fitness opened on Annan High Street in 2025. Same parent company as Lockerbie site. New location presents a natural opportunity for a combined DG11/DG12 digital marketing campaign to drive dual memberships and awareness for the Annan launch.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "regainfitness.co.uk",
  },
]

async function run() {
  const { data: existing } = await supabase.from("prospects").select("business_name")
  const existingNames = new Set((existing ?? []).map((r: any) => r.business_name))
  const toInsert = prospects.filter(
    (p) => !existingNames.has(p.business_name) && (p.url || p.contact_phone || p.contact_email)
  )
  console.log(`Inserting ${toInsert.length} new records (skipping ${prospects.length - toInsert.length} already present)...`)
  let inserted = 0
  let skipped = 0
  for (const record of toInsert) {
    const { data, error } = await supabase.from("prospects").insert(record).select("id, business_name")
    if (error) {
      console.error(`✗ ${record.business_name}: ${error.message}`)
      skipped++
    } else {
      console.log(`✓ ${data?.[0]?.business_name}`)
      inserted++
    }
  }
  console.log(`\nDone. Inserted: ${inserted} | Errors: ${skipped}`)
}
run()
