import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const prospects = [
  // ── ACCOMMODATION ──────────────────────────────────────────────────────────
  {
    business_name: "Dumfries Villa",
    url: "https://www.dumfriesvilla.co.uk",
    location: "33 Lovers Walk, Dumfries, DG1 1LR",
    sector: "Accommodation",
    contact_phone: "01387 248609",
    contact_email: "info@dumfriesvilla.co.uk",
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website modernisation with direct booking integration",
    why_them: "Victorian townhouse B&B a short walk from Dumfries town centre and train station. Has an existing website but it's visually dated with no direct booking capability — relies entirely on OTAs. A refreshed site with a booking widget would reduce commission costs and improve conversion for direct guests.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "dumfriesvilla.co.uk, VisitScotland, bedandbreakfasts.co.uk",
  },
  {
    business_name: "Southpark House",
    url: "https://www.southparkhouse.co.uk",
    location: "Quarry Road, Locharbriggs, Dumfries, DG1 1FA",
    sector: "Accommodation",
    contact_phone: "07711 415414",
    contact_email: "info@southparkhouse.co.uk",
    contact_name: null,
    score_need: 6,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with SEO and direct booking system",
    why_them: "VisitScotland 4-Star Gold rated B&B on the edge of Dumfries with countryside views. Current website is functional but basic — no real SEO, no direct booking. Premium rating signals willingness to invest in quality; a modern site targeting 'luxury B&B Dumfries' searches would drive direct bookings.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "southparkhouse.co.uk, VisitScotland, scotlandsbestbandbs.co.uk",
  },

  // ── AUTOMOTIVE ─────────────────────────────────────────────────────────────
  {
    business_name: "James Haugh Ltd",
    url: "https://www.jameshaugh.co.uk",
    location: "2 St Mary's Street, Dumfries, DG1 1HD",
    sector: "Automotive",
    contact_phone: "01387 255291",
    contact_email: null,
    contact_name: null,
    score_need: 4,
    score_pay: 7,
    score_fit: 5,
    score_access: 6,
    score_overall: 5.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and landing pages for servicing/MOT to capture local search traffic",
    why_them: "Family-owned Vauxhall and MG dealership serving Dumfries for over 50 years. Has a live dealership website but is competing against national franchises online. Local SEO for 'Vauxhall servicing Dumfries' and service-specific landing pages could drive service bookings independent of the manufacturer portal.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "jameshaugh.co.uk, motremind.me, SMTA garage directory",
  },
  {
    business_name: "Irongray Autocentre",
    url: "https://www.irongrayautocentre.co.uk",
    location: "Unit 1 Irongray House, Irongray Road, Dumfries, DG2 0HS",
    sector: "Automotive",
    contact_phone: "01387 721728",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.4,
    has_website: true,
    website_status: "live",
    social_presence: "low",
    recommended_service: "Website refresh with MOT/service booking and local SEO",
    why_them: "Independent MOT and car sales centre on the DG2 edge of Dumfries. Website is live but thin — no online MOT booking, weak local SEO footprint. Independent garages in this area command strong loyalty; a booking-enabled site targeting 'MOT Dumfries DG2' could significantly boost volume.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "irongrayautocentre.co.uk, SMTA, motremind.me",
  },
  {
    business_name: "Grierson & Graham Ltd",
    url: "https://www.griersonandgraham.com",
    location: "365 Annan Road, Dumfries, DG1 3JR",
    sector: "Automotive",
    contact_phone: "01387 257800",
    contact_email: null,
    contact_name: null,
    score_need: 4,
    score_pay: 7,
    score_fit: 5,
    score_access: 6,
    score_overall: 5.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Local SEO and service booking landing pages",
    why_them: "Honda franchise dealership in Dumfries with over 100 years of trading history. Has a full dealership website but competing against Honda's national digital presence. Local SEO for Honda servicing in Dumfries and DG1/DG2 targeted paid campaigns would be a strong differentiator for their service centre.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "griersonandgraham.com, SMTA, motremind.me",
  },
  {
    business_name: "Lochthorn Car Sales",
    url: "http://www.lochthorncars.co.uk",
    location: "Lochthorn Services, Auchencrieff Road, Locharbriggs, Dumfries, DG1 1XL",
    sector: "Automotive",
    contact_phone: "01387 265444",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Used car inventory site refresh with local SEO and lead capture",
    why_them: "Independent used car dealership with car sales, servicing and repairs at Locharbriggs. Has a live website and Facebook page but the site is visually dated. Used car buyers increasingly search online first — a modernised inventory-led site with strong local SEO for 'used cars Dumfries' would drive qualified leads.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "lochthorncars.co.uk, motremind.me, Facebook",
  },
  {
    business_name: "ATS Euromaster Dumfries",
    url: "https://www.atseuromaster.co.uk",
    location: "76 Glasgow Street, Dumfries, DG2 9AQ",
    sector: "Automotive",
    contact_phone: "01387 263837",
    contact_email: null,
    contact_name: null,
    score_need: 3,
    score_pay: 6,
    score_fit: 4,
    score_access: 5,
    score_overall: 4.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Local landing page and Google Ads management for tyre and MOT services",
    why_them: "National tyre and MOT chain with a Dumfries branch. National web presence but the local Glasgow Street branch has thin local SEO. Google Ads targeting 'tyres Dumfries' and a locally optimised branch landing page would capture high-intent local searches lost to competitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "atseuromaster.co.uk, motremind.me, find-open.co.uk",
  },

  // ── CHILDCARE & EDUCATION (NURSERIES) ──────────────────────────────────────
  {
    business_name: "Playworks Nursery",
    url: "https://www.playworksdumfries.co.uk",
    location: "1 George Street, Dumfries, DG1 1EA",
    sector: "Childcare & Education",
    contact_phone: "01387 249990",
    contact_email: "contact@playworksdumfries.co.uk",
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website redesign with parent resources, registration portal and local SEO",
    why_them: "Long-established community nursery in Dumfries town centre offering funded ELC for 2–5 year olds, connected to the Dumfries Toy Library. Has a live website but it's basic — no online registration, thin parent information and poor mobile experience. Parents searching 'nursery Dumfries town centre' are an untapped direct enquiry channel.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "playworksdumfries.co.uk, D&G Council ELC directory",
  },
  {
    business_name: "Tots Paradise",
    url: null,
    location: "4 Kingholm Road, Dumfries, DG1 4AX",
    sector: "Childcare & Education",
    contact_phone: "01387 263821",
    contact_email: "tots_paradise50@yahoo.co.uk",
    contact_name: null,
    score_need: 9,
    score_pay: 4,
    score_fit: 8,
    score_access: 9,
    score_overall: 7.4,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "New website with nursery info, term dates, registration and local SEO",
    why_them: "Established nursery in the Kingholm Road area of Dumfries with no web presence at all — just a Yahoo email address. Parents searching for childcare in DG1 will never find them online. A simple professional site with contact form, fees info and Ofsted/Care Inspectorate details would immediately generate enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "threebestrated.co.uk, D&G Council ELC directory, daynurseries.co.uk",
  },
  {
    business_name: "Kinderhouse Nursery",
    url: "https://www.kinderhousenursery.com",
    location: "16 Laurieknowe, Dumfries, DG2 7AJ",
    sector: "Childcare & Education",
    contact_phone: "01387 264064",
    contact_email: "info@kinderhousenursery.com",
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "low",
    recommended_service: "Website refresh with modern design, parent portal and SEO",
    why_them: "Established DG2 nursery offering funded ELC and full-day holiday club. Has a live website but it's dated and has no online registration capability. Holiday club provision is a strong differentiator — a modernised site specifically targeting working parents searching 'holiday club Dumfries' and 'nursery DG2' would drive enquiries year-round.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "kinderhousenursery.com, threebestrated.co.uk, daynurseries.co.uk",
  },
  {
    business_name: "Little Wonderland Nursery",
    url: "https://www.littlewonderlandnursery.com",
    location: "Lochar House, Dumfries, DG1 3NU",
    sector: "Childcare & Education",
    contact_phone: "01387 444222",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "low",
    recommended_service: "Website enhancement with online enquiry, term dates and local SEO",
    why_them: "Recently established nursery (incorporated 2021) at Lochar House for 2–5 year olds. Has a basic website but limited SEO visibility and no online registration. New settings frequently struggle for discoverability; a properly optimised site with clear admissions information would shorten the time to full capacity.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "littlewonderlandnursery.com, D&G Council ELC directory, Companies House",
  },

  // ── CHILDCARE & EDUCATION (DRIVING SCHOOLS) ────────────────────────────────
  {
    business_name: "Pro-Motion Driving School",
    url: "https://www.pro-motiondrivingschool.co.uk",
    location: "14 Callum Drive, Dumfries, DG1 3EF",
    sector: "Childcare & Education",
    contact_phone: "07740 165983",
    contact_email: null,
    contact_name: "Gordon Riddell",
    score_need: 7,
    score_pay: 4,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.4,
    has_website: true,
    website_status: "live",
    social_presence: "low",
    recommended_service: "Website refresh with online lesson booking and local SEO",
    why_them: "DVSA-registered ADI offering manual driving lessons and Pass Plus in Dumfries. Has a live website but it lacks online booking and ranks poorly for 'driving lessons Dumfries'. A booking-capable site with learner testimonials and local keyword targeting would compete directly against larger national schools at a fraction of their budget.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "pro-motiondrivingschool.co.uk, Yell, threebestrated.co.uk",
  },
  {
    business_name: "Andy Hammond School of Motoring",
    url: null,
    location: "24 Gillbrae Crescent, Dumfries, DG1 4DQ",
    sector: "Childcare & Education",
    contact_phone: "01387 262365",
    contact_email: null,
    contact_name: "Andy Hammond",
    score_need: 9,
    score_pay: 3,
    score_fit: 7,
    score_access: 9,
    score_overall: 6.8,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "New website with lesson booking, prices and local SEO",
    why_them: "DVSA-approved driving instructor operating in Dumfries with no web presence. All business comes via word of mouth or directory listings. A straightforward professional site with an online enquiry form and local SEO for 'driving lessons Dumfries' would generate consistent new learner enquiries at very low cost.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "drivingschools4u.com, Yelp UK, getpassed.net",
  },

  // ── FITNESS & LEISURE ──────────────────────────────────────────────────────
  {
    business_name: "PureGym Dumfries",
    url: "https://www.puregym.com/gyms/dumfries/",
    location: "Unit 4, Dumfries Retail Park, College Mains Road, Dumfries, DG2 0NU",
    sector: "Fitness & Leisure",
    contact_phone: "03444 770005",
    contact_email: "info.dumfries@puregym.com",
    contact_name: null,
    score_need: 2,
    score_pay: 7,
    score_fit: 3,
    score_access: 5,
    score_overall: 3.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Local Google Ads and social media campaigns for membership acquisition",
    why_them: "National 24-hour gym chain on Dumfries Retail Park. National web presence handled centrally but the local branch has a dedicated Facebook and Instagram. Local digital advertising targeting DG1/DG2 postcodes for membership promotions would be more cost-effective than national campaigns for driving Dumfries footfall.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "puregym.com, Facebook, Instagram",
  },
  {
    business_name: "Bannatyne Health Club Dumfries",
    url: "https://www.bannatyne.co.uk/health-club/dumfries",
    location: "Marchfield House, Dumfries, DG1 1SE",
    sector: "Fitness & Leisure",
    contact_phone: "01387 255522",
    contact_email: "sales.dumfries@bannatyne.co.uk",
    contact_name: null,
    score_need: 3,
    score_pay: 7,
    score_fit: 4,
    score_access: 5,
    score_overall: 4.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Local SEO and Google Ads for membership and spa day bookings",
    why_them: "Full-service health club with gym, pool, spa and studio in Dumfries. National chain with a dedicated Dumfries Instagram (@bannatynedumfries, 1,500+ followers) and Facebook. The local branch competes hard for spa day and personal training leads — locally targeted digital campaigns for 'gym Dumfries' and 'spa day Dumfries' would supplement the national marketing spend.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "bannatyne.co.uk, Instagram @bannatynedumfries, Facebook",
  },
  {
    business_name: "JJ's Fitness Centre",
    url: null,
    location: "2-6 Nith Place, Dumfries, DG1 2PL",
    sector: "Fitness & Leisure",
    contact_phone: "01387 270172",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 8,
    score_access: 8,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "active_no_site",
    recommended_service: "New website with membership info, class timetable and local SEO",
    why_them: "Established independent gym in Dumfries town centre with TechnoGym equipment, free weights and resistance machines. Has an active Facebook page but zero web presence — completely invisible to 'gym Dumfries' searches. A professional site with a timetable and membership signup would capture the large volume of Dumfries gym searchers currently going straight to PureGym or Anytime Fitness.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hussle.com, Facebook /JJsDumfries, moovit",
  },
  {
    business_name: "Synergy Performance",
    url: "https://synergy-performance.co.uk",
    location: "218a Heathhall Industrial Estate, Heathhall, Dumfries, DG1 3PH",
    sector: "Fitness & Leisure",
    contact_phone: "07545 566007",
    contact_email: "info@synergy-performance.co.uk",
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 8,
    score_access: 7,
    score_overall: 6.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with class booking, nutrition packages and local SEO",
    why_them: "Independent performance gym and personal training studio at Heathhall offering fitness classes, free weights and nutrition packages. Has a live website and active Facebook page but the site is basic — no online class booking, limited SEO for 'personal training Dumfries'. Nutrition packages are a strong differentiator that the site doesn't showcase effectively.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "synergy-performance.co.uk, Facebook, Fresha, Yell",
  },

  // ── HOME SERVICES ──────────────────────────────────────────────────────────
  {
    business_name: "Solway Cleaning Services",
    url: "https://www.solwaycleaningservices.com",
    location: "54E Queen Street, Dumfries, DG1 2JP",
    sector: "Home Services",
    contact_phone: "07517 352177",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online booking and local SEO for each service",
    why_them: "Professional cleaning company established 2015, covering window cleaning, carpet cleaning, oven cleaning, gutter clearing and pressure washing across Dumfries and Galloway. Has a live website and Facebook page. The site has a booking link but poor SEO — separate landing pages for each service (e.g. 'carpet cleaning Dumfries', 'window cleaning DG1') would capture high-intent local searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "solwaycleaningservices.com, Facebook, Nextdoor, Wheree",
  },

  // ── TOURISM & ATTRACTIONS ──────────────────────────────────────────────────
  {
    business_name: "Mostly Ghostly Tours",
    url: "https://www.mostlyghostly.org",
    location: "Dumfries, DG1",
    sector: "Tourism & Attractions",
    contact_phone: "07791 047835",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 8,
    score_access: 8,
    score_overall: 6.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website redesign with online booking and seasonal SEO",
    why_them: "Dumfries-based paranormal investigation and ghost tour operator running since 2010 — the region's first of its kind. Covers ghost walks, castle, churchyard and theatre tours. Has a live website but it's basic and lacks integrated online booking. High-season demand around Halloween means a proper booking system and stronger SEO for 'ghost tours Dumfries' would directly increase revenue.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "mostlyghostly.org, VisitScotland, TripAdvisor, scotlandstartshere.com",
  },

  // ── WEDDING & EVENTS ───────────────────────────────────────────────────────
  {
    business_name: "GE Photography",
    url: "https://www.ge-photography.co.uk",
    location: "The Grain Store, 48 Whitesands, Dumfries, DG1 2RS",
    sector: "Wedding & Events",
    contact_phone: "01387 248810",
    contact_email: "info@ge-photography.co.uk",
    contact_name: "Graeme Edwards",
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO strategy and portfolio landing pages to increase direct enquiries",
    why_them: "Established Dumfries wedding, portrait, events and commercial photographer with a studio on Whitesands. Has a full website with portfolio and package pages, but ranks poorly for competitive 'wedding photographer Dumfries' searches dominated by aggregator sites. Dedicated SEO and structured data for wedding keywords would push organic enquiries past the directory noise.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "ge-photography.co.uk, UKbride, Bridebook, Dumfries & Galloway wedding guide",
  },
]

async function main() {
  console.log(`Inserting ${prospects.length} Dumfries remaining straggler prospects...`)

  const { data, error } = await supabase
    .from("prospects")
    .insert(prospects)
    .select()

  if (error) {
    console.error("Insert error:", error)
    process.exit(1)
  }

  console.log(`Successfully inserted ${data?.length ?? 0} prospects.`)

  const bySector: Record<string, number> = {}
  for (const p of prospects) {
    bySector[p.sector] = (bySector[p.sector] ?? 0) + 1
  }
  console.log("\nBreakdown by sector:")
  for (const [sector, count] of Object.entries(bySector)) {
    console.log(`  ${sector}: ${count}`)
  }
}

main()
