import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const prospects = [
  // ── PROFESSIONAL SERVICES ──────────────────────────────────────────────────

  {
    business_name: "Latham & Co Solicitors",
    url: null,
    location: "197 High Street, Dumfries, DG1 2QT",
    sector: "Professional Services",
    contact_phone: "01387 252888",
    contact_email: "office1@lathamandco.com",
    contact_name: null,
    score_need: 7,
    score_pay: 7,
    score_fit: 7,
    score_access: 8,
    score_overall: 7.2,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Professional brochure website with practice area pages and contact form",
    why_them: "High-Street solicitors listed on SLAB with no owned website — only directory and legal-aid board listings. A Dumfries firm operating without a web presence is losing prospective clients to competitors who rank on Google. Straightforward professional services site with strong local SEO value.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "192.com, SLAB solicitor finder, SolicitorTree",
  },
  {
    business_name: "A B & A Matthews Solicitors",
    url: "https://www.abamatthews.com",
    location: "The Old Bank, Buccleuch Street Bridge, Dumfries, DG2 7TJ",
    sector: "Professional Services",
    contact_phone: "01387 257300",
    contact_email: "dumfriesoffice@abamatthews.com",
    contact_name: null,
    score_need: 4,
    score_pay: 7,
    score_fit: 6,
    score_access: 8,
    score_overall: 5.6,
    has_website: true,
    website_status: "live",
    social_presence: "inactive",
    recommended_service: "Website modernisation with SEO and conversion optimisation",
    why_them: "Long-established (1871) solicitors and estate agents with Dumfries, Newton Stewart and Stranraer offices. Live website but it has an older design and limited SEO signals. With a busy property and legal practice, an improved site with modern search visibility could increase enquiries across all three offices.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "abamatthews.com, 192.com, SLAB solicitor finder",
  },
  {
    business_name: "Your Move Estate Agents Dumfries",
    url: "https://www.your-move.co.uk/estate-agent/dumfries",
    location: "2 Queensberry Street, Dumfries, DG1 1EX",
    sector: "Professional Services",
    contact_phone: "01387 257666",
    contact_email: "dumfries@your-move.co.uk",
    contact_name: null,
    score_need: 3,
    score_pay: 7,
    score_fit: 5,
    score_access: 7,
    score_overall: 4.85,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Local SEO and Google Business Profile optimisation",
    why_them: "National chain branch on Queensberry Street — local branch manager may be interested in complementary local SEO or Google Ads targeting Dumfries property searches to drive branch-specific leads. Lower fit for a new build but local visibility services are a credible upsell.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "your-move.co.uk, Zoopla, OnTheMarket",
  },
  {
    business_name: "McEwan Fraser Legal Dumfries",
    url: "https://www.mcewanfraserlegal.co.uk/estate-agents/dumfries",
    location: "Dumfries, DG1",
    sector: "Professional Services",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 3,
    score_pay: 7,
    score_fit: 5,
    score_access: 6,
    score_overall: 4.7,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Local SEO and Google Ads for Dumfries property searches",
    why_them: "Scottish estate agent/solicitor hybrid operating in Dumfries with an open 7-days-a-week model. National brand but they actively seek local leads — a pitch around local PPC or Google Business Profile management for the Dumfries market could be well received by a local partner.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "mcewanfraserlegal.co.uk, Rightmove, Getagent",
  },
  {
    business_name: "Sutherland Black Chartered Accountants",
    url: "https://www.sutherlandblack.co.uk",
    location: "Dumfries, DG1 (remote-served from Edinburgh/Livingston offices)",
    sector: "Professional Services",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.5,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Local SEO content targeting small business accountant searches in Dumfries",
    why_them: "Scottish firm of plain-talking accountants actively targeting Dumfries small businesses via their website. Has a live site and good content marketing presence but could benefit from stronger local landing pages and SEO to compete with established Dumfries names for DG1 search terms.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "sutherlandblack.co.uk, local-accountants-uk.co.uk",
  },
  {
    business_name: "Tom Donald Financial Services",
    url: "https://tomdonaldfinancial.co.uk",
    location: "62 St Michael Street, Dumfries, DG1 2QF",
    sector: "Professional Services",
    contact_phone: "01387 240075",
    contact_email: "tom@tomdonaldfinancial.co.uk",
    contact_name: "Tom Donald",
    score_need: 7,
    score_pay: 6,
    score_fit: 7,
    score_access: 8,
    score_overall: 7.0,
    has_website: true,
    website_status: "placeholder",
    social_presence: "facebook_only",
    recommended_service: "Professional website with lead capture, services pages and local SEO",
    why_them: "Independent financial adviser based on St Michael Street with a Wix-built site that lacks professional polish and SEO. Has a personal email contact and is clearly a one-person practice — exactly the kind of business that benefits from a credibility-building website to convert referrals and organic searches into appointments.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "tomdonaldfinancial.co.uk, mortgageadviser.directory, financialadvisers.co.uk",
  },
  {
    business_name: "Border Finance Ltd",
    url: "https://borderfinance.co.uk",
    location: "High Lodge, Dumfries, DG1 4EX",
    sector: "Professional Services",
    contact_phone: "01387 247827",
    contact_email: "info@borderfinance.bds-digital.co.uk",
    contact_name: "Andrew Finnie",
    score_need: 5,
    score_pay: 7,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "inactive",
    recommended_service: "Website modernisation with SEO and lead generation",
    why_them: "Established independent IFA practice (founded 2004) in Dumfries with a live website that has the appearance of being maintained by an external provider (bds-digital subdomain email). The site and email setup signals a business that could benefit from a fresh, properly branded digital presence to generate enquiries beyond word-of-mouth.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "borderfinance.co.uk, vouchedfor.co.uk, unbiased.co.uk",
  },

  // ── HEALTHCARE ─────────────────────────────────────────────────────────────

  {
    business_name: "DG Smile Dental Practice",
    url: "https://dgsmile.co.uk",
    location: "48 Whitesands, Dumfries, DG1 2RS",
    sector: "Healthcare",
    contact_phone: "01387 267070",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 8,
    score_fit: 7,
    score_access: 7,
    score_overall: 7.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website redesign with online booking, patient portal and local SEO",
    why_them: "Four-surgery NHS and private dental practice in a prime riverside Dumfries location. Has a live site (dgsmile.co.uk) but it appears dated and lacks strong local SEO signals for high-value private treatment searches (implants, veneers, cosmetic). A conversion-optimised redesign could drive measurably more private enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "dgsmile.co.uk, nhsinform.scot, whatclinic.com",
  },
  {
    business_name: "Blue Door Dental Practice",
    url: "https://bluedoordental.co.uk",
    location: "22 Castle Street, Dumfries, DG1 1DT",
    sector: "Healthcare",
    contact_phone: "01387 261700",
    contact_email: "bluedoordental@gmail.com",
    contact_name: null,
    score_need: 7,
    score_pay: 7,
    score_fit: 7,
    score_access: 8,
    score_overall: 7.15,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website rebuild and local SEO — replace Gmail with professional email",
    why_them: "NHS family dental practice on Castle Street, established 15+ years. Has a live site but uses a gmail.com contact address — a clear indicator that digital credibility is lacking. A professional website with a branded email setup, online appointment requests and better local SEO would improve both trust and new patient conversion.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "bluedoordental.co.uk, nhsinform.scot, Yell",
  },
  {
    business_name: "GK Dental (Great King Street)",
    url: "https://gkdental.co.uk",
    location: "7 Great King Street, Dumfries, DG1 1BA",
    sector: "Healthcare",
    contact_phone: "01387 266456",
    contact_email: "Info.gkdental@gmail.com",
    contact_name: null,
    score_need: 7,
    score_pay: 7,
    score_fit: 7,
    score_access: 8,
    score_overall: 7.15,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Professional website upgrade and branded email — replace Gmail",
    why_them: "NHS and private dental practice in Dumfries town centre. Has a live site but uses a Gmail address, undermining credibility. Good opportunity to propose a professional rebrand of their web and email presence alongside better local SEO targeting cosmetic and private dental searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "gkdental.co.uk, nhsinform.scot, nhsdg.scot.nhs.uk",
  },
  {
    business_name: "Dunne & Drennan Eyecare",
    url: "http://www.dunnedrennaneyecare.co.uk",
    location: "68-72 English Street, Dumfries, DG1 2BY",
    sector: "Healthcare",
    contact_phone: "01387 255376",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.65,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website modernisation with online appointment booking and local SEO",
    why_them: "Independent opticians opened in 2015 by Frances Dunne and Fiona Drennan on English Street. Has a live website (separate from Frances Dunne Eyecare which is already in the DB) but the site looks older and lacks online booking. Strong fit for a modern professional site with frame gallery, booking integration and improved search rankings.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "dunnedrennaneyecare.co.uk, lovedumfries.co.uk, coopervision.co.uk",
  },
  {
    business_name: "Optical Express Dumfries",
    url: "https://www.opticalexpress.co.uk/clinic-finder/scotland/dumfries-queensberry-house",
    location: "First Floor, Queensberry House, 147 High Street, Dumfries, DG1 2QT",
    sector: "Healthcare",
    contact_phone: "01387 213193",
    contact_email: null,
    contact_name: null,
    score_need: 3,
    score_pay: 7,
    score_fit: 4,
    score_access: 6,
    score_overall: 4.45,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Local SEO and Google Ads for laser eye surgery searches in Dumfries",
    why_them: "National chain laser eye surgery and opticians clinic on Dumfries High Street. Low fit for a website build but local branch manager may be receptive to local PPC or Google Business Profile management to drive enquiries for laser eye surgery — high-value treatments with strong search intent.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "opticalexpress.co.uk, Yell, chamberofcommerce.uk",
  },
  {
    business_name: "Lochthorn Pharmacy",
    url: null,
    location: "Lochthorn Medical Centre, Edinburgh Road, Locharbriggs, Dumfries, DG1 1TR",
    sector: "Healthcare",
    contact_phone: "01387 251111",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple brochure website with services list, opening hours and click-to-call",
    why_them: "Independent community pharmacy at the Lochthorn Medical Centre — NHS dispensing plus private services. Has no owned website, only directory listings. A professional pharmacy website with online prescription request capability and local SEO would help differentiate from chain pharmacies nearby.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "healthera.co.uk, npn.org.uk, nhsinform.scot",
  },
  {
    business_name: "G R Blount Pharmacy",
    url: null,
    location: "St Michaels Bridge Road, Dumfries, DG1 2PX",
    sector: "Healthcare",
    contact_phone: "01387 262244",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.3,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Independent pharmacy website with prescription services, NHS info and local SEO",
    why_them: "Long-established independent pharmacy on St Michaels Bridge Road with no online presence beyond directory listings. Excellent opportunity to pitch a clean, trust-building site that helps this independent compete for local prescription and OTC health product searches against Boots and Lloyds.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "dumfries.ukintouch.com, cylex-uk.co.uk, communitypharmacy.scot.nhs.uk",
  },
  {
    business_name: "William Murray Pharmacy",
    url: null,
    location: "35 Galloway Street, Dumfries, DG2 7TN",
    sector: "Healthcare",
    contact_phone: "01387 266248",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.3,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Independent pharmacy website with services, prescription info and local SEO",
    why_them: "Independent community pharmacy on Galloway Street (DG2) with no digital presence. Same pitch as GR Blount — community pharmacies without websites lose search traffic to national chains. A credible professional site with local SEO targeting 'pharmacy near me' and 'prescription collection Dumfries' could generate meaningful footfall.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Yell, locatepharmacy.co.uk, npn.org.uk",
  },
  {
    business_name: "Ark Vet Centre Dumfries",
    url: "https://www.arkvetcentre.co.uk",
    location: "Unit 5, St Mary's Industrial Estate, Dumfries, DG1 1NA",
    sector: "Healthcare",
    contact_phone: "01387 259111",
    contact_email: "enquiries@arkvetcentre.co.uk",
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 6,
    score_access: 8,
    score_overall: 6.05,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online booking, pet health resources and local SEO",
    why_them: "Independent employee-owned 5-centre mixed animal practice headquartered at St Mary's Industrial Estate, Dumfries. Has a professional email and live website, but as an independently run practice competing against national vet chains, an improved digital presence with online appointment booking and pet health content could drive client acquisition.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "arkvetcentre.co.uk, findavet.rcvs.org.uk, 192.com",
  },
  {
    business_name: "Nithsdale Vets",
    url: "https://www.nithsdalevets.co.uk",
    location: "The Vet Centre, Martinton Place, Heathhall, Dumfries, DG1 3QN",
    sector: "Healthcare",
    contact_phone: "01387 253402",
    contact_email: "nithsdalevc@hotmail.co.uk",
    contact_name: null,
    score_need: 7,
    score_pay: 7,
    score_fit: 7,
    score_access: 8,
    score_overall: 7.15,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website redesign with branded email, online booking and local SEO",
    why_them: "Well-established mixed animal practice in Heathhall with multi-site cover (Thornhill, Kirkconnel). Has a live website and Facebook presence, but uses a Hotmail email address — a clear signal of underinvestment in digital. A professional rebrand with proper email hosting, online appointments and SEO would modernise their client acquisition significantly.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "nithsdalevets.co.uk, findavet.rcvs.org.uk, Yell",
  },
  {
    business_name: "Lochduhar Care Home",
    url: "https://www.barchester.com/home/lochduhar-care-home",
    location: "1 Blackley Park Road, Dumfries, DG2 9JW",
    sector: "Healthcare",
    contact_phone: "01387 424610",
    contact_email: null,
    contact_name: null,
    score_need: 3,
    score_pay: 7,
    score_fit: 4,
    score_access: 5,
    score_overall: 4.3,
    has_website: true,
    website_status: "live",
    social_presence: "inactive",
    recommended_service: "Local SEO and Google Ads for care home enquiries in Dumfries",
    why_them: "Large Barchester nursing and dementia care home (89 beds) on the outskirts of Dumfries. National brand with local manager — a local Google Ads or local SEO retainer for the Dumfries market could be valuable given the high cost-per-placement in care home searches and the local decision-making nature of care home selection.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "barchester.com, carehome.co.uk, Yell",
  },
  {
    business_name: "Goldielea Care Home",
    url: "https://www.advinia.co.uk/care-homes/goldielea-care-home/",
    location: "Dalbeattie Road, Dumfries, DG2 7PE",
    sector: "Healthcare",
    contact_phone: "01387 403371",
    contact_email: null,
    contact_name: null,
    score_need: 4,
    score_pay: 7,
    score_fit: 4,
    score_access: 5,
    score_overall: 4.7,
    has_website: true,
    website_status: "live",
    social_presence: "inactive",
    recommended_service: "Local SEO and Google Ads for care home enquiries in Dumfries",
    why_them: "Grade 2 listed residential, nursing and dementia care home in 10 acres of parkland on Dalbeattie Road (DG2). Operated by Advinia Healthcare. Similar to Lochduhar — national operator, local decisions. Local digital marketing for care-home-related search terms in D&G could drive family enquiries and bed-fill rate.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "advinia.co.uk, carehome.co.uk, lottie.org",
  },

  // ── BEAUTY & WELLNESS ──────────────────────────────────────────────────────

  {
    business_name: "Nelson Brown Hair and Beauty",
    url: "https://www.nelsonbrown.co.uk",
    location: "34 Whitesands, Dumfries, DG1 2RS",
    sector: "Beauty & Wellness",
    contact_phone: "01387 249944",
    contact_email: "reception@nelsonbrown.co.uk",
    contact_name: null,
    score_need: 4,
    score_pay: 7,
    score_fit: 7,
    score_access: 8,
    score_overall: 5.85,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO optimisation and conversion improvements to online booking flow",
    why_them: "Premier hair and beauty salon on Whitesands with a live site and professional email. Has online booking via Fresha and active social channels — relatively well set up. Lower immediate need, but could benefit from improved Google rankings for high-intent searches like 'hair salon Dumfries' and better on-site conversion to drive direct bookings away from Fresha.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "nelsonbrown.co.uk, Fresha, Yell",
  },
  {
    business_name: "Jackie Barbour Hair Design",
    url: "https://jackiebarbourhairdesign.co.uk",
    location: "71 Friars Vennel, Dumfries, DG1 2RQ",
    sector: "Beauty & Wellness",
    contact_phone: "01387 262232",
    contact_email: "jackiebarbour1@sky.com",
    contact_name: "Jackie Barbour",
    score_need: 7,
    score_pay: 6,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.9,
    has_website: true,
    website_status: "live",
    social_presence: "inactive",
    recommended_service: "Website modernisation with online booking and branded email",
    why_them: "Established hairdresser in Friars Vennel with a live website, but Sky email address signals this is a long-standing business that hasn't updated its digital infrastructure. A modern site with online booking, a portfolio gallery and proper email would significantly improve client acquisition and reduce reliance on walk-ins and word of mouth.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "jackiebarbourhairdesign.co.uk, lovedumfries.co.uk, Yell",
  },
  {
    business_name: "Slate Hairdressing",
    url: "http://www.slatehair.co.uk",
    location: "17 Bank Street, Dumfries, DG1 2NX",
    sector: "Beauty & Wellness",
    contact_phone: "01387 265907",
    contact_email: "salon@slatehairdressing.co.uk",
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online booking integration and local SEO",
    why_them: "Well-reviewed independent hair salon on Bank Street with a professional email address and live website. The site appears dated — a modernised version with Fresha or direct booking integration, a portfolio gallery and local SEO targeting 'hairdresser Dumfries town centre' searches would improve new client capture.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "slatehair.co.uk, lovedumfries.co.uk, Fresha",
  },
  {
    business_name: "DH Hairdressing",
    url: "https://www.fresha.com/a/dh-hairdressing-dumfries-95-irish-street-dumfries-e6q801if",
    location: "95 Irish Street, Dumfries, DG1 2NP",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.95,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "New website with portfolio, services menu, online booking and local SEO",
    why_them: "Highly rated (5.0, 63 reviews on Fresha) independent hairdresser on Irish Street offering hair extensions, wedding hair, kids parties and ear piercing. Entirely dependent on Fresha and Facebook for digital presence — no owned website. A professional site would reduce platform dependency and capture Google searches for extensions and wedding hair in Dumfries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Fresha, Facebook @daynaharknesshairdressing",
  },
  {
    business_name: "Scizzorkicks Barbers",
    url: null,
    location: "10 Great King Street, Dumfries, DG1 1BD",
    sector: "Beauty & Wellness",
    contact_phone: "01387 249924",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.95,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple barber website with services, prices, booking link and local SEO",
    why_them: "Barber on Great King Street with no web presence at all — found only through Whaircut and 192.com. Barbershops without websites are invisible on Google Maps and local search. A simple one-page site with click-to-call, pricing and a walk-in/appointment guide would pay for itself quickly in new clients.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "whaircut.co.uk, 192.com",
  },
  {
    business_name: "Crew Cuts Barber Shop",
    url: null,
    location: "18 Academy Street, Dumfries, DG1 1BY",
    sector: "Beauty & Wellness",
    contact_phone: "01387 266314",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.95,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Barber website with services, pricing, booking and local SEO",
    why_them: "Barber shop on Academy Street in Dumfries town centre with a phone listing but no website or social presence. Same opportunity as Scizzorkicks — a well-placed Google-ranked site targeting 'barbers Dumfries' would capture walk-in trade that currently goes to businesses with a web presence.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Yelp, 192.com, bigreddirectory.com",
  },
  {
    business_name: "6TY Shades of Beauty",
    url: "https://www.6tyshadesofbeauty.co.uk",
    location: "105 Irish Street, Dumfries, DG1 2NP",
    sector: "Beauty & Wellness",
    contact_phone: "01387 247448",
    contact_email: null,
    contact_name: null,
    score_need: 4,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO optimisation, booking conversion and e-commerce for retail products",
    why_them: "Full-service beauty salon on Irish Street offering nails, lashes, brows, tanning, skin and makeup — 260+ reviews on Birdeye and active Instagram. Has a live website and active social presence. Lower need for a site build but strong candidate for SEO improvements and potentially a product shop integration for beauty retail.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "6tyshadesofbeauty.co.uk, Fresha, Birdeye, Instagram",
  },
  {
    business_name: "GTC Custom Tattoo & Art Collective",
    url: "https://www.gtctattoo.co.uk",
    location: "18 Bank Street, Dumfries, DG1 2NX",
    sector: "Beauty & Wellness",
    contact_phone: "01387 265775",
    contact_email: null,
    contact_name: "Gary Caven",
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with artist portfolio, booking system and local SEO",
    why_them: "Family-run custom tattoo studio on Bank Street established in 2010, well regarded in Dumfries. Has a live website and Fresha booking. The site could benefit from a stronger portfolio showcase, artist profiles and SEO targeting 'custom tattoo Dumfries' and 'tattoo studio near me' searches to attract clients from across D&G.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "gtctattoo.co.uk, Fresha, Yell, GetInked",
  },
  {
    business_name: "Needleworks Tattoo Studio",
    url: "https://www.fresha.com/lvp/needleworks-english-street-znN12o",
    location: "57-59 English Street, Dumfries, DG1 2DA",
    sector: "Beauty & Wellness",
    contact_phone: "01387 264663",
    contact_email: "tattoos@needleworkstattoo.com",
    contact_name: null,
    score_need: 6,
    score_pay: 6,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "New website with artist portfolio, services, flash gallery and local SEO",
    why_them: "Award-winning tattoo and piercing studio with 25+ years experience on English Street. Highly regarded locally but has no owned website — only Fresha listing and Facebook. A proper studio website with artist portfolios, flash galleries, aftercare info and local SEO would establish stronger authority and reduce dependence on third-party platforms.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Fresha, wozupscotland.co.uk, GetInked, Wheree",
  },
  {
    business_name: "Tattoo City Dumfries",
    url: null,
    location: "66 Friars Vennel, Dumfries, DG1 2RL",
    sector: "Beauty & Wellness",
    contact_phone: "01387 255726",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.95,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Tattoo studio website with artist portfolio, booking and local SEO",
    why_them: "Tattoo and piercing shop on Friars Vennel with a phone number but no website or social media presence at all. A studio without an online portfolio is invisible to potential clients searching for 'tattoo Dumfries' — the most straightforward high-need pitch in this batch.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "localstore.co.uk, cylex-uk.co.uk",
  },
]

async function run() {
  const { data: existing } = await supabase.from("prospects").select("business_name")
  const existingNames = new Set((existing ?? []).map((r: any) => r.business_name))
  const toInsert = prospects.filter(
    (p) => !existingNames.has(p.business_name) && (p.url || p.contact_phone || p.contact_email)
  )
  console.log(`Inserting ${toInsert.length} new records...`)
  for (const record of toInsert) {
    const { data, error } = await supabase.from("prospects").insert(record).select("id, business_name")
    if (error) console.error(`✗ ${record.business_name}:`, error.message)
    else console.log(`✓ ${data?.[0]?.business_name}`)
  }
}
run()
