import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const prospects = [
  // ─── MOFFAT — Food & Drink ───────────────────────────────────────────────
  {
    business_name: "Brodies of Moffat",
    url: "https://www.brodiesofmoffat.co.uk",
    location: "1-2 Altrive Place, Holm Street, Moffat, DG10 9EB",
    sector: "Food & Drink",
    contact_phone: "01683 222870",
    contact_email: "whatscooking@brodiesofmoffat.co.uk",
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with SEO and online booking",
    why_them:
      "Award-winning restaurant, gin & coffee lounge in central Moffat. Good Food Award winner with loyal following. Existing site is functional but lacks local SEO punch and online booking capability — a high-footfall venue that would benefit from a modern, conversion-focused site.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "brodiesofmoffat.co.uk, DG Food and Drink, VisitScotland",
  },
  {
    business_name: "Claudios Restaurant Moffat",
    url: "https://claudiosmoffat.co.uk",
    location: "Burnside Road (Old Police Station), Moffat, DG10 9DX",
    sector: "Food & Drink",
    contact_phone: "01683 220958",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website modernisation with online booking and menu showcase",
    why_them:
      "Family-run Italian restaurant since 1996 — a Moffat institution. Site exists but is basic; no online booking and limited mobile optimisation. Long tenure demonstrates financial stability and appetite for quality. Good candidate for a conversion-focused refresh.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "claudiosmoffat.co.uk, TripAdvisor",
  },
  {
    business_name: "Hugo's Moffat",
    url: "https://www.hugosmoffat.uk",
    location: "4 Bath Place, Moffat, DG10 9HJ",
    sector: "Food & Drink",
    contact_phone: "01683 221606",
    contact_email: "info@hugosmoffat.uk",
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 8,
    score_access: 7,
    score_overall: 6.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with SEO, online booking and gift vouchers",
    why_them:
      "Upmarket Scottish tapas and sharing plates restaurant with consistently strong TripAdvisor reviews. Gluten-free specialism appeals to health-conscious tourists passing through Moffat on the A701. Current site is clean but thin on SEO content; no gift vouchers or booking integration.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "hugosmoffat.uk, TripAdvisor, Yelp",
  },
  {
    business_name: "Spice India Moffat",
    url: null,
    location: "Lower Craignelder, High Street, Moffat, DG10 9ED",
    sector: "Food & Drink",
    contact_phone: "01683 220900",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.2,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Starter website with online menu and takeaway ordering",
    why_them:
      "Fully licensed Indian restaurant and takeaway with delivery up to 15-mile radius — no website found. Moffat has strong tourist footfall and the absence of an online ordering/menu page is a clear gap. Low-friction starter site opportunity.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, Yell, Restaurantji",
  },

  // ─── MOFFAT — Accommodation ──────────────────────────────────────────────
  {
    business_name: "Buchan Guest House Moffat",
    url: "https://www.guesthouse-moffat.com",
    location: "13 Beechgrove, Moffat, DG10 9RS",
    sector: "Accommodation",
    contact_phone: "01683 220378",
    contact_email: "buchanguesthouse@gmail.com",
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking integration and SEO",
    why_them:
      "Victorian listed building B&B with 6 en-suite rooms in Moffat. Has a live website but it appears dated and relies on third-party booking platforms — direct booking integration would reduce commission costs. Good fit for a clean, modern accommodation site.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "guesthouse-moffat.com, TripAdvisor",
  },
  {
    business_name: "Rockhill Guest House Moffat",
    url: "https://www.rockhillmoffat.co.uk",
    location: "14 Beechgrove, Moffat, DG10 9RS",
    sector: "Accommodation",
    contact_phone: "01683 220283",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking and local SEO",
    why_them:
      "Victorian guest house open March–November in a quiet Moffat avenue. Has its own domain but the site lacks modern design and direct booking. Seasonal open window means targeted off-season promotion could extend revenue — a practical upsell for a new site.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "rockhillmoffat.co.uk, TripAdvisor, VisitScotland",
  },
  {
    business_name: "Seamore Guest House Moffat",
    url: "https://www.seamorehousebandb.co.uk",
    location: "Academy Road, Moffat, DG10 9HW",
    sector: "Accommodation",
    contact_phone: "01683 225257",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking and local SEO",
    why_them:
      "Charming Victorian-era B&B within walking distance of Moffat's main attractions including the Old Well Theatre and Golf Club. Active Facebook presence. Site exists but could be significantly improved with direct booking and better local search visibility.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "seamorehousebandb.co.uk, TripAdvisor, Kayak",
  },

  // ─── MOFFAT — Retail ─────────────────────────────────────────────────────
  {
    business_name: "The Moffat Bookshop",
    url: "http://themoffatbookshop.co.uk",
    location: "5 Well Street, Moffat, DG10 9DP",
    sector: "Retail",
    contact_phone: "01683 478088",
    contact_email: "themoffatbookshop@hotmail.com",
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.8,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Modern website with online catalogue and local SEO",
    why_them:
      "Independent bookshop on Moffat's main shopping street, listed on AbeBooks. Existing site appears very minimal. A well-designed independent bookshop site with stock search and local SEO would help capture tourist footfall and online book-lovers in the region.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "themoffatbookshop.co.uk, AbeBooks, IndieRetail",
  },
  {
    business_name: "Lothlorien Antique & Collectables Emporium",
    url: null,
    location: "22 Well Street, Moffat, DG10 9DP",
    sector: "Retail",
    contact_phone: "01683 221144",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.8,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter website with stock showcase and contact/directions",
    why_them:
      "Family-run antiques and collectables emporium on Well Street with a free toy museum on the first floor — a genuine tourist draw. No website found. A simple showcase site with photos, directions and opening hours would significantly improve discoverability for passing tourists.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Antiques Atlas, Antique Central, Yell",
  },
  {
    business_name: "Manse Interiors Moffat",
    url: null,
    location: "15 High Street, Moffat, DG10 9DL",
    sector: "Retail",
    contact_phone: "01683 221676",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.6,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Brochure website with product showcase, inspiration gallery and contact",
    why_them:
      "Independent interior design and furniture shop open 7 days a week on Moffat High Street. Active Facebook presence but no dedicated website found. A well-designed interiors showcase site with a gallery and local delivery info would attract both local homeowners and holiday cottage buyers.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Yell, Kompass, Facebook, Wozup Scotland",
  },

  // ─── MOFFAT — Beauty & Wellness ──────────────────────────────────────────
  {
    business_name: "Beauty Matters Moffat",
    url: null,
    location: "11 Well Street, Moffat, DG10 9DP",
    sector: "Beauty & Wellness",
    contact_phone: "01683 221505",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Starter website with service menu, online booking and local SEO",
    why_them:
      "Long-standing beauty salon on Moffat's main shopping street. No website found — relies entirely on word of mouth and Facebook. A simple booking-enabled site would help capture local and tourist customers searching for beauty treatments in Moffat.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "192.com, Nextdoor, Fresha, Secret Salons",
  },
  {
    business_name: "Rhoda's Hair Design Moffat",
    url: null,
    location: "31 Well Street, Moffat, DG10 9DP",
    sector: "Beauty & Wellness",
    contact_phone: "01683 220268",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.8,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter website with service list, pricing and online booking",
    why_them:
      "Hair salon on Well Street with no web presence beyond directory listings. In a tourist town like Moffat, visitors searching for a local hairdresser will default to whoever shows up online. A simple booking-enabled site is a quick win.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "192.com, Fresha, Secret Salons",
  },

  // ─── MOFFAT — Trades & Construction ─────────────────────────────────────
  {
    business_name: "Drummond & Murray Ltd",
    url: null,
    location: "36 Well Street, Moffat, DG10 9DP",
    sector: "Trades & Construction",
    contact_phone: "01683 220065",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter trades website with service list, area coverage and quote form",
    why_them:
      "Established plumbing and heating firm based in Moffat town centre — registered company (SC038018). No website found; listed across Thomson Local and Yell. Tradespeople without websites increasingly lose enquiries to competitors online.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "192.com, Thomson Local, Yell, Companies House",
  },

  // ─── LANGHOLM — Trades & Construction ───────────────────────────────────
  {
    business_name: "M. Borthwick Joinery",
    url: null,
    location: "29 Whitaside, Langholm, DG13 0JS",
    sector: "Trades & Construction",
    contact_phone: "01387 380847",
    contact_email: "martinborthwick@icloud.com",
    contact_name: "Martin Borthwick",
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter trades website with portfolio, services and contact",
    why_them:
      "Joiner and carpenter based in Langholm with no web presence. Listed in the welcometolangholm.co.uk local directory. A simple portfolio site with contact form would significantly improve lead generation in a rural area where most work comes from personal referrals.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },
  {
    business_name: "M. Haining Ltd",
    url: null,
    location: "Craigielea, 1 Rosevale Street, Langholm, DG13 0DS",
    sector: "Trades & Construction",
    contact_phone: "07785 977670",
    contact_email: null,
    contact_name: "Michael Haining",
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter electrician website with services, qualifications and quote form",
    why_them:
      "Electrician operating as a limited company (M. Haining Ltd) in Langholm with no web presence. Rural Dumfriesshire electricians rarely appear in local search results — a simple site would make this firm the first result for 'electrician Langholm' searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },
  {
    business_name: "Ross Calvert Joiner",
    url: null,
    location: "2 Charlotte Street, Langholm, DG13 0DZ",
    sector: "Trades & Construction",
    contact_phone: "07910 388242",
    contact_email: "peter_calvert@btinternet.com",
    contact_name: "Ross Calvert",
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.8,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter joinery website with portfolio and contact",
    why_them:
      "Independent joiner in Langholm with no website. Listed in the town's own directory, suggesting an established local reputation. A portfolio site showcasing past work would generate higher-value enquiries beyond word of mouth.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },
  {
    business_name: "Divers Plumbing & Heating",
    url: null,
    location: "Brastagi, Wauchope Street, Langholm, DG13 0AY",
    sector: "Trades & Construction",
    contact_phone: "07743 418230",
    contact_email: "diversphb@outlook.com",
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Starter plumbing & heating website with services, area coverage and quote form",
    why_them:
      "Plumbing and heating business in Langholm with a Facebook page but no website. Has a branded Facebook presence (facebook.com/diversphb) suggesting awareness of online marketing — a natural next step to a proper site with quote forms.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },
  {
    business_name: "Kevan Hotson Builder",
    url: null,
    location: "Braidpath, Langholm, DG13 0LH",
    sector: "Trades & Construction",
    contact_phone: "07714 463178",
    contact_email: "kevanhotsonbuilder@yahoo.co.uk",
    contact_name: "Kevan Hotson",
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.8,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter builder website with services, coverage and contact",
    why_them:
      "Independent builder operating in Langholm area with no web presence. Has a branded email address suggesting professionalism. Rural builders in DG13 are almost entirely absent from search results — a simple site would immediately improve enquiry volume.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },
  {
    business_name: "J&S Hotson Building Services",
    url: null,
    location: "9 Holmwood Drive, Langholm, DG13 0PX",
    sector: "Trades & Construction",
    contact_phone: "01387 380121",
    contact_email: null,
    contact_name: "Steven Hotson",
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.8,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter builder website with services and contact form",
    why_them:
      "Building services firm in Langholm with a landline number but no online presence. Given the volume of rural property renovation work in Eskdale and Liddesdale, a simple website would help capture homeowners who search before calling.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },

  // ─── LANGHOLM — Accommodation ────────────────────────────────────────────
  {
    business_name: "Border House B&B Langholm",
    url: "https://www.border-house.co.uk",
    location: "28 High Street, Langholm, DG13 0JH",
    sector: "Accommodation",
    contact_phone: "013873 80375",
    contact_email: null,
    contact_name: "Moira Beattie",
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking and local SEO",
    why_them:
      "Family-run B&B on the A7 tourist route through Langholm. Has a live website and Facebook presence. Site is functional but shows its age — direct booking integration and a fresher design would reduce reliance on OTAs and improve margins.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "border-house.co.uk, welcometolangholm.co.uk, TripAdvisor",
  },
  {
    business_name: "Ewes Water Log Cabins",
    url: "https://www.eweswaterlogcabins.co.uk",
    location: "A7 Road, Langholm, DG13 0HX",
    sector: "Accommodation",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 8,
    score_access: 7,
    score_overall: 6.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website upgrade with direct booking, SEO and photography showcase",
    why_them:
      "Three luxury log cabins overlooking the River Ewes — a premium self-catering product positioned near Gretna for wedding parties. Active Facebook following. Current site exists but could be significantly upgraded with direct booking, better SEO and a visual showcase to justify premium rates.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "eweswaterlogcabins.co.uk, VisitScotland, Booking.com",
  },
  {
    business_name: "The Douglas Hotel Langholm",
    url: "https://www.douglashotellangholm.co.uk",
    location: "86 High Street, Langholm, DG13 0DH",
    sector: "Accommodation",
    contact_phone: "013873 81547",
    contact_email: "enquiries@douglashotellangholm.co.uk",
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 8,
    score_access: 7,
    score_overall: 6.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with direct booking, restaurant and events showcase",
    why_them:
      "Restored family-run coaching inn with 4 en-suite rooms and an acclaimed restaurant on Langholm High Street. Active site but could benefit from integrated booking, events calendar and local SEO. A premium DG13 property well worth targeting.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "douglashotellangholm.co.uk, TripAdvisor, Yelp",
  },

  // ─── LANGHOLM — Food & Drink ─────────────────────────────────────────────
  {
    business_name: "Zara Continental Restaurant Langholm",
    url: "https://zaracontinental.com",
    location: "81 High Street, Langholm, DG13 0DJ",
    sector: "Food & Drink",
    contact_phone: "01387 320123",
    contact_email: "customer.service@zaracontinental.com",
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website modernisation with online ordering, menus and booking",
    why_them:
      "Indian restaurant, hotel and takeaway on Langholm High Street. Has a domain and email address. A modernised site with online ordering and takeaway capability would significantly improve revenue from the local and tourist market.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "zaracontinental.com, TripAdvisor, welcometolangholm.co.uk",
  },
  {
    business_name: "CastleView Catering at The Buccleuch Centre",
    url: null,
    location: "The Buccleuch Centre, Langholm, DG13 0AW",
    sector: "Food & Drink",
    contact_phone: "07468 194551",
    contact_email: "castleviewcatering@gmail.com",
    contact_name: "Tracey Goodfellow",
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.6,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Starter website with café menu, catering packages and enquiry form",
    why_them:
      "In-house caterers at the Buccleuch Centre — Langholm's main community and events venue. Also offers outside catering for weddings and parties. Active Instagram. No website found; a catering showcase site with enquiry form would immediately support the events and wedding pipeline.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, welcometolangholm.co.uk, Instagram",
  },

  // ─── LANGHOLM — Retail ───────────────────────────────────────────────────
  {
    business_name: "Latimers of Langholm",
    url: "https://www.latimersoflangholm.co.uk",
    location: "49-51 High Street, Langholm, DG13 0JH",
    sector: "Retail",
    contact_phone: "013873 80265",
    contact_email: "info@latimersoflangholm.co.uk",
    contact_name: "David Latimer",
    score_need: 5,
    score_pay: 7,
    score_fit: 8,
    score_access: 7,
    score_overall: 6.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with e-commerce functionality and local delivery",
    why_them:
      "Independent family furniture and homeware store established in 1882 — a Langholm institution. Has a live website with product pages but no e-commerce capability. Given the size of the store and their brand heritage, an online shop or at minimum a 'call to order' catalogue would drive incremental revenue.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "latimersoflangholm.co.uk, welcometolangholm.co.uk",
  },
  {
    business_name: "New Town Convenience Store Langholm",
    url: null,
    location: "Unit 4, Thomas Telford House, Thomas Telford Road, Langholm, DG13 0BF",
    sector: "Retail",
    contact_phone: "01387 380131",
    contact_email: "lornabell26@outlook.com",
    contact_name: "John Ritchie",
    score_need: 8,
    score_pay: 3,
    score_fit: 5,
    score_access: 7,
    score_overall: 5.4,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Google Business Profile optimisation and simple landing page",
    why_them:
      "Local convenience store serving the new Thomas Telford Road development area in Langholm. No website found — relies on Facebook. For a community shop, a simple landing page with opening hours, location and phone number would improve discoverability for newcomers and visitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },

  // ─── LANGHOLM — Professional Services ───────────────────────────────────
  {
    business_name: "JRW Chartered Accountants Langholm",
    url: "https://www.jrwca.com",
    location: "46 High Street, Langholm, DG13 0JH",
    sector: "Professional Services",
    contact_phone: "013873 80730",
    contact_email: "enquiries@jrwca.com",
    contact_name: null,
    score_need: 4,
    score_pay: 8,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website modernisation with local SEO and service pages for SME clients",
    why_them:
      "Regional chartered accountancy firm with a branch on Langholm High Street (also has offices in Hawick, Peebles, Edinburgh). Has a live website but it is a corporate multi-site — the Langholm office has minimal local search visibility. A branch-level local SEO strategy would help capture DG13 SME enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "jrwca.com, welcometolangholm.co.uk, Yell",
  },
  {
    business_name: "Eskvale Business Services",
    url: null,
    location: "28 Caroline Street, Langholm, DG13 0AF",
    sector: "Professional Services",
    contact_phone: "01387 381191",
    contact_email: "enquiries@eskvale.co.uk",
    contact_name: "John Majer",
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter professional services website with services, team and contact",
    why_them:
      "Business services firm in Langholm with an email domain (eskvale.co.uk) but no live website found. Has branded email address suggesting they see value in a professional image — a website would be the logical next step.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },

  // ─── LANGHOLM — Beauty & Wellness ────────────────────────────────────────
  {
    business_name: "Chloe at La Belle",
    url: "http://www.chloeatlabelle.co.uk",
    location: "Market Place, Langholm, DG13 0JQ",
    sector: "Beauty & Wellness",
    contact_phone: "013873 81555",
    contact_email: "chloeatlabelle@gmail.com",
    contact_name: "Chloe Kippen",
    score_need: 5,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online booking, treatment menu and local SEO",
    why_them:
      "Beauty salon specialising in advanced skin analysis and holistic treatments in central Langholm. Has a website but it appears basic — no online booking integration found. Adding a Fresha or similar booking widget and improving local SEO would directly increase appointment volume.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "chloeatlabelle.co.uk, Yell, Cylex, Mister What",
  },
  {
    business_name: "JK Salon Langholm",
    url: null,
    location: "80 High Street, Langholm, DG13 0JH",
    sector: "Beauty & Wellness",
    contact_phone: "01387 380458",
    contact_email: "karenlaidlaw40@gmail.com",
    contact_name: "Karen Muir",
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.8,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter website with service menu, pricing and online booking",
    why_them:
      "Unisex hair salon on Langholm High Street with no website — only listed in local directories. A simple booking-enabled site would immediately capture local and visitor search traffic and reduce reliance on walk-ins.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk, Touch Dumfries",
  },
  {
    business_name: "HMC2 Hair & Beauty Langholm",
    url: null,
    location: "2 Thomas Telford House, Thomas Telford Road, Langholm, DG13 0BF",
    sector: "Beauty & Wellness",
    contact_phone: "01387 383886",
    contact_email: "suzimur@icloud.com",
    contact_name: "Suzanne Murdoch",
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.8,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter website with service list, pricing and booking link",
    why_them:
      "Hair and beauty salon in Langholm's Thomas Telford Road development with no web presence. No website found beyond directory listings. A simple site with services and booking would help capture online enquiries in a town with very limited beauty salon competition online.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk, 192.com",
  },
  {
    business_name: "Emma's Mobile Hairdressing (Bridal Hair & Beauty)",
    url: "https://bridalhairbeauty.co.uk",
    location: "15 Drove Road, Langholm, DG13 0JW",
    sector: "Beauty & Wellness",
    contact_phone: "07545 489597",
    contact_email: "emma@bridalhairandbeauty.co.uk",
    contact_name: "Emma Ritchie",
    score_need: 5,
    score_pay: 5,
    score_fit: 8,
    score_access: 8,
    score_overall: 6.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with bridal gallery, pricing and booking",
    why_them:
      "Mobile bridal hair and beauty specialist in Langholm — a high-value niche. Has a website but bridal search SEO is extremely competitive and a specialist, well-optimised site with a gallery and testimonials would significantly improve enquiry quality and volume from Dumfries & Galloway brides.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },

  // ─── LANGHOLM — Automotive ───────────────────────────────────────────────
  {
    business_name: "Martins Tyre & Auto Services Ltd",
    url: null,
    location: "High Street, Langholm, DG13 0DH",
    sector: "Automotive",
    contact_phone: "01387 380246",
    contact_email: "martinsauto@btconnect.com",
    contact_name: "Grant Adamson",
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.2,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter automotive website with services, tyre booking and contact",
    why_them:
      "Tyre and auto services business on Langholm High Street — not to be confused with T Morrison & Son (which is already in the database as Irvine's Garage). No website found despite having a branded email. An online tyre booking and service enquiry form would directly generate incremental revenue.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },

  // ─── LANGHOLM — Childcare & Education ────────────────────────────────────
  {
    business_name: "Sarah's Childminding Langholm",
    url: null,
    location: "Meiklewood, Langholm, DG13 0PR",
    sector: "Childcare & Education",
    contact_phone: "01387 380164",
    contact_email: "meiklewood11@outlook.com",
    contact_name: "Sarah Phillips",
    score_need: 8,
    score_pay: 3,
    score_fit: 5,
    score_access: 7,
    score_overall: 5.4,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter childminder website with availability, rates and contact",
    why_them:
      "Registered childminder in Langholm with no web presence. In the current environment where parents research childcare online before making contact, a simple information page with Ofsted/SCSWIS registration, availability and rates would meaningfully increase enquiry quality.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },

  // ─── LANGHOLM — Wedding & Events ─────────────────────────────────────────
  {
    business_name: "CastleView Catering (Wedding & Events)",
    url: null,
    location: "The Buccleuch Centre, Langholm, DG13 0AW",
    sector: "Wedding & Events",
    contact_phone: "07468 194551",
    contact_email: "castleviewcatering@gmail.com",
    contact_name: "Tracey Goodfellow",
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 8,
    score_overall: 6.6,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Wedding catering website with packages, gallery and enquiry form",
    why_them:
      "CastleView Catering explicitly offers outside catering for weddings and parties in addition to running the Buccleuch Centre café. A dedicated wedding catering landing page (or section) would help capture brides searching for catering in DG13 — a highly underserved niche.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, welcometolangholm.co.uk, Instagram",
  },

  // ─── LANGHOLM — Home Services ────────────────────────────────────────────
  {
    business_name: "S D Skelton Grounds Maintenance",
    url: null,
    location: "108 Henry Street, Langholm, DG13 0AS",
    sector: "Home Services",
    contact_phone: "07702 079951",
    contact_email: "steskelton@hotmail.co.uk",
    contact_name: "Steve Skelton",
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.8,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter grounds maintenance website with services, area and quote form",
    why_them:
      "Grounds maintenance operative based in Langholm with no web presence. Listed in the local directory with personal email. Rural properties and estates around Eskdale require year-round grounds maintenance — a simple site listing services and coverage would help capture commercial and residential enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },
  {
    business_name: "A&W Irving Painters & Decorators",
    url: null,
    location: "15 Eskdail Street, Langholm, DG13 0BG",
    sector: "Home Services",
    contact_phone: "07718 655378",
    contact_email: "aanddirving@yahoo.com",
    contact_name: "Alistair Irving",
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.8,
    has_website: false,
    website_status: "none",
    social_presence: "listed_only",
    recommended_service: "Starter decorator website with portfolio, services and contact",
    why_them:
      "Painters and decorators in Langholm with no web presence. A portfolio site with before/after photos would significantly improve credibility for larger residential and commercial jobs in DG13.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "welcometolangholm.co.uk local directory",
  },
]

async function main() {
  console.log(`Inserting ${prospects.length} prospects...`)

  const { data, error } = await supabase
    .from("prospects")
    .insert(prospects)
    .select()

  if (error) {
    console.error("Insert error:", error)
    process.exit(1)
  }

  console.log(`Successfully inserted ${data?.length ?? 0} prospects.`)
}

main()
