import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const prospects = [
  {
    business_name: "Crumb",
    url: "http://www.crumbdumfries.co.uk",
    location: "53 St Michael Street, Dumfries, DG1 2QB",
    sector: "Food & Drink",
    contact_phone: "01387 269258",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online booking and SEO",
    why_them: "Popular contemporary casual-dining restaurant (burgers, pizza, pasta, steaks) open since 2017. Has a live website but it's basic — no online booking, thin local SEO presence. Good fit for a modernised site targeting family dining searches in DG1.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, crumbdumfries.co.uk, DG Food and Drink",
  },
  {
    business_name: "La Dolce Vita Dumfries",
    url: "https://ladolcevitadumfries.co.uk",
    location: "94 Irish Street, Dumfries, DG1 2PB",
    sector: "Food & Drink",
    contact_phone: "01387 255689",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website modernisation with online booking and menu showcase",
    why_them: "Family-run Italian restaurant in the town centre with a live website and active Facebook presence. Site is functional but dated — no online booking system, limited SEO targeting Italian restaurant Dumfries searches. Private dining for 20–30 is an untapped upsell hook.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, ladolcevitadumfries.co.uk, DG Food and Drink",
  },
  {
    business_name: "Bruno's Italian Restaurant Dumfries",
    url: "http://www.brunosrestaurant.co.uk",
    location: "3 Balmoral Road, Dumfries, DG1 3BE",
    sector: "Food & Drink",
    contact_phone: "01387 255757",
    contact_email: "brunosrestaurant@hotmail.co.uk",
    contact_name: null,
    score_need: 6,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website rebuild with online booking, modern menu gallery and local SEO",
    why_them: "Established fine Italian dining venue in Dumfries (DG Food and Drink member). Website is live but appears dated — hotmail contact address signals a business not fully invested in its digital presence. Good opportunity for a professional refresh with online table booking.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "brunosrestaurant.co.uk, DG Food and Drink, Yelp",
  },
  {
    business_name: "Casa Mia Dumfries",
    url: "https://www.casamiadumfries.co.uk",
    location: "53 Nunholm Road, Dumfries, DG1 1JW",
    sector: "Food & Drink",
    contact_phone: "01387 269619",
    contact_email: "mail@casamiadumfries.co.uk",
    contact_name: null,
    score_need: 3,
    score_pay: 7,
    score_fit: 7,
    score_access: 8,
    score_overall: 5.35,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO audit and conversion optimisation",
    why_them: "Modern European restaurant on the banks of the River Nith, well regarded and active on Instagram. Has a polished live website and professional email — strong digital presence. Lower priority but worth monitoring for an SEO or Google Ads upsell.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "casamiadumfries.co.uk, DG Food and Drink, TripAdvisor",
  },
  {
    business_name: "Home Restaurant Dumfries",
    url: null,
    location: "48 Whitesands, Dumfries, DG1 2RS",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 6,
    score_fit: 8,
    score_access: 6,
    score_overall: 7.3,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "New website with online booking, menu showcase and local SEO",
    why_them: "Award-winning restaurant (Restaurant of the Year 2023, D&G Life Awards) with no functional website — bookings handled via text/Facebook only. A small family restaurant with real prestige but zero web capture for customers searching online. Strong fit for a conversion-focused brochure site with booking.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, DG Food and Drink, Facebook @homedumfries, Great British Life",
  },
  {
    business_name: "Eatery 53 Dumfries",
    url: "https://www.eatery53.co.uk",
    location: "53 St Michael Street, Dumfries, DG1 2QB",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 4,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and online booking optimisation",
    why_them: "Modern British restaurant with fine dining and vibrant cocktails. Has a live website and Quandoo booking integration. Lower immediate need but could benefit from improved local SEO and a more prominent direct booking flow to reduce third-party commission.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "eatery53.co.uk, TripAdvisor, Quandoo",
  },
  {
    business_name: "Deli 56 Dumfries",
    url: null,
    location: "56 Buccleuch Street, Dumfries, DG1 2AA",
    sector: "Food & Drink",
    contact_phone: "01387 264050",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.35,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Simple brochure website with menu, opening hours and contact",
    why_them: "Well-reviewed sandwich deli on Buccleuch Street with no website — visible only through Facebook and directories. Sandwich shops with strong footfall but no web presence are easy wins for a starter site package. Low investment barrier, fast results.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "DG Food and Drink, TripAdvisor, Yelp",
  },
  {
    business_name: "Above and Below Dumfries",
    url: "https://aboveandbelowdg.co.uk",
    location: "87 Irish Street, Dumfries, DG1 2PQ",
    sector: "Food & Drink",
    contact_phone: "01387 443024",
    contact_email: null,
    contact_name: null,
    score_need: 4,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.6,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO audit and online booking enhancement",
    why_them: "Restaurant and grill (Mediterranean, seafood, ribs) with a live website, Dish Cult booking and good TripAdvisor reviews. Relatively new venue with a modern site — lower priority but could benefit from local SEO targeting Irish Street dining searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "aboveandbelowdg.co.uk, TripAdvisor, Dish Cult",
  },
  {
    business_name: "Pan and Plate Dumfries",
    url: "https://panandplate.co.uk",
    location: "17 Church Crescent, Dumfries, DG1 1DF",
    sector: "Food & Drink",
    contact_phone: "07534 698619",
    contact_email: "info@panandplate.co.uk",
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 8,
    score_access: 8,
    score_overall: 6.25,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and booking system integration",
    why_them: "Newly opened urban-dining restaurant with a modern website and professional email. Good social presence. Lower immediate need for a rebuild but could benefit from local SEO and direct booking to reduce reliance on third-party platforms.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "panandplate.co.uk, TripAdvisor, Dish Cult",
  },
  {
    business_name: "Yamas Deli Dumfries",
    url: "https://yamasdelionline.co.uk",
    location: "35 Bank Street, Dumfries, DG1 2PA",
    sector: "Food & Drink",
    contact_phone: "01387 252700",
    contact_email: "yamasdeli20@outlook.com",
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.05,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with improved menu presentation and local SEO",
    why_them: "Authentic Greek/Mediterranean deli and takeaway on Bank Street with an online ordering site. Outlook email address suggests the owner manages digital presence personally. A professional website upgrade could significantly improve their visibility for Greek food searches in Dumfries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "yamasdelionline.co.uk, TripAdvisor, Facebook",
  },
  {
    business_name: "The Back Street Dumfries",
    url: "https://thebackstreetdumfries.co.uk",
    location: "103 Queensberry Street, Dumfries, DG1 1BH",
    sector: "Food & Drink",
    contact_phone: "01387 248008",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.05,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO optimisation and direct booking integration",
    why_them: "Casual-dining gastropub on Queensberry Street with a live website and good reviews. Has a web presence but limited SEO reach — could benefit from targeted content and a direct booking flow to reduce reliance on third-party reservation platforms.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "thebackstreetdumfries.co.uk, TripAdvisor, Yelp",
  },
  {
    business_name: "Easterbrook Bistro Bar & Spa",
    url: "https://www.easterbrookbistro.co.uk",
    location: "The Crichton, Bankend Road, Dumfries, DG1 4TL",
    sector: "Food & Drink",
    contact_phone: "01387 219081",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 7,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Local SEO and venue hire page enhancement",
    why_them: "Bistro, bar and spa within the Crichton estate — a destination venue with a live website. The site exists but ranks poorly for Dumfries restaurant searches. A targeted SEO campaign could substantially improve discoverability, especially for spa-dining package searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "easterbrookbistro.co.uk, VisitScotland, DG Food and Drink",
  },
  {
    business_name: "Crichton Central Cafe & Bar",
    url: "https://www.crichtoncentral.co.uk",
    location: "The Crichton, Bankend Road, Dumfries, DG1 4TA",
    sector: "Food & Drink",
    contact_phone: "01387 219082",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and Google Business Profile optimisation",
    why_them: "Cafe and bar in the Crichton estate with co-working spaces. Has a live website but limited visibility for general Dumfries cafe searches. Opportunity to improve local SEO and attract more daytime custom beyond the on-site co-working crowd.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "crichtoncentral.co.uk, VisitScotland, DG Food and Drink",
  },
  {
    business_name: "Riverside Tap Dumfries",
    url: "https://www.beerwithoutborders.co.uk/riverside-tap/",
    location: "5 Friars Vennel, Dumfries, DG1 2RQ",
    sector: "Food & Drink",
    contact_phone: "07726 928724",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 6.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Dedicated venue page with SEO and events calendar",
    why_them: "Specialist craft-beer bar near the Robert Burns Centre with strong word-of-mouth but no standalone website — currently a sub-page on the parent Beer Without Borders company site. A dedicated site for Riverside Tap would massively improve discoverability for craft beer and bar searches in Dumfries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "beerwithoutborders.co.uk, CAMRA, TripAdvisor",
  },
  {
    business_name: "Mrs Green's Tea Lounge",
    url: null,
    location: "16 Queensberry Street, Dumfries, DG1 1EX",
    sector: "Food & Drink",
    contact_phone: "07503 116582",
    contact_email: "hello@mrsgreenstealounge.co.uk",
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 8,
    score_access: 7,
    score_overall: 7.0,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Brochure website with afternoon tea booking, menu showcase and local SEO",
    why_them: "Charming afternoon tea lounge on Queensberry Street with an active Instagram and professional email — but no website. Afternoon tea is a high-search, high-conversion category and this business has zero web presence to capture that demand. A stylish brochure site with booking would be an immediate win.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, DG Food and Drink, Instagram @mrsgreenstealounge",
  },
  {
    business_name: "Benvenuto Takeaway Dumfries",
    url: "https://benvenutoonline.co.uk",
    location: "44 Eastfield Road, Dumfries, DG1 2EQ",
    sector: "Food & Drink",
    contact_phone: "01387 256211",
    contact_email: "info@benvenutoonline.co.uk",
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with improved online ordering and local SEO",
    why_them: "Italian takeaway (pizzas, pasta) on Eastfield Road with a live online ordering website and professional email. Site appears functional but older — a modernised site with improved mobile UX and SEO could capture more of the Dumfries pizza/Italian delivery market.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "DG Food and Drink, TripAdvisor, Yelp",
  },
  {
    business_name: "Drummuir Farm Ice Cream",
    url: "https://www.drummuirfarm.co.uk",
    location: "Clarencefield Road, Collin, Dumfries, DG1 4PX",
    sector: "Food & Drink",
    contact_phone: "01387 460833",
    contact_email: null,
    contact_name: null,
    score_need: 4,
    score_pay: 6,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and local discovery optimisation",
    why_them: "Iconic Dumfries ice cream parlour (30+ years, multi-site). Has a live website but limited local SEO reach beyond existing fans. Opportunity to target tourist and family outing searches. Lower priority given strong brand recognition.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "drummuirfarm.co.uk, DG Food and Drink, VisitScotland",
  },
  {
    business_name: "The Granary Dumfries",
    url: null,
    location: "Dobies Building, 21 Loreburn Street, Dumfries, DG1 1HN",
    sector: "Food & Drink",
    contact_phone: "01387 250534",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.35,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Brochure website with events calendar, menu and social integration",
    why_them: "Belhaven-managed pub with food, live sport, DJ nights and a quiz — good footfall but no owned web presence (only a Belhaven sub-page). A standalone site would improve local discoverability and give the manager a platform to promote events and weekly specials.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "belhaven.co.uk/pubs/dumfries-and-galloway/granary, TripAdvisor",
  },
  {
    business_name: "Cafe in the Park Dumfries",
    url: null,
    location: "Dock Park, Dumfries, DG1 2RY",
    sector: "Food & Drink",
    contact_phone: "01387 267740",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 4,
    score_fit: 5,
    score_access: 5,
    score_overall: 5.1,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple brochure website with opening hours and menu",
    why_them: "Council-run cafe in Dock Park with no web presence. Limited budget potential given public-sector ownership, but a simple low-cost website would improve discoverability for park visitors and tourists. Lower priority.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, goingout.co.uk",
  },
  {
    business_name: "The Art Room Cafe Dumfries",
    url: "https://www.the-art-room.co.uk",
    location: "The Old School, Brooke Street, Dumfries, DG1 2JL",
    sector: "Food & Drink",
    contact_phone: "07834 228054",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.35,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with gallery, event booking and local SEO",
    why_them: "Independent family-run cafe/gallery/gift shop hybrid in a stunning converted old school building. Has a website but it appears to serve primarily the art/retail aspect — the cafe section could be significantly better showcased. Strong story-telling opportunity for a Nith Digital case study.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "the-art-room.co.uk, TripAdvisor, VisitScotland",
  },
  {
    business_name: "Kings Coffee and Books Dumfries",
    url: "https://kings-online.co.uk",
    location: "12 Queensberry Street, Dumfries, DG1 1EX",
    sector: "Food & Drink",
    contact_phone: "01387 254444",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and local search optimisation",
    why_them: "Long-established town-centre coffee shop combined with a Christian bookshop. Has a live website. Lower commercial priority but the dual retail/cafe model means any web improvement has double impact. Good fit for a starter SEO package.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "kings-online.co.uk, TripAdvisor, VisitScotland",
  },
  {
    business_name: "The Station Cafe Dumfries",
    url: "https://thestationcafe-cafe.business.site",
    location: "Railway Station, Lovers Walk, Dumfries, DG1 1LU",
    sector: "Food & Drink",
    contact_phone: "01387 262605",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.85,
    has_website: true,
    website_status: "placeholder",
    social_presence: "none",
    recommended_service: "Proper brochure website replacing Google Business site",
    why_them: "Cafe within Dumfries Railway Station — a captive audience of commuters and travellers. Current web presence is only a Google Business Site (placeholder-level). A real website with opening hours, menu and Google Maps integration would be a significant upgrade at minimal cost.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Google Business Site, TripAdvisor, chamberofcommerce.uk",
  },
  {
    business_name: "Palmerston Cafe Dumfries",
    url: "https://palmerstoncafe.com",
    location: "68 Glasgow Street, Dumfries, DG2 9AQ",
    sector: "Food & Drink",
    contact_phone: "01387 254789",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 6,
    score_access: 7,
    score_overall: 5.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website modernisation with online ordering and local SEO",
    why_them: "Family-run fish & chip cafe serving Dumfries since 1969 — an institution. Has a live website but it appears dated. The long heritage is a powerful SEO and storytelling hook. A modernised site with online ordering could capture more of the local fish & chips delivery market.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "palmerstoncafe.com, Yelp, DumfriesDirect.uk",
  },
  {
    business_name: "Snaq at the Arena Dumfries",
    url: "https://www.snaq.uk",
    location: "Queen of the South Arena, Palmerston Park, Dumfries, DG2 9BA",
    sector: "Food & Drink",
    contact_phone: "01387 209885",
    contact_email: "eat@snaq.uk",
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.05,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and local food search optimisation",
    why_them: "Cafe at Queen of the South FC's stadium — open daily to the public (not just on match days). Has a modern Wix-based website but limited local SEO presence. An SEO-optimised proper website would help capture people searching for cafes near Palmerston Park and in the DG2 postcode.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "snaq.uk, food.gov.uk, moo4events.com",
  },
  {
    business_name: "Hugo's Eatery & Bar Dumfries",
    url: "https://hugosdumfries.co.uk",
    location: "23 Bank Street, Dumfries, DG1 2NX",
    sector: "Food & Drink",
    contact_phone: "01387 269028",
    contact_email: null,
    contact_name: null,
    score_need: 4,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.45,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO optimisation and online booking enhancement",
    why_them: "Town-centre cocktail bar and eatery on Bank Street with an OpenTable booking integration and a live website. Lower immediate need but could benefit from direct booking capability (cutting OpenTable commission) and improved local SEO targeting cocktail bar and eatery searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "hugosdumfries.co.uk, OpenTable, Yelp",
  },
  {
    business_name: "The Robert the Bruce (JD Wetherspoon) Dumfries",
    url: "https://www.jdwetherspoon.com/pubs/robert-the-bruce-dumfries/",
    location: "81-83 Buccleuch Street, Dumfries, DG1 1DJ",
    sector: "Food & Drink",
    contact_phone: "01387 270320",
    contact_email: null,
    contact_name: null,
    score_need: 1,
    score_pay: 3,
    score_fit: 1,
    score_access: 2,
    score_overall: 1.7,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "None — national chain",
    why_them: "National JD Wetherspoon chain pub. No web need — fully managed nationally. Included for completeness and to prevent duplicate research.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "jdwetherspoon.com, CAMRA",
  },
  {
    business_name: "The Ship Inn Dumfries",
    url: null,
    location: "97-99 St Michael Street, Dumfries, DG1 2PY",
    sector: "Food & Drink",
    contact_phone: "01387 270764",
    contact_email: "theshipinndumfries@outlook.com",
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.2,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Simple brochure website with pub menu, events and contact",
    why_them: "Historic traditional pub opposite Robert Burns' burial place — excellent location for tourist trade. No website at all, only Facebook and an Outlook email. A basic pub website with the Burns connection as a hook would capture significant tourist search traffic.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "CAMRA, whatpub.com, Restaurantji",
  },
  {
    business_name: "The Worlds End Dumfries",
    url: null,
    location: "27-29 Whitesands, Dumfries, DG1 2RR",
    sector: "Food & Drink",
    contact_phone: "01387 252196",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 5,
    score_access: 6,
    score_overall: 5.65,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Basic pub website with menu and events",
    why_them: "Riverside pub on Whitesands with no web presence beyond Facebook. Whitesands is a high-traffic tourist zone — a basic website targeting pub Whitesands Dumfries searches would improve discoverability at very low cost.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, Yell, inapub.co.uk",
  },
  {
    business_name: "Coach & Horses Inn Dumfries",
    url: "https://www.coachhorses.com",
    location: "66 Whitesands, Dumfries, DG1 2RS",
    sector: "Food & Drink",
    contact_phone: "07746 675349",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.05,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and local search optimisation",
    why_them: "Former coaching inn on Whitesands with river views, live music and a website. Lower priority given existing web presence, but the site could be better optimised for local searches and events promotion.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "coachhorses.com, CAMRA, Yelp",
  },
  {
    business_name: "The Imperial Dumfries",
    url: "https://ambertaverns.co.uk/pub/the-imperial/",
    location: "18-20 Queensberry Street, Dumfries, DG1 1HR",
    sector: "Food & Drink",
    contact_phone: "01387 266191",
    contact_email: null,
    contact_name: null,
    score_need: 3,
    score_pay: 3,
    score_fit: 4,
    score_access: 4,
    score_overall: 3.35,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "None — managed pub chain sub-page",
    why_them: "Amber Taverns managed pub — web presence is a chain sub-page. Limited bespoke web opportunity. Included for prospect database completeness.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "ambertaverns.co.uk, CAMRA, Yelp",
  },
  {
    business_name: "The Riverside Bar Dumfries",
    url: null,
    location: "Dock Park, Dumfries, DG1 2RY",
    sector: "Food & Drink",
    contact_phone: "01387 254477",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Simple brochure website with pub menu, beer garden info and events",
    why_them: "Popular riverside pub in Dock Park — recently reopened under new management (May 2025). No website. Reopening creates a natural hook for a new site pitch: new licensee, fresh start, perfect time to establish an online presence before peak tourist season.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "CAMRA, whatpub.com, Facebook",
  },
  {
    business_name: "The India Palm Dumfries",
    url: "https://www.theindiapalmrestaurant.com",
    location: "46 Buccleuch Street, Dumfries, DG1 2AH",
    sector: "Food & Drink",
    contact_phone: "01387 266644",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 5.9,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online booking and local SEO",
    why_them: "Established Indian restaurant on Buccleuch Street with a live website. The site is functional but could be better optimised for local Indian restaurant searches and could benefit from a direct booking system rather than relying purely on phone reservations.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "theindiapalmrestaurant.com, TripAdvisor, Yelp",
  },
  {
    business_name: "India Palms Takeaway Dumfries",
    url: "https://www.indiapalmsdumfries.co.uk",
    location: "23 Glasgow Street, Dumfries, DG2 9AF",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.35,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Online ordering improvement and local SEO",
    why_them: "Indian takeaway on Glasgow Street (related to or same operator as The India Palm restaurant). Has a live website with online ordering. Could benefit from improved local SEO and a more professional online presence.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "indiapalmsdumfries.co.uk",
  },
  {
    business_name: "Canton Express Dumfries",
    url: null,
    location: "87 St Michael Street, Dumfries, DG1 2PY",
    sector: "Food & Drink",
    contact_phone: "01387 269003",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Simple website with online ordering and local SEO",
    why_them: "Highly rated Chinese takeaway (top-reviewed Chinese in Dumfries per multiple sources) with no website — Facebook only. A simple website with online ordering would capture a large share of the Dumfries Chinese food delivery search market.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Cylex, Facebook, CAMRA, TripAdvisor",
  },
  {
    business_name: "Good Luck Chinese Takeaway Dumfries",
    url: "https://goodlucktakeaway.co.uk",
    location: "9 Queen Street, Dumfries, DG1 2JG",
    sector: "Food & Drink",
    contact_phone: "01387 250303",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.1,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website modernisation with improved online ordering",
    why_them: "Well-reviewed Chinese takeaway with a live ordering website. The domain and site appear older — a refresh with better mobile UX and SEO targeting Chinese food Dumfries delivery searches would improve conversion.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "goodlucktakeaway.co.uk, TripAdvisor, Cylex",
  },
  {
    business_name: "New Oriental Chinese Restaurant Dumfries",
    url: "https://www.neworiental.org",
    location: "54 Friars Vennel, Dumfries, DG1 2RL",
    sector: "Food & Drink",
    contact_phone: "01387 251316",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.45,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website modernisation with online ordering and local SEO",
    why_them: "Long-established Chinese takeaway on Friars Vennel. Has a website but it appears dated. Good opportunity for a modernised online ordering site targeting Chinese food delivery in the DG1 area.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "neworiental.org, TripAdvisor, Facebook",
  },
  {
    business_name: "Phoenix Chinese Takeaway Dumfries",
    url: null,
    location: "82 Annan Road, Dumfries, DG1 3EQ",
    sector: "Food & Drink",
    contact_phone: "01387 248866",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 5,
    score_overall: 5.65,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple website with online ordering",
    why_them: "Highly praised Chinese takeaway on Annan Road with no website and no social media — completely invisible online beyond directories. Cash-only operation suggests a traditional owner who hasn't prioritised digital. A simple ordering website could transform their reach.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, food.gov.uk, Cylex",
  },
  {
    business_name: "Istanbul Kebab House Dumfries",
    url: "https://istanbul-online.co.uk",
    location: "24 Loreburn Street, Dumfries, DG1 1HJ",
    sector: "Food & Drink",
    contact_phone: "01387 262999",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.1,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website modernisation with improved online ordering",
    why_them: "Established kebab and pizza takeaway on Loreburn Street with an online ordering site. The site appears older — a modernised site with better mobile UX and local SEO would help them compete in the busy Dumfries takeaway market.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "istanbul-online.co.uk, Foodhub, Cylex",
  },
  {
    business_name: "Kebab Takeaway Dumfries",
    url: "https://kebabtakeawaydg1.co.uk",
    location: "51 English Street, Dumfries, DG1 2BU",
    sector: "Food & Drink",
    contact_phone: "01387 254965",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.45,
    has_website: true,
    website_status: "live",
    social_presence: "none",
    recommended_service: "Website refresh with improved online ordering and local SEO",
    why_them: "Central English Street kebab and pizza takeaway with its own ordering website. The site exists but appears basic — improving UX and SEO could meaningfully increase their online order volume in a competitive takeaway market.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "kebabtakeawaydg1.co.uk, Yelp, food.gov.uk",
  },
  {
    business_name: "Dante's Fish Chips & Kebab Dumfries",
    url: "https://dantesfishandchips.co.uk",
    location: "97 English Street, Dumfries, DG1 2DA",
    sector: "Food & Drink",
    contact_phone: "01387 266333",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.1,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh and local SEO",
    why_them: "Fish and chips, kebab and pizza takeaway on English Street with a live online ordering site. Has a web presence — lower priority, but a site refresh with improved local SEO targeting fish and chips Dumfries delivery searches could yield solid returns.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "dantesfishandchips.co.uk, TripAdvisor, Just Eat",
  },
  {
    business_name: "Marmaris Takeaway Dumfries",
    url: "https://marmaristakeawaydumfries.co.uk",
    location: "20 Whitesands, Dumfries, DG1 2RR",
    sector: "Food & Drink",
    contact_phone: "01387 268222",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.1,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh and local SEO",
    why_them: "Pizza, kebab, fish and chips and burgers takeaway on busy Whitesands — also an off-licence. Has a live ordering website but limited web visibility. Improving local SEO for the off-licence angle (an unusual combination) is an interesting differentiator.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "marmaristakeawaydumfries.co.uk, TripAdvisor, Facebook",
  },
  {
    business_name: "Noblehill Cafe Dumfries",
    url: "https://www.noblehillchippy.co.uk",
    location: "181 Annan Road, Dumfries, DG1 3EY",
    sector: "Food & Drink",
    contact_phone: "01387 255746",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.35,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with online ordering and heritage storytelling",
    why_them: "Family-run fish and chip cafe on Annan Road since 1971. Has a website. The 50+ year heritage is a powerful brand story — a modernised site with that narrative and online ordering could significantly boost their digital presence.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "noblehillchippy.co.uk, TripAdvisor, thomsonlocal.com",
  },
  {
    business_name: "Anayah's Kitchen Dumfries",
    url: "https://anayahskitchen.com",
    location: "24 Brewery Street, Dumfries, DG1 2RP",
    sector: "Food & Drink",
    contact_phone: "07482 994480",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.05,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Website refresh with improved local SEO and direct ordering",
    why_them: "Indian restaurant and takeaway on Brewery Street with online ordering and an active Facebook page. Good food reputation but the website appears basic — a professional redesign with improved local SEO targeting Indian restaurant Dumfries searches would help them stand out in a competitive market.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "anayahskitchen.com, TripAdvisor, Just Eat",
  },
  {
    business_name: "Best Pizza & Kebab House Dumfries",
    url: null,
    location: "33 English Street, Dumfries, DG1 2BU",
    sector: "Food & Drink",
    contact_phone: "01387 269075",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple website with online ordering",
    why_them: "Central English Street pizza and kebab takeaway with no website and no visible social media presence — entirely reliant on Just Eat and foot traffic. A simple ordering website would give them a direct channel and reduce commission costs.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Yelp, Zmenu, Restaurantji",
  },
]

async function run() {
  const { data: existing } = await supabase.from("prospects").select("business_name")
  const existingNames = new Set((existing ?? []).map((r: any) => r.business_name))
  const toInsert = prospects.filter(
    (p) => !existingNames.has(p.business_name) && (p.url || p.contact_phone || p.contact_email)
  )
  console.log(`Inserting ${toInsert.length} new records...`)
  for (const record of toInsert) {
    const { data, error } = await supabase.from("prospects").insert(record).select("id, business_name")
    if (error) console.error(`✗ ${record.business_name}:`, error.message)
    else console.log(`✓ ${data?.[0]?.business_name}`)
  }
}
run()
