import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const prospects = [
  // ============================================================
  // NEWTON STEWART — Trades & Construction (0 existing)
  // ============================================================
  {
    business_name: "James Scott Builders",
    url: null,
    location: "Holmpark Industrial Estate, Newton Stewart, DG8 6AW",
    sector: "Trades & Construction",
    contact_phone: "01671 401223",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Business website with project gallery and contact form",
    why_them: "Established building contractor on Newton Stewart's main industrial estate with no web presence. Entirely reliant on word of mouth. A simple portfolio site would capture local trade searches and feed enquiries direct.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Adamson Builders & Plasterer",
    url: null,
    location: "Ben-brackie, Newton Stewart, DG8 0PU",
    sector: "Trades & Construction",
    contact_phone: "01581 300291",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple trade website with services list and contact",
    why_them: "Local builder and plasterer operating in the Newton Stewart area with no website or social presence. Relies entirely on word of mouth. A one-page trade site with phone CTA would immediately differentiate them.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "JJM Joiners",
    url: null,
    location: "8 Cairnsmore Avenue, Newton Stewart, DG8 6LA",
    sector: "Trades & Construction",
    contact_phone: "01671 404035",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Trade website with joinery portfolio and quote request",
    why_them: "Local joinery business in Newton Stewart with no digital footprint. Bespoke joinery is a high-value search term — a gallery-led website could attract kitchen, staircase and fitted furniture enquiries across DG8.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "McClymont Electrical",
    url: null,
    location: "Holmpark, Newton Stewart, DG8 6NR",
    sector: "Trades & Construction",
    contact_phone: "01671 403407",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Trade website with NICEIC accreditation display and contact",
    why_them: "Electrical contractor based at Newton Stewart industrial estate. No web presence found. Electricians with no website lose a high-value stream of domestic and commercial enquiries — low competition for DG8 electrician searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "3B Construction",
    url: null,
    location: "South Street Depot, Wigtown, DG8 9SH",
    sector: "Trades & Construction",
    contact_phone: "01988 700000",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Construction company website with project portfolio and tender enquiry form",
    why_them: "Construction company operating from Wigtown depot (Newton Stewart area) with no web presence. A professional site with commercial project gallery would position them for larger contract work across DG8/DG9.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Robert Boan Heating",
    url: null,
    location: "6 Philip Avenue, Newton Stewart, DG8 6HF",
    sector: "Trades & Construction",
    contact_phone: "01671 403093",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Plumbing and heating website with Gas Safe registration display",
    why_them: "Local plumbing and heating engineer in Newton Stewart with no website. Boiler repair and installation searches are high-intent — a simple Gas Safe-led site would capture urgent domestic enquiries across the DG8 area.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // NEWTON STEWART — Food & Drink (6 existing)
  // ============================================================
  {
    business_name: "The Brig-end Pantry",
    url: null,
    location: "78 Victoria Street, Newton Stewart, DG8 6DB",
    sector: "Food & Drink",
    contact_phone: "01671 402003",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple café website with menu and opening hours",
    why_them: "Local café and delicatessen on Victoria Street with no web presence. Visitor-facing businesses in Newton Stewart rely heavily on foot traffic — a simple site with menu and opening hours would capture tourist searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Brambles Bistro & Coffee Shop",
    url: null,
    location: "43 Main Street, Glenluce, DG8 0PP",
    sector: "Food & Drink",
    contact_phone: "01581 300494",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Café website with menu, opening hours and gallery",
    why_them: "Bistro and coffee shop in Glenluce village with no web presence. Located near Glenluce Abbey visitor traffic — a well-optimised site would capture Southern Upland Way walkers and day-tripper food searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Kelvin House Hotel & Restaurant",
    url: null,
    location: "53 Main Street, Glenluce, DG8 0PP",
    sector: "Food & Drink",
    contact_phone: "01581 300303",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Hotel restaurant website with table booking and room promotion",
    why_them: "Hotel restaurant in Glenluce with no visible website. Serves both overnight guests and locals — a site with online booking and food menu would drive direct reservations and reduce reliance on third-party platforms.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Pizza Royal Newton Stewart",
    url: null,
    location: "57 Victoria Street, Newton Stewart, DG8 6NL",
    sector: "Food & Drink",
    contact_phone: "01671 402848",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Takeaway website with online ordering and menu",
    why_them: "Pizza takeaway in Newton Stewart town centre with no website. Takeaways without direct ordering sites pay heavy commission to aggregators — an own-brand ordering site would reduce costs and build a direct customer list.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Cafe Cree",
    url: null,
    location: "48 Victoria Street, Newton Stewart, DG8 6BW",
    sector: "Food & Drink",
    contact_phone: "01671 404203",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Café website with home-cooked menu and events listing",
    why_them: "Home-cooked food café on Victoria Street serving sit-in and takeaway. No web presence — misses all tourist and visitor food searches for the Newton Stewart area. A clean café website would drive foot traffic from the A75 visitor corridor.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Cinnamon Coffee Shop Newton Stewart",
    url: null,
    location: "73-75 Victoria Street, Newton Stewart, DG8 6NL",
    sector: "Food & Drink",
    contact_phone: "01671 404440",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Coffee shop website with menu, home-baking showcase and loyalty scheme info",
    why_them: "Modern spacious coffee shop offering quality home-baked and locally sourced food. No website found. Positioned as a quality independent — a visually appealing site with a menu and story would differentiate from chain cafes.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "The Clansman Wigtown",
    url: null,
    location: "11 The Square, Wigtown, DG8 9SE",
    sector: "Food & Drink",
    contact_phone: "01988 700344",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Pub/restaurant website with food menu and events calendar",
    why_them: "Town square pub in Wigtown (Scotland's National Book Town) with no website. A huge volume of literary festival and book town visitors pass through Wigtown year-round — a simple site with food menu and events would capture this ready-made audience.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Monreith Arms Hotel",
    url: null,
    location: "Monreith, Newton Stewart, DG8 9SE",
    sector: "Food & Drink",
    contact_phone: "01988 700232",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Hotel pub website with food menu, accommodation and wedding enquiry",
    why_them: "Village hotel in Monreith near the sandy beaches of Luce Bay. No website found. A rural hotel with bar food, rooms and function potential — well-suited to a multi-page site targeting coastal visitors, walkers and wedding parties.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // NEWTON STEWART — Accommodation (4 existing)
  // ============================================================
  {
    business_name: "Bruce Hotel Newton Stewart",
    url: null,
    location: "88 Queen Street, Newton Stewart, DG8 6JL",
    sector: "Accommodation",
    contact_phone: "01671 402294",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Hotel website with room booking, bar and function room info",
    why_them: "Town centre hotel in Newton Stewart with no web presence found. All accommodation bookings going to OTAs. A direct booking website would reduce commission costs and allow them to showcase bar, function space and local activity packages.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Galloway Arms Hotel Newton Stewart",
    url: null,
    location: "Victoria Street, Newton Stewart, DG8 6DB",
    sector: "Accommodation",
    contact_phone: "01671 402653",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Hotel website with direct booking and local touring packages",
    why_them: "Traditional hotel on Newton Stewart's main shopping street with no website visible. A direct booking site with Galloway Forest Park proximity as the key USP would cut OTA commissions and attract cycling/walking tourism packages.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Ellangowan Hotel Creetown",
    url: null,
    location: "St John Street, Creetown, DG8 7JF",
    sector: "Accommodation",
    contact_phone: "01671 820201",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Hotel website with room gallery, bar menu and local attractions",
    why_them: "Village hotel in Creetown near the Gem Rock Museum with no online presence found. Creetown has growing visitor interest — a website would capture gem/mineral tourism accommodation searches and film location (The Wicker Man) interest.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Glen Trool Holiday Park",
    url: null,
    location: "Glentrool Village, Newton Stewart, DG8 6RN",
    sector: "Accommodation",
    contact_phone: "01671 840280",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Caravan and camping park website with pitch booking and site map",
    why_them: "Holiday park at the gateway to Galloway Forest Park in Glentrool. No current website found. With 7stanes mountain biking and the Southern Upland Way on the doorstep, a booking-enabled site would attract active outdoor visitors year-round.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Torwood House Hotel",
    url: null,
    location: "Glenluce, DG8 0PB",
    sector: "Accommodation",
    contact_phone: "01581 300469",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Country house hotel website with room booking and wedding/events package",
    why_them: "Country house hotel near Glenluce with no visible website. A scenic property well placed for Southern Upland Way walkers and Rhins of Galloway day-trippers — direct booking site with wedding/events enquiry would reduce OTA dependency.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Kenmuir Arms Hotel",
    url: null,
    location: "31 Main Street, Kirkcowan, DG8 0AJ",
    sector: "Accommodation",
    contact_phone: "01581 600218",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Village hotel website with rooms, bar menu and local activities",
    why_them: "Village inn with rooms in Kirkcowan with no web presence. Rural Wigtownshire accommodation is under-served online — a simple site with room photos, food menu and local fishing/cycling info would attract DG8 corridor visitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // NEWTON STEWART — Retail (8 existing)
  // ============================================================
  {
    business_name: "Stewart R Cunningham Outdoor Centres",
    url: null,
    location: "14-18 Victoria Street, Newton Stewart, DG8 6BT",
    sector: "Retail",
    contact_phone: "01671 401115",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Outdoor sports retail website with e-commerce and gear guides",
    why_them: "Outdoor equipment retailer in Newton Stewart serving walkers and cyclists using the Galloway Forest Park. No website found. With the 7stanes and Southern Upland Way on the doorstep, an e-commerce-capable site with gear guides would drive significant local and visitor sales.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Douglas House Antique Centre",
    url: null,
    location: "Douglas House, Newton Stewart, DG8 6DQ",
    sector: "Retail",
    contact_phone: "01671 403102",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Antique centre website with stock showcase and tearoom info",
    why_them: "Antique centre and tearoom in Newton Stewart with no website. Antique buyers now routinely search online before visiting — a stock showcase with the tearoom element highlighted would attract both day-trippers and specialist collectors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Old Bank Bookshop Wigtown",
    url: null,
    location: "6-7 South Main Street, Wigtown, DG8 9EH",
    sector: "Retail",
    contact_phone: "01988 402111",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Bookshop website with online catalogue and events listing",
    why_them: "Independent bookshop in Wigtown — Scotland's National Book Town. No website found. During Wigtown Book Festival alone over 10,000 visitors descend; a site with stock catalogue, opening hours and events would be used year-round.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "The Creaking Shelves Bookshop",
    url: null,
    location: "12 North Main Street, Wigtown, DG8 9HL",
    sector: "Retail",
    contact_phone: "01988 402902",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Secondhand bookshop website with stock search and events calendar",
    why_them: "Second-hand bookshop on Wigtown's main street with no website. Book Town visitors often pre-plan their shop visits online — a searchable stock catalogue or at minimum an events/opening hours page would capture that audience.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "R & A Dill Furniture",
    url: null,
    location: "15 Lochancroft Lane, Wigtown, DG8 9HZ",
    sector: "Retail",
    contact_phone: "01988 402227",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Furniture retail website with product showcase and contact",
    why_them: "Furniture retailer in Wigtown with no web presence. Furniture buyers increasingly research online before committing — even a simple showcase site with contact form would convert local and regional browsing into footfall.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // NEWTON STEWART — Professional Services (5 existing)
  // ============================================================
  {
    business_name: "Smith and Valentine Solicitors",
    url: null,
    location: "66 Victoria Street, Newton Stewart, DG8 6DD",
    sector: "Professional Services",
    contact_phone: "01671 402813",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Solicitors website with service areas, team profiles and enquiry form",
    why_them: "Long-established solicitors in Newton Stewart with no visible website. Legal firms without websites lose significant search volume to competitors in Castle Douglas and Dumfries — a professional site with service area pages would anchor them locally.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Montpelier Chartered Accountants Newton Stewart",
    url: null,
    location: "1 Dashwood Square, Newton Stewart, DG8 6EQ",
    sector: "Professional Services",
    contact_phone: "01671 403777",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Accountancy practice website with service pages and client portal info",
    why_them: "Chartered accountancy practice in Newton Stewart with no website visible. Accountants are high-value prospects — a professional site with Making Tax Digital, payroll and farm accounts pages would target the DG8 rural business market specifically.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Galloway & Ayrshire Properties Newton Stewart",
    url: null,
    location: "28 Victoria Street, Newton Stewart, DG8 6BT",
    sector: "Professional Services",
    contact_phone: "01671 402104",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Estate agency website with property listings and valuation request",
    why_them: "Local estate agents in Newton Stewart with no dedicated website found. Estate agents without a property search interface lose listings and vendor enquiries to Rightmove-only competitors — a branded site with valuation CTA would build direct pipeline.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // NEWTON STEWART — Home Services (1 existing)
  // ============================================================
  {
    business_name: "Penvale Landscaping and Property Maintenance",
    url: null,
    location: "Newton Stewart, DG8 6HE",
    sector: "Home Services",
    contact_phone: "01671 322154",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Landscaping website with before/after gallery and quote request form",
    why_them: "Landscaping and property maintenance business in Newton Stewart with no web presence. A visual before/after gallery website with seasonal service packages (lawn, hedges, driveways) would generate year-round enquiries across DG8.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Gordon James Engineers",
    url: null,
    location: "Old Station Yard, Wigtown, DG8 9QB",
    sector: "Home Services",
    contact_phone: "01988 840201",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Engineering services website with plant hire and maintenance listing",
    why_them: "Agricultural and industrial engineering firm at Wigtown Old Station Yard with no website. Serving rural DG8 farms and estates — a services page with machinery repair, plant hire and fabrication would position them for commercial search enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // NEWTON STEWART — Beauty & Wellness (3 existing)
  // ============================================================
  {
    business_name: "Hallidays Hair & Beauty",
    url: null,
    location: "37 Queen Street, Newton Stewart, DG8 6JR",
    sector: "Beauty & Wellness",
    contact_phone: "01671 401253",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Hair and beauty salon website with online booking and price list",
    why_them: "Hair and beauty salon on Queen Street with no website found. Beauty salons without online booking lose new client enquiries to competitors who appear in local search. An Instagram-linked booking site would convert social followers to appointments.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Hi Lights Hair Salon Newton Stewart",
    url: null,
    location: "110 Queen Street, Newton Stewart, DG8 6JW",
    sector: "Beauty & Wellness",
    contact_phone: "01671 403601",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Hair salon website with online booking and team profiles",
    why_them: "Hair salon in Newton Stewart with no website visible. In a town of this size there are limited hair salons competing online — a simple site with booking integration would dominate local search for hairdressers DG8.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Creeside Clinic Newton Stewart",
    url: null,
    location: "Creeside Cottage, Newton Stewart, DG8 6RB",
    sector: "Beauty & Wellness",
    contact_phone: "07919 093571",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Aesthetic clinic website with treatments menu, before/after gallery and online booking",
    why_them: "Advanced aesthetics clinic offering laser tattoo removal, hair removal and holistic therapies in Newton Stewart. No website found. Aesthetic clinics depend heavily on visual trust-building — a treatment showcase site with before/after imagery would convert enquiries at a premium.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // NEWTON STEWART — Automotive (6 existing)
  // ============================================================
  {
    business_name: "Old Church Garage Newton Stewart",
    url: null,
    location: "North Street, Newton Stewart, DG8 0QH",
    sector: "Automotive",
    contact_phone: "01581 300795",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Garage website with MOT booking, services list and location map",
    why_them: "Local garage in Newton Stewart with no website. Car owners searching for MOT and servicing DG8 will default to the first result they find — with zero competition from this business online, a simple garage site would capture high-intent local traffic immediately.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // NEWTON STEWART — Healthcare (8 existing)
  // ============================================================
  {
    business_name: "Peter Foulds Opticians Newton Stewart",
    url: null,
    location: "49 Princes Street, Newton Stewart, DG8 6EU",
    sector: "Healthcare",
    contact_phone: "01671 403729",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Independent opticians website with eye test booking and eyewear showcase",
    why_them: "Independent opticians in Newton Stewart with no website. Specsavers dominates search — an independent optician site emphasising personalised service, local family credentials and frame ranges would win patients who prefer non-chain healthcare.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Stranraer Cancer Drop-In Centre",
    url: null,
    location: "83 Victoria Street, Newton Stewart, DG8 6NL",
    sector: "Healthcare",
    contact_phone: "01776 707778",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 3,
    score_fit: 6,
    score_access: 5,
    score_overall: 5.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Charity/health information website with service details and volunteer sign-up",
    why_them: "Cancer drop-in and support centre serving both Newton Stewart and Stranraer areas with no website. A simple information site with services, opening hours and donation/volunteering CTAs would improve reach for those seeking support across DG8/DG9.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // NEWTON STEWART — Childcare & Education (3 existing)
  // ============================================================
  {
    business_name: "Galloway Childcare Company",
    url: null,
    location: "Whithorn Children's Centre, Whithorn, DG8 8PN",
    sector: "Childcare & Education",
    contact_phone: "01988 500902",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Childcare provider website with session types, OFSTED/SCSWIS info and parent portal",
    why_them: "Childcare company operating multiple centres across the Machars peninsula with no website. Parents choosing childcare now research extensively online — a site with setting descriptions, inspection grades and booking enquiry would convert new parent searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Sonja's TLC Childminder",
    url: null,
    location: "49 Queen Street, Newton Stewart, DG8 6JR",
    sector: "Childcare & Education",
    contact_phone: "01671 404119",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 3,
    score_fit: 5,
    score_access: 6,
    score_overall: 5.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Childminder profile website with availability, ethos and parent testimonials",
    why_them: "Registered childminder in Newton Stewart with no web presence. New families moving to the area search for registered childminders online — a simple trust-building profile page with Care Inspectorate registration details and testimonials would generate enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // NEWTON STEWART — Fitness & Leisure (6 existing)
  // ============================================================
  {
    business_name: "Sandar Events Yoga & Wellness",
    url: null,
    location: "Monreith Home Farm Cottage, Newton Stewart, DG8 9LB",
    sector: "Fitness & Leisure",
    contact_phone: "01988 700982",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Yoga and wellness website with class schedule, booking and workshop listings",
    why_them: "Hatha yoga and craft workshop provider in Monreith area with no website. Wellness services depend on visibility — a class schedule with online booking and seasonal retreat offerings would attract visitors and local participants alike.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Ride Borders Mountain Biking",
    url: null,
    location: "Newton Stewart, DG8 9QT",
    sector: "Fitness & Leisure",
    contact_phone: "01988 700974",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Mountain biking guide/hire website with route info and booking",
    why_them: "Mountain biking guide and activity provider near Newton Stewart (gateway to 7stanes trails). No current website visible. The Galloway Forest Park attracts thousands of cyclists — a trails/guide site with booking would capture high-value outdoor tourism spend.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // NEWTON STEWART — Tourism & Attractions (15 existing)
  // ============================================================
  {
    business_name: "Swallow Theatre Newton Stewart",
    url: null,
    location: "Moss Park, Newton Stewart, DG8 8DR",
    sector: "Tourism & Attractions",
    contact_phone: "01988 850368",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 3,
    score_fit: 6,
    score_access: 5,
    score_overall: 5.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Community theatre website with productions calendar, box office and memberships",
    why_them: "Community theatre in the Newton Stewart area with no website. A box office and productions calendar site would make tickets accessible to a wider audience and serve as the permanent home for show marketing across DG8.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "The Real Galloway Tourist Route",
    url: null,
    location: "The Business Centre, Newton Stewart, DG8 6JL",
    sector: "Tourism & Attractions",
    contact_phone: "01671 403875",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 3,
    score_fit: 6,
    score_access: 5,
    score_overall: 5.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Tourism route website with interactive map, member listings and visitor guide",
    why_them: "Tourism route initiative for the Galloway area with no visible website. A digital route guide with interactive map, member business listings and itinerary builder would serve as the definitive online resource for DG8 visitor planning.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // NEWTON STEWART — Wedding & Events (2 existing)
  // ============================================================
  {
    business_name: "Fits The Picture Photography",
    url: null,
    location: "28 Victoria Street, Newton Stewart, DG8 6BT",
    sector: "Wedding & Events",
    contact_phone: "01671 403667",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Wedding photography portfolio website with gallery and enquiry form",
    why_them: "Photographer offering wedding, aerial and 360 virtual tour photography based in Newton Stewart. No portfolio website found. Couples routinely shortlist photographers purely by online portfolio — a well-designed gallery site would convert browsing couples into bookings.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "The Tartan Bunting",
    url: null,
    location: "19 Fineview Crescent, Newton Stewart, DG8 0QJ",
    sector: "Wedding & Events",
    contact_phone: "01581 300245",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Scottish wedding decor e-commerce website with product showcase",
    why_them: "Handmade Scottish bunting and event décor business in Newton Stewart. No website found. Scottish wedding and Burns Night décor has strong national demand — an e-commerce site with Etsy-style showcase would open UK-wide sales beyond local events.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },

  // ============================================================
  // STRANRAER — Trades & Construction (1 existing: McGill Electrical)
  // ============================================================
  {
    business_name: "Stranraer Building & Roofing",
    url: null,
    location: "1 London Road, Stranraer, DG9 8AB",
    sector: "Trades & Construction",
    contact_phone: "01776 703293",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Building and roofing contractor website with project gallery and emergency contact",
    why_them: "Roofing and general building contractor on Stranraer's main approach road with no website. Emergency roofing searches are high-value — a site with before/after gallery, emergency call CTA and local accreditations would generate high-intent enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "McCallum Builders Stranraer",
    url: null,
    location: "37 Queen Street, Stranraer, DG9 7LQ",
    sector: "Trades & Construction",
    contact_phone: "01776 704564",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Builder website with services list, project photos and free quote CTA",
    why_them: "General building contractor in Stranraer town centre with no web presence. With DG9 having very limited builders with websites, a well-optimised site would immediately rank for builder Stranraer and DG9 searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Young Electrical Stranraer",
    url: null,
    location: "Lochryan Street, Stranraer, DG9 7HR",
    sector: "Trades & Construction",
    contact_phone: "01776 707453",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Electrician website with NICEIC badge, services and emergency callout info",
    why_them: "Electrical contractor in Stranraer with no website. Electricians Stranraer DG9 is a low-competition search term — a NICEIC-badged site with EV charger installation and EICR testing pages would generate premium commercial enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Dickson & Mahan Stranraer",
    url: null,
    location: "7 High Street, Stranraer, DG9 7LL",
    sector: "Trades & Construction",
    contact_phone: "01776 702853",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Electrical and building services website with full service listing",
    why_them: "Established electrical and building contractor in Stranraer town centre with no website. A well-structured site covering both electrical and building services would dominate local trade search for combined-trade contractors across DG9.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "JB Sandford Building Services",
    url: null,
    location: "Davaldie Cottage, Stoneykirk, Stranraer, DG9 9DZ",
    sector: "Trades & Construction",
    contact_phone: "01776 830445",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Rural building contractor website with renovation and new build portfolio",
    why_them: "Building services contractor in rural Stoneykirk/Stranraer area with no website. Rural DG9 building work — barn conversions, extensions, farmhouse renovations — is a premium niche. A before/after project site would attract high-value rural renovation enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Colin Taylor Plumbing & Heating Stranraer",
    url: null,
    location: "21 High Park Avenue, Stranraer, DG9 0DE",
    sector: "Trades & Construction",
    contact_phone: "07833 459449",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Plumber website with Gas Safe registration, boiler services and emergency callout",
    why_them: "Plumbing and heating engineer in Stranraer with no website. Boiler breakdown searches are time-critical — a Gas Safe-registered site with visible emergency number and service areas would capture high-conversion urgent enquiries across DG9.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // STRANRAER — Food & Drink (4 existing)
  // ============================================================
  {
    business_name: "Sun Kai Chinese Restaurant Stranraer",
    url: null,
    location: "11-15 Queen Street, Stranraer, DG9 7LQ",
    sector: "Food & Drink",
    contact_phone: "01776 703196",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Restaurant and takeaway website with online ordering and menu",
    why_them: "Chinese restaurant and takeaway on Stranraer's main town street with no website. Online ordering is now the default expectation — a website with direct ordering would reduce aggregator commission and increase average order value.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK / Yelp UK directory",
  },
  {
    business_name: "Fig & Olive Stranraer",
    url: null,
    location: "Stranraer, DG9",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "social_only",
    recommended_service: "Café website with menu, brunch showcase and online booking",
    why_them: "Café and tea room in Stranraer with a Yelp listing but no website found. Brunch and café culture drives strong social and search traffic — a visually appealing site with menu and booking would convert Instagram followers to paying visitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Yelp UK directory",
  },
  {
    business_name: "The Arches Restaurant Stranraer",
    url: null,
    location: "77 Hanover Street, Stranraer, DG9 7RX",
    sector: "Food & Drink",
    contact_phone: "01776 702196",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Restaurant website with menu, private dining and online booking",
    why_them: "Restaurant in Stranraer with no website found. A polished restaurant site with a seasonal menu, private dining section and table booking would capture the pre-ferry diner market — Stranraer sees significant through-traffic from Cairnryan ferry users.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Star Fish Restaurant Stranraer",
    url: null,
    location: "13 Charlotte Street, Stranraer, DG9 7EJ",
    sector: "Food & Drink",
    contact_phone: "01776 707235",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Fish restaurant website with menu, catch of the day and online booking",
    why_them: "Seafood restaurant in Stranraer town centre with no website found. Fresh seafood is a key draw for coastal visitors — a well-photographed site with catch of the day updates and online booking would attract both locals and ferry passengers stopping over.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK / Yelp UK directory",
  },
  {
    business_name: "Smugglers Grill Stranraer",
    url: null,
    location: "10-14 Castle Street, Stranraer, DG9 7RT",
    sector: "Food & Drink",
    contact_phone: "01776 706195",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Grill restaurant website with menu and pre-booking for ferry travellers",
    why_them: "Grill restaurant in Stranraer town centre with no website. A site with a grill menu, opening hours and pre-booking form targeting pre-ferry dining would capture a steady stream of Cairnryan ferry-traveller spend.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Petrucci Restaurant Stranraer",
    url: null,
    location: "2-6 George Street, Stranraer, DG9 7RL",
    sector: "Food & Drink",
    contact_phone: "01776 705837",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Italian restaurant website with menu gallery and table booking",
    why_them: "Italian restaurant on Stranraer's main street with no website found. Italian restaurants with visual menus and booking convert strongly online — a well-photographed pasta/pizza site would dominate Stranraer restaurant search results.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Bay House Restaurant Stranraer",
    url: null,
    location: "Cairnryan Road, Stranraer, DG9 8AT",
    sector: "Food & Drink",
    contact_phone: "01776 706000",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Bay-view restaurant website with menus, functions and direct booking",
    why_them: "Restaurant on the Cairnryan Road — in the direct path of all ferry traffic — with no website found. Strategic location for pre/post ferry dining makes a booking-enabled site extremely high-value for capturing transient customers.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK / Yelp UK directory",
  },
  {
    business_name: "Kirkland Farm Shop & Tea Room",
    url: null,
    location: "Kirkland Farm, Stranraer, DG9 0QP",
    sector: "Food & Drink",
    contact_phone: "01776 870494",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Farm shop and café website with seasonal produce listing and opening hours",
    why_them: "Farm shop and tearoom in Leswalt area of Stranraer with no website. Farm shops with strong digital presence command premium prices and attract affluent foodie tourists — a produce showcase with opening hours and seasonal offers would drive consistent footfall.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // STRANRAER — Accommodation (5 existing)
  // ============================================================
  {
    business_name: "Lighthouse Hotel Corsewall",
    url: null,
    location: "Corsewall Point, Kirkcolm, Stranraer, DG9 0QG",
    sector: "Accommodation",
    contact_phone: "01776 853220",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Boutique lighthouse hotel website with direct booking, dining and wedding packages",
    why_them: "Unique lighthouse conversion hotel on the Rhins of Galloway peninsula — a genuinely premium destination property with no website found. This is exactly the kind of distinctive property that sells itself with great photography — a direct booking site would command premium rates.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Royal Hotel Stranraer",
    url: null,
    location: "Stranraer, DG9 7RZ",
    sector: "Accommodation",
    contact_phone: "01776 702426",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Town centre hotel website with direct booking, bar and function room info",
    why_them: "Traditional hotel in Stranraer town centre with no website visible. A branded direct booking site would reduce OTA commission and allow them to market function rooms and bar directly to the significant local and ferry-traveller market.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Knocknassie House Hotel",
    url: null,
    location: "Kirkcolm, Stranraer, DG9 0QB",
    sector: "Accommodation",
    contact_phone: "01776 854217",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 6,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Country house hotel website with dining, accommodation and private hire",
    why_them: "Country house hotel and restaurant in Kirkcolm (Rhins peninsula) with no website found. Rural country house hotels are high-value accommodation bookings — a site with property photography, dining menus and event hire would generate direct premium bookings.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Corsewall Arms Hotel",
    url: null,
    location: "24 Main Street, Kirkcolm, Stranraer, DG9 0NN",
    sector: "Accommodation",
    contact_phone: "01776 853554",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Village hotel website with rooms, bar menu and local activity info",
    why_them: "Village hotel on the Rhins of Galloway with no web presence. A simple hotel site with rooms, pub food menu and proximity to Corsewall Lighthouse and Portpatrick coastal walk would attract outdoor and touring visitors to the peninsula.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Torrs Warren Country House Hotel",
    url: null,
    location: "Greyhill Road, Stranraer, DG9 9DH",
    sector: "Accommodation",
    contact_phone: "01776 830204",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 6,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Country house hotel website with accommodation, events and direct booking",
    why_them: "Country house hotel near Stranraer with no current website found. A beautifully presented country house site with direct booking for rooms and private events would immediately compete with the nearby Knockinaam Lodge market segment.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Dundream Self-Catering Stranraer",
    url: null,
    location: "Stranraer, DG9 0QQ",
    sector: "Accommodation",
    contact_phone: "07517 373470",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Self-catering holiday cottage website with direct booking calendar",
    why_them: "Gold Star Green Tourism award-winning self-catering coastal accommodation near Stranraer. No website found. Sustainable tourism credentials are increasingly important — a direct booking site with green accreditation showcase would attract premium eco-conscious visitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // STRANRAER — Retail (0 existing)
  // ============================================================
  {
    business_name: "Galloway Carpet Centre Stranraer",
    url: null,
    location: "Thistle Business Park, Stranraer, DG9 7HJ",
    sector: "Retail",
    contact_phone: "01776 889145",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Flooring retail website with product ranges, room inspiration and fitting request",
    why_them: "Carpet and flooring specialist on Stranraer's business park with no website. Flooring buyers in DG9 currently have to travel to Dumfries — a local flooring site with product ranges and free measure CTA would capture significant regional spend.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "John McNeillie Menswear Stranraer",
    url: null,
    location: "85 Hanover Street, Stranraer, DG9 7RS",
    sector: "Retail",
    contact_phone: "01776 703434",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Independent menswear shop website with brand showcase and click & collect",
    why_them: "Independent menswear retailer on Stranraer's main shopping street with no website. Independent fashion retailers without an online presence lose trade to Amazon and national chains — a brand-led site with stock highlights and local delivery would retain loyal customers.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "R Barbour & Sons Stranraer",
    url: null,
    location: "66-70 Hanover Street, Stranraer, DG9 7RP",
    sector: "Retail",
    contact_phone: "01776 702104",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Family retail business website with product showcase and click & collect",
    why_them: "Established family retail business in Stranraer town centre with no website found. Long-running family businesses with loyal local bases benefit enormously from a digital presence that makes them visible to the tourist and new-resident market.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // STRANRAER — Professional Services (4 existing)
  // ============================================================
  {
    business_name: "Ferguson & Company Solicitors Stranraer",
    url: null,
    location: "Clydesdale Bank Buildings, Stranraer, DG9",
    sector: "Professional Services",
    contact_phone: "01776 702561",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Law firm website with practice areas, team profiles and client enquiry form",
    why_them: "Solicitors practice in Stranraer with no website found. Legal firms without websites actively lose enquiries to Dumfries and Castle Douglas competitors — a clean service-area site would anchor local legal searches for DG9.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Craig McIntyre & Peacock Accountants",
    url: null,
    location: "33 Lewis Street, Stranraer, DG9 7LB",
    sector: "Professional Services",
    contact_phone: "01776 703539",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Accountancy practice website with service specialisms, team and client portal link",
    why_them: "Chartered accountancy practice in Stranraer with no website. Accountants are reliable long-term clients — a practice site with self-assessment, VAT and farming accounts pages would target the rural DG9 business base specifically.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "JB Graham Estate Agents Stranraer",
    url: null,
    location: "94 George Street, Stranraer, DG9 7JS",
    sector: "Professional Services",
    contact_phone: "01776 889222",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 7,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Estate agency website with property search, valuation CTA and land/rural property focus",
    why_them: "Local estate agents in Stranraer with no dedicated website. A property search site with a Rhins of Galloway land and rural property focus would attract buyers that national portals underserve — building Stranraer estate agency brand authority.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // STRANRAER — Home Services (1 existing: LWC Cleaning)
  // ============================================================
  {
    business_name: "GMC Cleaning Services Stranraer",
    url: null,
    location: "84 Fairhurst Road, Stranraer, DG9 7QD",
    sector: "Home Services",
    contact_phone: "01776 706184",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Cleaning services website with domestic and commercial packages and quote form",
    why_them: "Cleaning services company in Stranraer with no website. A simple site with domestic, end-of-tenancy and commercial cleaning packages would generate recurring B2B contracts from local hospitality and commercial premises around DG9.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "John Dougan Plumber Stranraer",
    url: null,
    location: "3 Broomfield Gardens, Stranraer, DG9 7EZ",
    sector: "Home Services",
    contact_phone: "01776 704120",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Plumber website with services list and emergency callout number",
    why_them: "Local plumber in Stranraer with no website. Plumber Stranraer searches have almost no local competition in organic results — a simple callout-focused website would rank quickly and generate consistent domestic repair enquiries.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // STRANRAER — Beauty & Wellness (4 existing)
  // ============================================================
  {
    business_name: "DG9 Hair Salon Stranraer",
    url: null,
    location: "14 North Strand Street, Stranraer, DG9 7LD",
    sector: "Beauty & Wellness",
    contact_phone: "01776 889505",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Hair salon website with online booking, team and price list",
    why_them: "Hair salon on Stranraer's North Strand Street with no website. The salon name literally references the DG9 postcode — a locally branded site targeting 'hairdresser Stranraer DG9' would own local search with minimal competition.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "3D Hair & Beauty Stranraer",
    url: null,
    location: "60 George Street, Stranraer, DG9 7JS",
    sector: "Beauty & Wellness",
    contact_phone: "01776 702033",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Hair and beauty salon website with Fresha/online booking integration",
    why_them: "Hair and beauty salon on Stranraer's George Street shopping area with no website. Online booking for hair and beauty is now standard expectation — a site with Fresha integration would reduce no-shows and open new client acquisition.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Mind Body & Sole Therapist Stranraer",
    url: null,
    location: "11A St John Street, Stranraer, DG9 7EN",
    sector: "Beauty & Wellness",
    contact_phone: "01776 258110",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Holistic therapy website with treatment menu, online booking and gift vouchers",
    why_them: "Holistic therapist in Stranraer town centre with no website. Therapy and wellness businesses depend on trusted, professional web presence to convert new clients — a calm, well-designed site with booking and gift vouchers would grow clientele.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // STRANRAER — Automotive (3 existing)
  // ============================================================
  {
    business_name: "Hillands Garage Stoneykirk",
    url: null,
    location: "Stoneykirk, Stranraer, DG9 9DH",
    sector: "Automotive",
    contact_phone: "01776 830239",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 6.0,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Rural garage website with MOT, servicing and recovery services",
    why_them: "Garage in Stoneykirk village on the Rhins of Galloway — sole local service for a wide rural area. No website means they miss all online enquiries from the peninsula. A simple site with MOT booking and breakdown recovery CTA would dominate DG9 9 area searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Autoniq West End Garage Stranraer",
    url: null,
    location: "West End, Stranraer, DG9 0EP",
    sector: "Automotive",
    contact_phone: "01776 700900",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Garage website with used car listings, MOT booking and service packages",
    why_them: "Garage at the west end of Stranraer with no website found. Auto businesses that list used cars online dramatically expand their buyer pool — a site with car listings plus service booking would create two revenue streams digitally.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Leek's Accident Repair Centre Stranraer",
    url: null,
    location: "Hillside Piggery, Stranraer, DG9 7FD",
    sector: "Automotive",
    contact_phone: "01776 703415",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Body shop website with insurance approved accreditation and online estimate",
    why_them: "Accident repair centre in Stranraer with no website. Insurance-approved bodywork is a high-value, repeat-referral business — a professional site with approved repairer status and online estimate form would generate both insurance and private work.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // STRANRAER — Healthcare (5 existing)
  // ============================================================
  {
    business_name: "Urquhart Opticians Stranraer",
    url: null,
    location: "26 Bridge Street, Stranraer, DG9 7JF",
    sector: "Healthcare",
    contact_phone: "01776 704648",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 6,
    score_fit: 7,
    score_access: 7,
    score_overall: 6.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Independent opticians website with eye test booking, frame showcase and contact lens info",
    why_them: "Independent optician in Stranraer with no website — competing against Specsavers on George Street. A site emphasising personal service, independent expertise and local heritage would attract patients who prefer independent opticians over chains.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // STRANRAER — Childcare & Education (2 existing)
  // ============================================================
  {
    business_name: "Stranraer Academy (Community Education)",
    url: "https://www.stranraer.dumgal.sch.uk",
    location: "McMaster Road, Stranraer, DG9 8BY",
    sector: "Childcare & Education",
    contact_phone: "01776 706484",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 4,
    score_fit: 5,
    score_access: 5,
    score_overall: 4.75,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Community education programme website redesign with adult learning sign-up",
    why_them: "Secondary school with community education provision. The school website is a council template — any adult learning, evening class or community programme they run would benefit from a standalone branded landing page for public enrolment.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Local knowledge, council directory",
  },
  // ============================================================
  // STRANRAER — Fitness & Leisure (6 existing)
  // ============================================================
  {
    business_name: "Stranraer Half Marathon",
    url: null,
    location: "Sun Street, Stranraer, DG9 7JJ",
    sector: "Fitness & Leisure",
    contact_phone: "01776 702151",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 3,
    score_fit: 6,
    score_access: 5,
    score_overall: 5.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Race event website with online entry, results archive and sponsorship",
    why_them: "Annual half marathon and 10k running event in Stranraer with no website. A race event site with online entry (Eventbrite/RunBritain integration), results and course map would grow the event's reach and secure local sponsorships.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // STRANRAER — Tourism & Attractions (9 existing)
  // ============================================================
  {
    business_name: "Mull of Galloway Community Trust",
    url: null,
    location: "South Rhinns Community Development Trust, Stranraer, DG9 9DH",
    sector: "Tourism & Attractions",
    contact_phone: "01776 840632",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 3,
    score_fit: 6,
    score_access: 5,
    score_overall: 5.5,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Community tourism website with visitor guide, events and local business directory",
    why_them: "South Rhinns Community Development Trust running visitor facilities at the Mull of Galloway (Scotland's most southerly point). No website found for the Trust itself. A community tourism site would serve as the primary online resource for one of DG9's landmark visitor attractions.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Lakeview Guesthouse Stranraer",
    url: null,
    location: "19 Agnew Crescent, Stranraer, DG9 7JY",
    sector: "Tourism & Attractions",
    contact_phone: "01776 703472",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Guesthouse website with room showcase, direct booking and local attractions guide",
    why_them: "Guesthouse in Stranraer that also appears under tourism directories with no website. A direct booking site with Loch Ryan views photography and local activity guide would enable direct bookings and reduce Booking.com commission.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  // ============================================================
  // STRANRAER — Wedding & Events (3 existing)
  // ============================================================
  {
    business_name: "One Stop Photography Stranraer",
    url: null,
    location: "34a Charlotte Street, Stranraer, DG9 7EF",
    sector: "Wedding & Events",
    contact_phone: "01776 706363",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Wedding and portrait photography website with gallery and package pricing",
    why_them: "Professional wedding and commercial photographer in Stranraer with no portfolio website. Wedding photographers without a polished portfolio site lose bookings to competitors who present their work online — a gallery site with pricing and enquiry form is essential.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
  {
    business_name: "Morgan Images Photography Stranraer",
    url: null,
    location: "Stranraer, DG9 9DX",
    sector: "Wedding & Events",
    contact_phone: "01776 830434",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.25,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Photography portfolio website with wedding gallery and enquiry form",
    why_them: "Photography and media business in the Stranraer area with no website found. A portfolio site with wedding gallery, commercial photography showcase and easy contact form would convert search traffic into qualified enquiries across DG9.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Hotfrog UK directory",
  },
]

async function run() {
  const { data: existing } = await supabase.from("prospects").select("business_name")
  const existingNames = new Set((existing ?? []).map((r: any) => r.business_name))
  const toInsert = prospects.filter(
    (p) => !existingNames.has(p.business_name) && (p.url || p.contact_phone || p.contact_email)
  )
  console.log(`Inserting ${toInsert.length} new records...`)
  for (const record of toInsert) {
    const { data, error } = await supabase.from("prospects").insert(record).select("id, business_name")
    if (error) console.error(`✗ ${record.business_name}:`, error.message)
    else console.log(`✓ ${data?.[0]?.business_name}`)
  }
  console.log("Done.")
}
run()
