import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const prospects = [
  // ── THORNHILL – Food & Drink ──────────────────────────────────────────────
  {
    business_name: "Jinty-B's Cakes & Tearoom",
    url: null,
    location: "68 Drumlanrig Street, Thornhill, DG3 5LY",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 5,
    score_overall: 6.45,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Simple brochure website with menu, opening hours and contact",
    why_them: "Popular cash-only tearoom in Thornhill known for first-class homemade cakes and light lunches — no website at all, discovered only via Facebook and word of mouth. A simple conversion-focused site would capture tourist trade and locals searching 'tearoom Thornhill' online.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, DG Food and Drink, Facebook @JinnysTearoom",
  },
  {
    business_name: "Elmerglen Hotel",
    url: null,
    location: "11 West Morton Street, Thornhill, DG3 5ND",
    sector: "Food & Drink",
    contact_phone: "01848 330558",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Brochure website with menu, rooms and local attraction hooks",
    why_them: "Thornhill pub and hotel with no web presence whatsoever — phone only. Discoverable only via UseYourLocal directory. A basic site with food menu and accommodation info would improve bookings from passing A76 traffic and outdoor activity visitors.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "useyourlocal.com, 192.com",
  },
  {
    business_name: "The Green Tearoom",
    url: null,
    location: "Blacknest, Thornhill Golf Club, Thornhill, DG3 5DW",
    sector: "Food & Drink",
    contact_phone: "01848 331779",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.1,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple website with menu, opening hours and golf club context",
    why_them: "Family-run tearoom at Thornhill Golf Club offering homemade soups, light lunches and baking — vegan and gluten-free options. No dedicated website, only a VisitScotland listing. Ideal candidate for a low-cost site to capture golfer and countryside visitor trade.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "VisitScotland listing, visitthornhill.co.uk",
  },

  // ── THORNHILL – Accommodation ─────────────────────────────────────────────
  {
    business_name: "Trigony House Hotel & Garden Spa",
    url: "https://www.trigonyhotel.co.uk",
    location: "Closeburn, Thornhill, DG3 5EZ",
    sector: "Accommodation",
    contact_phone: "01848 331211",
    contact_email: "info@trigonyhotel.co.uk",
    contact_name: null,
    score_need: 3,
    score_pay: 9,
    score_fit: 6,
    score_access: 8,
    score_overall: 5.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and paid search to compete for Dumfries & Galloway country hotel searches",
    why_them: "Luxury 4-star country house hotel with garden spa at Closeburn — polished live website and professional email. Lower need but an SEO audit or Google Ads campaign targeting 'country hotel Dumfries' keywords could drive incremental bookings in the shoulder season.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "trigonyhotel.co.uk, VisitScotland, TripAdvisor",
  },
  {
    business_name: "Camplebridge B&B",
    url: null,
    location: "Camplebridge, Thornhill, DG3 5EY",
    sector: "Accommodation",
    contact_phone: "01848 331046",
    contact_email: "melkinkead@live.com",
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 5,
    score_overall: 6.45,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "New B&B website with rooms, local attractions and online enquiry form",
    why_them: "Rural B&B on a working riding school estate near Thornhill — hotmail-based email and Facebook-only presence signals a business relying on word-of-mouth. A clean website with photos, pricing and an enquiry form would capture equestrian visitors and Drumlanrig tourists looking online.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "visitthornhill.co.uk, Facebook @CamplebridgeBB",
  },
  {
    business_name: "Camplebridge Steadings",
    url: "http://thornhillselfcateringcottage.co.uk",
    location: "Camplebridge, Thornhill, DG3 5EY",
    sector: "Accommodation",
    contact_phone: "01848 330659",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 5,
    score_fit: 6,
    score_access: 6,
    score_overall: 5.7,
    has_website: true,
    website_status: "live",
    social_presence: "none",
    recommended_service: "Website refresh with modern booking flow and SEO for self-catering searches",
    why_them: "Self-catering cottage at an equestrian estate — existing website appears aged with minimal local SEO footprint. Opportunity for a refresh targeting 'self-catering Thornhill' and 'horse-friendly cottage Dumfries and Galloway' searches.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "thornhillselfcateringcottage.co.uk, visitthornhill.co.uk",
  },

  // ── THORNHILL – Tourism & Attractions ────────────────────────────────────
  {
    business_name: "Drumlanrig Castle & Country Estate",
    url: "https://www.drumlanrigcastle.co.uk",
    location: "Drumlanrig, Carronbridge, Thornhill, DG3 4AQ",
    sector: "Tourism & Attractions",
    contact_phone: "01848 331555",
    contact_email: "info@drumlanrigcastle.co.uk",
    contact_name: null,
    score_need: 2,
    score_pay: 10,
    score_fit: 5,
    score_access: 9,
    score_overall: 4.4,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Targeted digital partnership or sponsored content for Nith Digital local pages",
    why_them: "Major visitor attraction for all of Dumfries & Galloway — Renaissance castle, formal gardens, cycling, woodland walks and events (Electric Fields Festival). Already has a strong digital presence. Lower priority for direct outreach but worth tracking as a prestige anchor client.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "drumlanrigcastle.co.uk, VisitScotland, Tripadvisor",
  },
  {
    business_name: "Electric Fields Festival",
    url: "https://www.electricfieldsfestival.com",
    location: "Drumlanrig Castle, Thornhill, DG3 4AQ",
    sector: "Tourism & Attractions",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 4,
    score_pay: 8,
    score_fit: 5,
    score_access: 7,
    score_overall: 5.2,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "Localised SEO and content partnership for festival visitors searching in DG3",
    why_them: "Boutique annual music festival held on Drumlanrig Castle grounds — strong brand but niche digital footprint outside festival season. Opportunity for a content partnership or local SEO campaign targeting staycation searches for 'music festivals Scotland' and 'DG3 events'.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "electricfieldsfestival.com, VisitScotland, TicketWeb",
  },
  {
    business_name: "Camplebridge Riding School",
    url: "http://www.epony.co.uk",
    location: "Camplebridge, Thornhill, DG3 5EY",
    sector: "Tourism & Attractions",
    contact_phone: "01848 330659",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.35,
    has_website: true,
    website_status: "live",
    social_presence: "facebook_only",
    recommended_service: "Website modernisation with online lesson booking and gift voucher sales",
    why_them: "Horse riding school near Thornhill on a working estate with self-catering accommodation. Existing site is older and lacks online booking — a modernised site with lesson scheduling, gift vouchers and holiday package hooks would convert tourist and local searches more effectively.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "epony.co.uk, Facebook @CamplebridgeRidingSchool, horseridinguk.co.uk",
  },

  // ── THORNHILL – Retail ────────────────────────────────────────────────────
  {
    business_name: "Penpont Village Shop",
    url: null,
    location: "Main Street, Penpont, Thornhill, DG3 4BP",
    sector: "Retail",
    contact_phone: "01848 330907",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 3,
    score_fit: 5,
    score_access: 5,
    score_overall: 5.15,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Simple community shop website with opening times, services and contact",
    why_them: "Family-run village general store serving Penpont since 1983 — groceries, newspapers, lottery and paypoint. No website; discoverable only via Facebook and Royal Mail locator. A basic web presence would help holiday cottage visitors find local services before and during their stay.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Facebook @PenpontVillageShop, Royal Mail branch finder",
  },
  {
    business_name: "Watson's Grocers Moniaive",
    url: null,
    location: "9 High Street, Moniaive, Thornhill, DG3 4HN",
    sector: "Retail",
    contact_phone: "01848 200204",
    contact_email: null,
    contact_name: null,
    score_need: 7,
    score_pay: 3,
    score_fit: 5,
    score_access: 5,
    score_overall: 5.15,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple convenience store web page with opening hours and services",
    why_them: "Premier convenience store serving the village of Moniaive — the primary grocery stop for a large rural catchment. No web presence at all. Even a single-page site with hours, services and contact would improve discoverability for visitors to Moniaive.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "premier-stores.co.uk, misterwhat.co.uk, 192.com",
  },

  // ── THORNHILL – Wedding & Events ─────────────────────────────────────────
  {
    business_name: "Dabton House",
    url: "https://www.dabtonhouse.co.uk",
    location: "Dabton, Thornhill, DG3 5AR",
    sector: "Wedding & Events",
    contact_phone: "07552736599",
    contact_email: "info@dabtonhouse.co.uk",
    contact_name: null,
    score_need: 3,
    score_pay: 10,
    score_fit: 5,
    score_access: 8,
    score_overall: 5.0,
    has_website: true,
    website_status: "live",
    social_presence: "active_with_site",
    recommended_service: "SEO and paid search targeting exclusive-use wedding venue searches in Scotland",
    why_them: "Luxury exclusive-use wedding venue on the Queensberry Estate near Thornhill — restored Buccleuch family home sleeping 20+ with 4 acres of formal gardens, capacity for 200 guests. Already has a polished site. Worth monitoring for an SEO campaign targeting high-value 'exclusive use wedding Scotland' keywords.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "dabtonhouse.co.uk, VisitScotland, Confetti, Scotland Starts Here",
  },

  // ── THORNHILL – Childcare & Education ────────────────────────────────────
  {
    business_name: "Closeburn Nursery",
    url: null,
    location: "Closeburn Primary School, Closeburn, Thornhill, DG3 5HP",
    sector: "Childcare & Education",
    contact_phone: "01848 331240",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 3,
    score_fit: 4,
    score_access: 5,
    score_overall: 4.6,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple informational page within the D&G council site or standalone leaflet-style site",
    why_them: "Council-run nursery attached to Closeburn Primary — no standalone digital presence beyond the D&G council directory. Awareness among new families moving to the rural DG3 area could be improved with a simple informational web page.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Dumfries and Galloway Council ELC directory, Education Scotland",
  },
  {
    business_name: "Penpont Pre-School",
    url: null,
    location: "Penpont Primary School, School Lane, Penpont, Thornhill, DG3 4BH",
    sector: "Childcare & Education",
    contact_phone: "01848 330453",
    contact_email: null,
    contact_name: null,
    score_need: 6,
    score_pay: 3,
    score_fit: 4,
    score_access: 5,
    score_overall: 4.6,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple informational nursery page with intake, sessions and contact",
    why_them: "SCSWIS-rated Good pre-school at Penpont Primary — no website, discovered only via WhichNursery listing. Families relocating to rural Penpont have limited ability to research local childcare online. A basic information page would meaningfully improve discoverability.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "whichnursery.com, Dumfries and Galloway Council ELC directory",
  },

  // ── SANQUHAR – Food & Drink ───────────────────────────────────────────────
  {
    business_name: "Kelloholm Arms",
    url: null,
    location: "Greystone Avenue, Kelloholm, Sanquhar, DG4 6RY",
    sector: "Food & Drink",
    contact_phone: "01659 66844",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 3,
    score_fit: 6,
    score_access: 5,
    score_overall: 5.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple pub website with menu, events and contact",
    why_them: "Local pub in Kelloholm serving the Upper Nithsdale community — no web presence, phone number only. A basic site with menu, events and directions would capture searches from new residents and visitors in the DG4 area.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "useyourlocal.com, pubsgalore.co.uk",
  },
  {
    business_name: "Squire's Bar Kirkconnel",
    url: null,
    location: "41 Main Street, Kirkconnel, Sanquhar, DG4 6NB",
    sector: "Food & Drink",
    contact_phone: "01659 66902",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 3,
    score_fit: 6,
    score_access: 5,
    score_overall: 5.75,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple pub website with menu, opening times and contact",
    why_them: "Village pub in Kirkconnel with no web presence — phone only. Entirely invisible online to anyone searching for food and drink in the Sanquhar/Kirkconnel corridor. A simple brochure site would put this business on the map for tourist and commuter traffic.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "useyourlocal.com, 192.com",
  },
  {
    business_name: "Poppy's Tearoom",
    url: null,
    location: "35 Main Street, Kirkconnel, Sanquhar, DG4 6NB",
    sector: "Food & Drink",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 3,
    score_fit: 7,
    score_access: 5,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Simple tearoom website with menu, opening hours and contact",
    why_them: "Beloved local tearoom in Kirkconnel praised by walkers and locals — no website, Facebook presence only. Walkers on the Southern Upland Way and cycle tourists passing through DG4 searching for a cafe stop have no way to find this business online.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "TripAdvisor, tastyrank.com, vinsights.co.uk",
  },

  // ── SANQUHAR – Accommodation ──────────────────────────────────────────────
  {
    business_name: "Rigg House B&B",
    url: null,
    location: "Rigg Farm, Kelloholm, Sanquhar, DG4 6NR",
    sector: "Accommodation",
    contact_phone: "01659 221230",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 5,
    score_overall: 6.45,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "New B&B website with rooms, local area guide and online enquiry form",
    why_them: "18th century farmhouse B&B in the Kirkconnel Hills overlooking the Upper Nith Valley — outstanding rural views, family-run. Listed on KAYAK, Expedia and Hotels.com but has no direct website of its own. A dedicated site would reduce OTA commissions and build direct bookings.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "uktourismonline.co.uk, KAYAK, Agoda, 192.com",
  },
  {
    business_name: "Queensberry Arms Hotel Kirkconnel",
    url: null,
    location: "71-72 Main Street, Kirkconnel, Sanquhar, DG4 6NB",
    sector: "Accommodation",
    contact_phone: "07532683888",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 5,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.6,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Hotel website with rooms, restaurant menu, bar and events",
    why_them: "Hotel with restaurant and bar in Kirkconnel — mobile number only, no website confirmed by CAMRA. Bookings currently handled via third-party OTAs (Booking.com, LateRooms). A direct website with online enquiry would reduce commission dependency and improve local search visibility.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "CAMRA, Booking.com, TripAdvisor, LateRooms",
  },

  // ── SANQUHAR – Automotive ─────────────────────────────────────────────────
  {
    business_name: "H A Harkness & Sons",
    url: null,
    location: "The Common, Kirkconnel, Sanquhar, DG4 6JT",
    sector: "Automotive",
    contact_phone: "01659 67082",
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 6,
    score_overall: 6.45,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Garage website with MOT booking, services list and contact",
    why_them: "Long-established MOT testing centre in Kirkconnel — no website, discovered only via Autoinsider and Kompass directories. A simple garage site with online MOT booking reminder and service list would modernise this local business and capture new customers in the DG4 corridor.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "autoinsider.co.uk, Kompass, motcentre.info, 192.com",
  },

  // ── SANQUHAR – Beauty & Wellness ─────────────────────────────────────────
  {
    business_name: "Station 49 Hair Salon",
    url: null,
    location: "49 Main Street, Kirkconnel, Sanquhar, DG4 6NB",
    sector: "Beauty & Wellness",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 3,
    score_fit: 7,
    score_access: 5,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Simple salon website with services, prices and online booking",
    why_them: "Hair salon in Kirkconnel with no website and no discoverable social media — only visible in Big Red Directory. A basic Fresha-connected booking site would immediately improve new client discoverability and allow online appointment booking.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "bigreddirectory.com, ukpostcodecheck.com",
  },

  // ── SANQUHAR – Home Services ──────────────────────────────────────────────
  {
    business_name: "S. Milne Exterior Cleaning Services",
    url: null,
    location: "Kirkconnel, Sanquhar, DG4",
    sector: "Home Services",
    contact_phone: null,
    contact_email: null,
    contact_name: null,
    score_need: 8,
    score_pay: 4,
    score_fit: 7,
    score_access: 4,
    score_overall: 5.9,
    has_website: false,
    website_status: "none",
    social_presence: "facebook_only",
    recommended_service: "Simple trades website with services, before/after photos and contact/quote form",
    why_them: "Local exterior cleaning operator in Kirkconnel offering gutter cleaning, pressure washing and window cleaning across Kelloholm and surrounding DG4 area — Facebook only, no website. A trades site with a quote request form and before/after gallery would help capture search traffic from homeowners in Upper Nithsdale.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "Facebook @SMilneExteriorCleaningServices",
  },

  // ── SANQUHAR – Healthcare ─────────────────────────────────────────────────
  {
    business_name: "Kelloholm Clinic",
    url: null,
    location: "Corsrig Crescent, Kelloholm, Sanquhar, DG4 6EL",
    sector: "Healthcare",
    contact_phone: "01659 67376",
    contact_email: null,
    contact_name: null,
    score_need: 5,
    score_pay: 4,
    score_fit: 4,
    score_access: 5,
    score_overall: 4.55,
    has_website: false,
    website_status: "none",
    social_presence: "none",
    recommended_service: "Informational healthcare page with services, clinic times and contact",
    why_them: "NHS satellite health clinic in Kelloholm (part of Upper Nithsdale Group Practice) offering nursing clinics, immunisations and health checks — no standalone web presence beyond the NHS Inform listing. New residents in DG4 have difficulty finding the clinic online. A simple information page would improve awareness.",
    pipeline_status: "prospect",
    outreach_hook: null,
    google_review_count: null,
    google_star_rating: null,
    site_age_signal: null,
    best_outreach_window: null,
    price_range_low: null,
    price_range_high: null,
    source: "bizseek.co.uk, yell.com, scoot.co.uk, nhsinform.scot",
  },
]

async function run() {
  const { data: existing } = await supabase.from("prospects").select("business_name")
  const existingNames = new Set((existing ?? []).map((r: any) => r.business_name))
  const toInsert = prospects.filter(
    (p) => !existingNames.has(p.business_name) && (p.url || p.contact_phone || p.contact_email)
  )
  console.log(`Inserting ${toInsert.length} new records (${prospects.length - toInsert.length} skipped — already exist or no contact signal)...`)
  for (const record of toInsert) {
    const { data, error } = await supabase.from("prospects").insert(record).select("id, business_name")
    if (error) console.error(`✗ ${record.business_name}:`, error.message)
    else console.log(`✓ ${data?.[0]?.business_name}`)
  }
  console.log("Done.")
}
run()
